(function(){
  'use strict';
  const C=window.Cargas,U=C.util;
  C.app={
    activeView:'lab',lastTime:0,accumulator:0,timeSaveAccumulator:0,dailyConfig:null,
    init(){
      C.storage.load();this.applySettings();C.lab.init();C.campaign.init();C.minigames.init();C.quiz.init();this.bindNavigation();this.bindGlobalActions();this.setupHelp();this.setupOnboarding();this.renderDaily();this.renderProgress();this.updateGlobalProgress();this.checkAchievements();
      C.events.on('save:changed',()=>{this.updateGlobalProgress();if(this.activeView==='progress')this.renderProgress();if(this.activeView==='daily')this.renderDaily();});
      document.addEventListener('keydown',event=>this.onKey(event));document.addEventListener('pointerdown',()=>C.audio.unlock(),{once:true,capture:true});document.addEventListener('visibilitychange',()=>{this.lastTime=performance.now();this.accumulator=0;});
      this.lastTime=performance.now();requestAnimationFrame(now=>this.loop(now));
      setTimeout(()=>this.openOnboarding(),180);
    },
    bindNavigation(){document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>this.showView(button.dataset.view)));},
    showView(name){if(!document.getElementById(`view-${name}`))return;if(this.activeView==='campaign'&&name!=='campaign'&&C.campaign.level)C.campaign.sim.playing=false;if(this.activeView==='minigames'&&name!=='minigames'&&C.minigames.current){if(C.minigames.mazeSim)C.minigames.mazeSim.playing=false;if(C.minigames.coulombSim)C.minigames.coulombSim.playing=false;}this.activeView=name;document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active',view.dataset.viewName===name));document.querySelectorAll('[data-view]').forEach(button=>{const active=button.dataset.view===name;button.classList.toggle('active',active);if(button.classList.contains('nav-btn'))active?button.setAttribute('aria-current','page'):button.removeAttribute('aria-current');});if(name==='campaign')C.campaign.renderBrowser();if(name==='minigames')C.minigames.renderGrid();if(name==='daily')this.renderDaily();if(name==='progress')this.renderProgress();document.getElementById('main-content').focus({preventScroll:true});window.scrollTo({top:0,behavior:C.storage.data.settings.reducedMotion?'auto':'smooth'});},
    bindGlobalActions(){
      document.getElementById('help-btn').addEventListener('click',()=>C.ui.open(document.getElementById('help-dialog')));
      document.getElementById('settings-btn').addEventListener('click',()=>C.ui.open(document.getElementById('settings-dialog')));
      document.getElementById('mute-btn').addEventListener('click',()=>{C.storage.update(data=>data.settings.sfx=!data.settings.sfx);this.applySettings();C.ui.toast(C.storage.data.settings.sfx?'Sons ativados':'Sons silenciados');});
      document.getElementById('fullscreen-btn').addEventListener('click',async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch(error){C.ui.toast('Tela cheia indisponível','O navegador bloqueou essa ação.','warning');}});
      document.querySelectorAll('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog')?.close()));
      document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}));
      document.getElementById('setting-sfx').addEventListener('change',e=>{C.storage.update(data=>data.settings.sfx=e.target.checked);this.applySettings();});
      document.getElementById('setting-volume').addEventListener('input',e=>{const value=Number(e.target.value);document.getElementById('volume-output').textContent=`${Math.round(value*100)}%`;C.audio.setVolume(value);});document.getElementById('setting-volume').addEventListener('change',e=>C.storage.update(data=>data.settings.volume=Number(e.target.value)));
      document.getElementById('setting-reduced-motion').addEventListener('change',e=>{C.storage.update(data=>data.settings.reducedMotion=e.target.checked);this.applySettings();});
      document.getElementById('setting-high-contrast').addEventListener('change',e=>{C.storage.update(data=>data.settings.highContrast=e.target.checked);this.applySettings();});
      document.getElementById('setting-text-scale').addEventListener('change',e=>{C.storage.update(data=>data.settings.textScale=Number(e.target.value));this.applySettings();});
      document.getElementById('reopen-tutorial-btn').addEventListener('click',()=>{document.getElementById('settings-dialog').close();this.openOnboarding();});
      document.getElementById('export-save-btn').addEventListener('click',()=>{C.downloadText(`cargas-progresso-${U.dateKey()}.json`,C.storage.export());C.ui.toast('Dados exportados','O arquivo JSON contém progresso e configurações.','success');});
      document.getElementById('import-save-input').addEventListener('change',event=>this.importSave(event));
      document.getElementById('reset-progress-btn').addEventListener('click',()=>this.resetProgress());
      document.getElementById('daily-start-btn').addEventListener('click',()=>this.startDaily());
    },
    applySettings(){const s=C.storage.data.settings;document.body.classList.toggle('reduced-motion',!!s.reducedMotion);document.body.classList.toggle('high-contrast',!!s.highContrast);document.documentElement.style.setProperty('--font-scale',String(s.textScale||1));document.getElementById('setting-sfx').checked=!!s.sfx;document.getElementById('setting-volume').value=s.volume;document.getElementById('volume-output').textContent=`${Math.round(s.volume*100)}%`;document.getElementById('setting-reduced-motion').checked=!!s.reducedMotion;document.getElementById('setting-high-contrast').checked=!!s.highContrast;document.getElementById('setting-text-scale').value=String(s.textScale||1);document.getElementById('mute-btn').textContent=s.sfx?'♪':'×';document.getElementById('mute-btn').setAttribute('aria-label',s.sfx?'Silenciar sons':'Ativar sons');C.audio.setVolume(s.volume);if(C.lab?.initialized){const layerMap={resultant:'layer-resultant',individual:'layer-individual',components:'layer-components',field:'layer-field',lines:'layer-lines',heatmap:'layer-heatmap',trajectories:'layer-trajectories',velocity:'layer-velocity',distance:'layer-distance',grid:'layer-grid',labels:'layer-labels',values:'layer-values'};for(const [key,id] of Object.entries(layerMap)){const input=document.getElementById(id);if(input)input.checked=s.layers[key]!==false;}C.lab.syncLayers();}},
    setupHelp(){const render=tab=>{const root=document.getElementById('help-content');document.querySelectorAll('[data-help-tab]').forEach(btn=>btn.classList.toggle('active',btn.dataset.helpTab===tab));if(tab==='glossary')root.innerHTML=`<div class="glossary-grid">${C.data.glossary.map(([term,desc])=>`<div class="glossary-item"><b>${term}</b><span>${desc}</span></div>`).join('')}</div>`;else if(tab==='science')root.innerHTML=`<div class="science-note"><b>Sobre a precisão</b><br>Este aplicativo usa uma versão simplificada da Lei de Coulomb, suavização em distâncias muito pequenas, limites de velocidade e materiais representados por parâmetros didáticos. Ele é ótimo para visualizar relações e vetores, mas não substitui medições laboratoriais calibradas.</div><div class="glossary-grid" style="margin-top:12px"><div class="glossary-item"><b>Estabilidade</b><span>O motor usa passo de tempo fixo para reduzir diferenças entre dispositivos.</span></div><div class="glossary-item"><b>Unidades</b><span>Força, campo, distância e velocidade usam unidades aproximadas do laboratório.</span></div></div>`;else root.innerHTML=`<div class="glossary-grid"><div class="glossary-item"><b>Arrastar</b><span>Selecione um objeto e mova com mouse, caneta ou toque.</span></div><div class="glossary-item"><b>Espaço</b><span>Inicia ou pausa a simulação visível.</span></div><div class="glossary-item"><b>Delete / Backspace</b><span>Remove o objeto selecionado quando permitido.</span></div><div class="glossary-item"><b>Ctrl/Cmd + Z</b><span>Desfaz a última alteração no laboratório livre.</span></div><div class="glossary-item"><b>R</b><span>Reinicia o experimento ou nível atual.</span></div><div class="glossary-item"><b>F / G</b><span>Alterna força resultante e grade no laboratório.</span></div></div>`;};document.querySelectorAll('[data-help-tab]').forEach(btn=>btn.addEventListener('click',()=>render(btn.dataset.helpTab)));render('controls');},
    setupOnboarding(){this.onboardingSteps=[
      {title:'Sinais criam relações',text:'Cargas positivas usam “+” e contorno contínuo. Negativas usam “−” e marcas segmentadas. Sinais iguais repelem; opostos atraem.'},
      {title:'Arraste e experimente',text:'Escolha uma ferramenta, toque no laboratório para criar e arraste qualquer objeto móvel. A carga verde é a carga-teste q.'},
      {title:'Leia a força resultante',text:'A seta verde soma todas as forças sobre q. Ative forças individuais, componentes, campo e potencial quando quiser investigar mais.'},
      {title:'Neutro também responde',text:'Materiais neutros podem polarizar: regiões opostas se separam e formam um dipolo induzido.'},
      {title:'Atrito transfere elétrons',text:'Encoste materiais diferentes por algum tempo. O aplicativo mostra quem perde e quem ganha elétrons sem saturar instantaneamente.'},
      {title:'Controle o tempo',text:'Use iniciar, pausar, avanço único, velocidade e reset. O tutorial fica disponível no botão de ajuda e nas configurações.'}
    ];document.getElementById('onboarding-next').addEventListener('click',()=>this.nextOnboarding());document.getElementById('onboarding-skip').addEventListener('click',()=>this.finishOnboarding());},
    openOnboarding(){this.onboardingIndex=0;this.renderOnboarding();C.ui.open(document.getElementById('onboarding-dialog'));},
    renderOnboarding(){const step=this.onboardingSteps[this.onboardingIndex];document.getElementById('onboarding-title').textContent=step.title;document.getElementById('onboarding-text').textContent=step.text;document.getElementById('onboarding-dots').innerHTML=this.onboardingSteps.map((_,i)=>`<span class="${i===this.onboardingIndex?'active':''}"></span>`).join('');document.getElementById('onboarding-next').textContent=this.onboardingIndex===this.onboardingSteps.length-1?'Começar':'Continuar';},
    nextOnboarding(){if(this.onboardingIndex<this.onboardingSteps.length-1){this.onboardingIndex++;this.renderOnboarding();C.audio.tone('button');}else this.finishOnboarding();},
    finishOnboarding(){C.storage.update(data=>data.tutorialComplete=true);C.ui.close(document.getElementById('onboarding-dialog'));this.showView('lab');},
    dailyForDate(date=new Date()){const key=U.dateKey(date),random=U.seededRandom(key),types=['field','vector','tribo','maze','coulomb'],type=types[Math.floor(random()*types.length)],difficulty=random()<.28?'easy':random()>.78?'hard':'normal';const names={field:'Constelação de Campo',vector:'Direção Relâmpago',tribo:'Par do Dia',maze:'Rota Invisível',coulomb:'Lançamento Solar'},descriptions={field:'Reproduza o padrão elétrico exclusivo de hoje.',vector:'Resolva uma sequência diária de forças resultantes.',tribo:'Encontre os materiais que produzem o sinal solicitado.',maze:'Guie q pelo labirinto diário sem controle direto.',coulomb:'Ajuste as cargas e acerte o alvo diário.'},icons={field:'⌁',vector:'↗',tribo:'⚡',maze:'◇',coulomb:'◎'};return{key,type,difficulty,name:names[type],description:descriptions[type],icon:icons[type]};},
    renderDaily(){this.dailyConfig=this.dailyForDate();const date=new Date();document.getElementById('daily-date').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(date);document.getElementById('daily-icon').textContent=this.dailyConfig.icon;document.getElementById('daily-type').textContent=`${this.dailyConfig.difficulty==='easy'?'Fácil':this.dailyConfig.difficulty==='hard'?'Difícil':'Normal'} · offline`;document.getElementById('daily-name').textContent=this.dailyConfig.name;document.getElementById('daily-description').textContent=this.dailyConfig.description;const daily=C.storage.data.daily,record=daily.days[this.dailyConfig.key];document.getElementById('daily-current-streak').textContent=`${daily.currentStreak||0} dias`;document.getElementById('daily-best-streak').textContent=`${daily.longestStreak||0} dias`;document.getElementById('daily-best-score').textContent=record?.bestScore||'—';document.getElementById('daily-start-btn').textContent=record?.completed?'Jogar novamente':'Começar desafio de hoje';const calendar=document.getElementById('daily-calendar');calendar.innerHTML='';for(let offset=20;offset>=0;offset--){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate()-offset),key=U.dateKey(d),done=!!daily.days[key]?.completed;const node=document.createElement('div');node.className=`daily-day ${done?'done':''} ${offset===0?'today':''}`;node.title=new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(d);node.textContent=done?'✓':d.getDate();calendar.append(node);}},
    startDaily(){const config=this.dailyConfig||this.dailyForDate();this.showView('minigames');C.minigames.start(config.type,{daily:true,difficulty:config.difficulty});},
    completeDaily(score){const key=U.dateKey(),daily=C.storage.data.daily,existing=daily.days[key];C.storage.update(data=>{const d=data.daily;d.days[key]={completed:true,bestScore:Math.max(existing?.bestScore||0,score),completedAt:new Date().toISOString(),type:this.dailyConfig?.type||C.minigames.current};if(!existing?.completed){const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);const yesterdayKey=U.dateKey(yesterday);d.currentStreak=d.lastCompleted===yesterdayKey?(d.currentStreak||0)+1:1;d.longestStreak=Math.max(d.longestStreak||0,d.currentStreak);d.lastCompleted=key;}});this.unlockAchievement('daily-first');this.renderDaily();},
    unlockAchievement(id,notify=true){if(C.storage.data.achievements[id])return false;const achievement=C.data.achievements.find(a=>a.id===id);if(!achievement)return false;C.storage.update(data=>data.achievements[id]={unlockedAt:new Date().toISOString()});if(notify){C.audio.tone('achievement');C.ui.toast('Conquista desbloqueada',achievement.title,'success',4600);}return true;},
    checkAchievements(){const data=C.storage.data,completed=Object.values(data.campaign.levels).filter(l=>l.completed).length;if(data.stats.frictionTransfers>=10)this.unlockAchievement('tribo-scientist');if(Object.keys(data.experimentsCompleted).length>=C.data.presets.length)this.unlockAchievement('all-experiments');for(let chapter=1;chapter<=6;chapter++){if(C.data.levels.filter(l=>l.chapter===chapter).every(l=>data.campaign.levels[l.id]?.completed)){this.unlockAchievement('chapter-complete');if(chapter===4)this.unlockAchievement('induction-expert');}}if(completed>=30)this.unlockAchievement('campaign-complete');},
    updateGlobalProgress(){const data=C.storage.data,completed=Object.values(data.campaign.levels).filter(l=>l.completed).length,stars=data.campaign.totalStars||Object.values(data.campaign.levels).reduce((s,l)=>s+(l.stars||0),0);document.getElementById('progress-levels').textContent=`${completed}/30 desafios`;document.getElementById('progress-stars').textContent=`${stars} estrelas`;document.getElementById('progress-streak').textContent=`${data.daily.currentStreak||0} dias`;document.getElementById('progress-bar').style.width=`${Math.round(completed/30*100)}%`;},
    renderProgress(){const data=C.storage.data,completed=Object.values(data.campaign.levels).filter(l=>l.completed).length,stars=data.campaign.totalStars||0,quizRate=data.quiz.answered?Math.round(data.quiz.correct/data.quiz.answered*100):0,achievements=Object.keys(data.achievements).length,totalTime=Object.values(data.stats).filter((_,i)=>i<4).reduce((a,b)=>a+(Number(b)||0),0);const cards=[['Desafios',`${completed}/30`,'níveis concluídos'],['Estrelas',stars,'de 90 possíveis'],['Quiz',`${quizRate}%`,`${data.quiz.answered} respostas`],['Conquistas',`${achievements}/${C.data.achievements.length}`,'desbloqueadas'],['Tempo ativo',`${Math.floor(totalTime/60)} min`,'nos modos de estudo']];document.getElementById('profile-stats').innerHTML=cards.map(c=>`<div class="stat-card"><small>${c[0]}</small><strong>${c[1]}</strong><span>${c[2]}</span></div>`).join('');
      const topics=['Sinais','Distância','Vetores','Indução','Atrito','Campo elétrico'];document.getElementById('concept-mastery').innerHTML=topics.map(topic=>{const variants=Object.entries(data.quiz.topics).filter(([name])=>name.toLowerCase().includes(topic.toLowerCase().split(' ')[0]));const answered=variants.reduce((s,[,v])=>s+v.total,0),correct=variants.reduce((s,[,v])=>s+v.correct,0);let campaignBonus=0;if(topic==='Sinais')campaignBonus=this.chapterCompletionRatio(1)*40;if(topic==='Distância')campaignBonus=this.chapterCompletionRatio(2)*40;if(topic==='Vetores')campaignBonus=this.chapterCompletionRatio(3)*40;if(topic==='Indução')campaignBonus=this.chapterCompletionRatio(4)*40;if(topic==='Atrito')campaignBonus=this.chapterCompletionRatio(5)*40;const percent=Math.round(U.clamp((answered?correct/answered*60:0)+campaignBonus,0,100));return`<div class="mastery-item"><span>${topic}</span><div class="mastery-bar"><span style="width:${percent}%"></span></div><b>${percent}%</b></div>`;}).join('');
      document.getElementById('achievement-count').textContent=`${achievements}/${C.data.achievements.length}`;document.getElementById('achievement-grid').innerHTML=C.data.achievements.map(a=>`<div class="achievement ${data.achievements[a.id]?'unlocked':''}"><span class="achievement-icon">${data.achievements[a.id]?a.icon:'◌'}</span><span><b>${a.title}</b><small>${a.description}</small></span></div>`).join('');},
    chapterCompletionRatio(chapter){const levels=C.data.levels.filter(l=>l.chapter===chapter);return levels.filter(l=>C.storage.data.campaign.levels[l.id]?.completed).length/levels.length;},
    async importSave(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const text=await file.text();C.storage.import(text);this.applySettings();C.lab.refreshSavedExperiments();C.campaign.renderBrowser();this.renderDaily();this.renderProgress();this.updateGlobalProgress();C.ui.toast('Dados importados','Progresso validado e carregado.','success');}catch(error){C.ui.toast('Arquivo inválido',error.message||'Não foi possível importar os dados.','error');}},
    async resetProgress(){if(!await C.ui.confirm('Isso apagará níveis, estrelas, quizzes, desafios diários, conquistas e experimentos salvos neste dispositivo.','Resetar todo o progresso'))return;C.storage.reset();this.applySettings();C.lab.refreshSavedExperiments();C.campaign.renderBrowser();this.renderDaily();this.renderProgress();this.updateGlobalProgress();C.ui.toast('Progresso resetado','O laboratório foi restaurado com segurança.');},
    updateActive(dt){if(this.activeView==='lab')C.lab.update(dt);else if(this.activeView==='campaign')C.campaign.update(dt);else if(this.activeView==='minigames')C.minigames.update(dt);else if(this.activeView==='quiz')C.quiz.update(dt);},
    renderActive(now){if(this.activeView==='lab')C.lab.render(now);else if(this.activeView==='campaign')C.campaign.render(now);else if(this.activeView==='minigames')C.minigames.render(now);else if(this.activeView==='quiz')C.quiz.render(now);},
    loop(now){let frame=Math.min((now-this.lastTime)/1000,C.CONSTANTS.MAX_FRAME);this.lastTime=now;if(!document.hidden){this.accumulator+=frame;let steps=0;while(this.accumulator>=C.CONSTANTS.FIXED_DT&&steps<10){this.updateActive(C.CONSTANTS.FIXED_DT);this.accumulator-=C.CONSTANTS.FIXED_DT;steps++;}this.renderActive(now);this.trackTime(frame);}requestAnimationFrame(t=>this.loop(t));},
    trackTime(dt){this.timeSaveAccumulator+=dt;const key={lab:'timeLab',campaign:'timeCampaign',quiz:'timeQuiz',minigames:'timeMinigames'}[this.activeView];if(key)C.storage.data.stats[key]=(C.storage.data.stats[key]||0)+dt;if(this.timeSaveAccumulator>12){this.timeSaveAccumulator=0;C.storage.save();}},
    onKey(event){const open=document.querySelector('dialog[open]');if(open&&event.key==='Escape'){event.preventDefault();open.close();return;}if(C.lab.onKey(event))return;if(C.campaign.onKey(event))return;if(C.minigames.onKey(event))return;if(C.quiz.onKey(event))return;}
  };

  window.addEventListener('DOMContentLoaded',()=>C.app.init());
})();
