(function(){
  'use strict';
  const C=window.Cargas,U=C.util;
  C.campaign={
    initialized:false,chapter:1,level:null,drag:null,hintsUsed:0,resets:0,moves:0,failed:false,lastUi:0,
    init(){if(this.initialized)return;this.initialized=true;this.stage=new C.CanvasStage(document.getElementById('canvas-campaign'));this.sim=new C.PhysicsSimulation({mode:'campaign',settings:{chargeDynamics:false}});this.renderer=new C.PhysicsRenderer(this.stage,this.sim);this.renderer.setLayers({resultant:true,individual:false,components:false,field:false,lines:false,heatmap:false,trajectories:true,velocity:false,distance:false,grid:true,labels:true,values:false});this.bind();this.renderBrowser();},
    bind(){
      document.getElementById('campaign-practice-btn').addEventListener('click',()=>C.app.showView('lab'));
      document.getElementById('campaign-close-btn').addEventListener('click',()=>this.closeLevel());
      document.getElementById('campaign-play-btn').addEventListener('click',()=>this.togglePlay());
      document.getElementById('campaign-step-btn').addEventListener('click',()=>{this.sim.stepOnce();this.updateUi(true);});
      document.getElementById('campaign-reset-btn').addEventListener('click',()=>this.resetLevel(true));
      document.getElementById('campaign-delete-btn').addEventListener('click',()=>this.deleteSelected());
      document.querySelectorAll('[data-campaign-add]').forEach(btn=>btn.addEventListener('click',()=>this.addCharge(Number(btn.dataset.campaignAdd))));
      document.getElementById('campaign-hint-btn').addEventListener('click',()=>this.revealHint());
      document.getElementById('campaign-force-toggle').addEventListener('change',e=>this.renderer.layers.resultant=e.target.checked);
      document.getElementById('campaign-field-toggle').addEventListener('change',e=>this.renderer.layers.field=e.target.checked);
      document.getElementById('campaign-trail-toggle').addEventListener('change',e=>this.renderer.layers.trajectories=e.target.checked);
      const canvas=this.stage.canvas;canvas.addEventListener('pointerdown',event=>{event.preventDefault();C.audio.unlock();canvas.setPointerCapture?.(event.pointerId);const p=this.stage.point(event),hit=this.sim.hitTest(p);if(hit&&hit.type!=='test'&&!hit.fixed){this.sim.selectedId=hit.id;this.drag={id:hit.id,ox:p.x-hit.x,oy:p.y-hit.y,startX:hit.x,startY:hit.y};hit.vx=hit.vy=0;}else if(hit?.type==='charge'){this.sim.selectedId=hit.id;this.drag={id:hit.id,ox:p.x-hit.x,oy:p.y-hit.y,startX:hit.x,startY:hit.y};}else this.sim.selectedId=null;});canvas.addEventListener('pointermove',event=>{if(!this.drag)return;event.preventDefault();const p=this.stage.point(event),o=this.sim.scene.objects.find(x=>x.id===this.drag.id);if(o)this.sim.setPosition(o,p.x-this.drag.ox,p.y-this.drag.oy);});canvas.addEventListener('pointerup',()=>{if(this.drag){const o=this.sim.scene.objects.find(x=>x.id===this.drag.id);if(o&&Math.hypot(o.x-this.drag.startX,o.y-this.drag.startY)>8)this.moves++;this.drag=null;this.updateUi(true);}});
    },
    renderBrowser(){
      const tabs=document.getElementById('chapter-tabs');tabs.innerHTML=C.data.chapters.map(ch=>{const progress=this.chapterProgress(ch.id);return`<button role="tab" aria-selected="${this.chapter===ch.id}" class="${this.chapter===ch.id?'active':''}" data-chapter="${ch.id}"><b>${ch.icon} Capítulo ${ch.id}</b><small>${progress.done}/5 concluídos</small></button>`;}).join('');tabs.querySelectorAll('[data-chapter]').forEach(btn=>btn.addEventListener('click',()=>{this.chapter=Number(btn.dataset.chapter);this.renderBrowser();}));
      const chapter=C.data.chapters[this.chapter-1],progress=this.chapterProgress(this.chapter);document.getElementById('chapter-summary').innerHTML=`<span class="eyebrow">Capítulo ${chapter.id}</span><h2>${chapter.title}</h2><p>${chapter.subtitle}. ${progress.stars} de 15 estrelas conquistadas.</p>`;
      const levels=C.data.levels.filter(l=>l.chapter===this.chapter);document.getElementById('level-grid').innerHTML=levels.map(level=>{const record=C.storage.data.campaign.levels[level.id]||{};const unlocked=this.isUnlocked(level.id);const stars=record.stars||0;return`<button class="level-card" data-level="${level.id}" ${unlocked?'':'disabled'} aria-label="${unlocked?`Abrir nível ${level.id}: ${level.title}`:`Nível ${level.id} bloqueado`}"><span class="level-number">${unlocked?level.index:'🔒'}</span><span class="level-stars">${[1,2,3].map(n=>`<span class="${n<=stars?'earned':''}">★</span>`).join('')}</span><h3>${level.title}</h3><p>${unlocked?level.objective:'Complete o nível anterior para desbloquear.'}</p></button>`;}).join('');document.querySelectorAll('[data-level]').forEach(btn=>btn.addEventListener('click',()=>this.startLevel(Number(btn.dataset.level))));
    },
    chapterProgress(id){const levels=C.data.levels.filter(l=>l.chapter===id);return{done:levels.filter(l=>C.storage.data.campaign.levels[l.id]?.completed).length,stars:levels.reduce((sum,l)=>sum+(C.storage.data.campaign.levels[l.id]?.stars||0),0)};},
    isUnlocked(id){return id===1||!!C.storage.data.campaign.levels[id-1]?.completed||!!C.storage.data.campaign.levels[id]?.completed;},
    startLevel(id){const level=C.data.levels.find(l=>l.id===id);if(!level||!this.isUnlocked(id))return;this.level=level;this.hintsUsed=0;this.resets=0;this.moves=0;this.failed=false;document.getElementById('campaign-browser').classList.add('hidden');document.getElementById('campaign-player').classList.remove('hidden');this.loadLevelScene();document.getElementById('campaign-chapter-label').textContent=`Capítulo ${level.chapter} · Nível ${level.index}`;document.getElementById('campaign-level-title').textContent=level.title;document.getElementById('campaign-level-objective').textContent=level.objective;document.getElementById('campaign-hint').textContent='Comece observando a posição inicial e o alvo.';document.getElementById('hint-cost').textContent='0 usadas';this.renderRules();this.updateUi(true);},
    loadLevelScene(){const level=this.level;this.sim.settings.dwell=level.dwell||.72;this.sim.settings.maxTargetSpeed=level.maxTargetSpeed||90;this.sim.loadScene(level.scene);this.sim.onComplete=result=>this.completeLevel(result);this.sim.playing=false;},
    closeLevel(){this.sim.playing=false;this.level=null;document.getElementById('campaign-player').classList.add('hidden');document.getElementById('campaign-browser').classList.remove('hidden');this.renderBrowser();},
    renderRules(){const l=this.level;const sign=l.allowed==='positive'?'somente +':l.allowed==='negative'?'somente −':l.allowed==='none'?'sem cargas externas':'±';const rules=[['Limite',`${l.maxCharges} cargas`],['Sinais',sign],['Alvo',`velocidade ≤ ${l.maxTargetSpeed||90} u/s`]];if(l.timeLimit)rules.push(['Tempo',`${l.timeLimit} s`]);if(l.moveLimit)rules.push(['Movimentos',`${l.moveLimit}`]);document.getElementById('campaign-rules').innerHTML=rules.map(r=>`<div class="rule"><span>${r[0]}</span><b>${r[1]}</b></div>`).join('');document.querySelector('[data-campaign-add="1"]').disabled=l.allowed==='negative'||l.allowed==='none';document.querySelector('[data-campaign-add="-1"]').disabled=l.allowed==='positive'||l.allowed==='none';},
    addedCharges(){const initial=this.level.scene.objects.filter(o=>o.type==='charge').length;return Math.max(0,this.sim.scene.objects.filter(o=>o.type==='charge').length-initial);},
    addCharge(sign){if(!this.level)return;if(this.addedCharges()>=this.level.maxCharges){C.ui.toast('Limite de cargas atingido',`Este nível permite ${this.level.maxCharges}.`,'warning');C.audio.tone('error');return;}if((this.level.allowed==='positive'&&sign<0)||(this.level.allowed==='negative'&&sign>0)||this.level.allowed==='none'){C.ui.toast('Sinal não permitido','Confira as regras do nível.','warning');C.audio.tone('error');return;}const intensity=this.level.chargeIntensity||1.5;this.sim.addObject(sign>0?'positive':'negative',450,270,{q:sign*intensity,fixed:true,name:'Carga do jogador'});this.moves++;C.audio.tone('place');this.updateUi(true);},
    deleteSelected(){const o=this.sim.selected;if(!o||o.type!=='charge'||o.name!=='Carga do jogador'){C.ui.toast('Selecione uma carga sua','Objetos do cenário não podem ser excluídos.');return;}this.sim.removeSelected();this.moves++;this.updateUi(true);},
    togglePlay(){if(!this.level)return;this.sim.playing=!this.sim.playing;C.audio.tone('button');this.updateUi(true);},
    resetLevel(count=true){if(!this.level)return;if(count)this.resets++;this.loadLevelScene();this.moves=0;this.updateUi(true);C.audio.tone('button');},
    revealHint(){if(!this.level||this.hintsUsed>=3){C.ui.toast('Todas as dicas foram reveladas');return;}const hint=this.level.hints[this.hintsUsed];this.hintsUsed++;document.getElementById('campaign-hint').textContent=hint;document.getElementById('hint-cost').textContent=`${this.hintsUsed} ${this.hintsUsed===1?'usada':'usadas'}`;if(this.hintsUsed===3){const t=this.sim.scene.target;this.sim.effect('success',Math.max(80,t.x-150),t.y,{quiet:false});}C.audio.tone('button');},
    calculateResult(){const l=this.level,time=this.sim.elapsed;let score=1000-Math.round(time*5)-this.hintsUsed*120-this.resets*70-Math.max(0,this.moves-(l.maxCharges||0))*18;if(l.timeLimit&&time<l.timeLimit*.6)score+=80;if(l.moveLimit&&this.moves<=l.moveLimit)score+=70;score=U.clamp(score,250,1200);const stars=score>=850?3:score>=620?2:1;return{score,stars,time};},
    completeLevel(){if(!this.level)return;const level=this.level,result=this.calculateResult(),previous=C.storage.data.campaign.levels[level.id]||{};C.storage.update(data=>{data.campaign.levels[level.id]={completed:true,stars:Math.max(previous.stars||0,result.stars),bestScore:Math.max(previous.bestScore||0,result.score),bestTime:previous.bestTime?Math.min(previous.bestTime,result.time):result.time};data.campaign.totalStars=Object.values(data.campaign.levels).reduce((sum,l)=>sum+(l.stars||0),0);});if(this.hintsUsed===0)C.app.unlockAchievement('no-hints');if(result.stars===3)C.app.unlockAchievement('three-stars');if(level.id===13)C.app.unlockAchievement('perfect-balance');C.app.unlockAchievement('first-attraction');C.app.checkAchievements();C.ui.result({kicker:`Nível ${level.id} completo`,title:level.title,description:level.explanation,icon:'★',details:[{label:'Estrelas',value:'★'.repeat(result.stars)+'☆'.repeat(3-result.stars)},{label:'Pontuação',value:result.score},{label:'Tempo',value:U.formatTime(result.time)},{label:'Dicas',value:this.hintsUsed}],primary:level.id<30?'Próximo nível':'Ver campanha',secondary:'Seleção de níveis',onPrimary:()=>{if(level.id<30){const next=level.id+1;this.level=null;this.startLevel(next);}else this.closeLevel();},onSecondary:()=>this.closeLevel()});},
    fail(reason){if(this.failed||!this.level)return;this.failed=true;this.sim.playing=false;C.audio.tone('error');C.ui.result({kicker:'Tentativa encerrada',title:'Quase lá',description:reason,icon:'↻',details:[{label:'Tempo',value:U.formatTime(this.sim.elapsed)},{label:'Movimentos',value:this.moves}],primary:'Tentar novamente',secondary:'Voltar aos níveis',onPrimary:()=>{this.failed=false;this.resetLevel(true);},onSecondary:()=>this.closeLevel()});},
    update(dt){if(!this.level)return;this.sim.step(dt);if(this.level.timeLimit&&this.sim.elapsed>=this.level.timeLimit)this.fail('O tempo terminou. Ajuste as cargas antes de iniciar para ganhar velocidade.');if(this.level.moveLimit&&this.moves>this.level.moveLimit)this.fail('O limite de movimentos foi ultrapassado. Planeje a configuração antes de mover os objetos.');},
    render(now){if(!this.level)return;this.renderer.render(now);if(now-this.lastUi>100){this.updateUi();this.lastUi=now;}},
    updateUi(){if(!this.level)return;const status=document.getElementById('campaign-status'),btn=document.getElementById('campaign-play-btn');status.classList.toggle('paused',!this.sim.playing);status.innerHTML=`<i></i> ${this.sim.playing?'Em execução':'Pausada'}`;btn.innerHTML=this.sim.playing?'<span>Ⅱ</span><b>Pausar</b>':'<span>▶</span><b>Iniciar</b>';document.getElementById('campaign-condition').textContent=`${this.addedCharges()}/${this.level.maxCharges} cargas · ${this.moves} mov.`;document.getElementById('campaign-timer').textContent=U.formatTime(this.sim.elapsed);const pct=U.clamp(this.sim.targetDwell/(this.sim.settings.dwell||.7),0,1);document.getElementById('campaign-target-status').textContent=pct>0?`Estabilizando no alvo: ${Math.round(pct*100)}%`:'Mantenha q no alvo em baixa velocidade';},
    onKey(event){if(C.app?.activeView!=='campaign'||!this.level||document.querySelector('dialog[open]'))return false;const key=event.key.toLowerCase();if(key===' '){event.preventDefault();this.togglePlay();return true;}if(key==='r'){event.preventDefault();this.resetLevel(true);return true;}if(key==='escape'){event.preventDefault();this.closeLevel();return true;}if(event.key==='Delete'||event.key==='Backspace'){event.preventDefault();this.deleteSelected();return true;}return false;}
  };
})();
