(function(){
  'use strict';
  const C=window.Cargas,U=C.util,K=C.CONSTANTS;
  const dirs=[['↖',-3*Math.PI/4],['↑',-Math.PI/2],['↗',-Math.PI/4],['←',Math.PI],['•',null],['→',0],['↙',3*Math.PI/4],['↓',Math.PI/2],['↘',Math.PI/4]];
  C.minigames={
    initialized:false,current:null,state:null,daily:false,difficulty:'normal',lastUi:0,
    init(){if(this.initialized)return;this.initialized=true;this.stage=new C.CanvasStage(document.getElementById('canvas-minigame'));this.ctx=this.stage.ctx;this.bind();this.renderGrid();},
    bind(){document.getElementById('minigame-close-btn').addEventListener('click',()=>this.close());const canvas=this.stage.canvas;canvas.addEventListener('pointerdown',event=>{event.preventDefault();C.audio.unlock();canvas.setPointerCapture?.(event.pointerId);this.pointerDown(this.stage.point(event),event);});canvas.addEventListener('pointermove',event=>{if(!this.state?.drag)return;event.preventDefault();this.pointerMove(this.stage.point(event));});canvas.addEventListener('pointerup',()=>this.pointerUp());},
    renderGrid(){const grid=document.getElementById('minigame-grid');grid.innerHTML=C.data.minigames.map(game=>{const best=C.storage.data.minigames[game.id]?.bestScore||0;return`<button class="minigame-card" data-game="${game.id}"><span class="game-icon">${game.icon}</span><h2>${game.title}</h2><p>${game.description}</p><div class="minigame-meta"><span>${game.concept}</span><b>${best?`${game.bestLabel}: ${best}`:'Ainda não jogado'}</b></div></button>`;}).join('');grid.querySelectorAll('[data-game]').forEach(btn=>btn.addEventListener('click',()=>this.start(btn.dataset.game)));},
    start(id,options={}){const game=C.data.minigames.find(g=>g.id===id);if(!game)return;this.current=id;this.daily=!!options.daily;this.difficulty=options.difficulty||'normal';document.getElementById('minigame-grid').classList.add('hidden');document.getElementById('minigame-player').classList.remove('hidden');document.getElementById('minigame-kicker').textContent=this.daily?'Desafio diário':game.concept;document.getElementById('minigame-title').textContent=game.title;document.getElementById('minigame-instructions').textContent=game.description;document.getElementById('minigame-explanation').textContent=this.explanation(id);this.setup(id);},
    close(){this.current=null;this.state=null;this.daily=false;document.getElementById('minigame-player').classList.add('hidden');document.getElementById('minigame-grid').classList.remove('hidden');this.renderGrid();},
    explanation(id){return({field:'As setas representam a direção do campo que uma carga-teste positiva sentiria em cada ponto. Compare direção e intensidade do padrão.',maze:'Você controla o campo, não a partícula. A resultante elétrica curva a trajetória de q enquanto obstáculos resolvem colisões.',tribo:'Materiais mais acima na série tendem a perder elétrons; materiais mais abaixo tendem a ganhar e ficar negativos.',vector:'Calcule mentalmente atração, repulsão e distância. Depois some as contribuições como vetores.',coulomb:'A posição, o sinal e a intensidade das cargas determinam a aceleração inicial e toda a trajetória.'})[id];},
    setup(id){if(id==='field')this.setupField();else if(id==='maze')this.setupMaze();else if(id==='tribo')this.setupTribo();else if(id==='vector')this.setupVector();else if(id==='coulomb')this.setupCoulomb();},
    commonDifficulty(onChange){return`<label><span>Dificuldade</span><select id="mg-difficulty"><option value="easy">Fácil</option><option value="normal" selected>Normal</option><option value="hard">Difícil</option></select></label>`;},
    setControls(html){const root=document.getElementById('minigame-controls');root.innerHTML=html;return root;},
    setHud(status,score,progress,extra){document.getElementById('minigame-status').textContent=status;document.getElementById('minigame-score').textContent=score;document.getElementById('minigame-progress').textContent=progress;document.getElementById('minigame-extra').textContent=extra;},
    finish(score,details,description){const id=this.current;const previous=C.storage.data.minigames[id]?.bestScore||0;C.storage.update(data=>{data.minigames[id]={...(data.minigames[id]||{}),bestScore:Math.max(previous,Math.round(score)),plays:(data.minigames[id]?.plays||0)+1};});if(this.daily)C.app.completeDaily(Math.round(score));C.audio.tone('success');C.ui.result({kicker:'Minigame concluído',title:C.data.minigames.find(g=>g.id===id).title,description,icon:'✦',details:[{label:'Pontuação',value:Math.round(score)},...details],primary:'Jogar novamente',secondary:'Ver minigames',onPrimary:()=>this.setup(id),onSecondary:()=>this.close()});},

    // FIELD LINE BUILDER
    fieldTargets(){return{
      easy:[{x:280,y:270,q:2},{x:620,y:270,q:-2}],
      normal:[{x:250,y:170,q:2},{x:650,y:170,q:2},{x:450,y:400,q:-3}],
      hard:[{x:200,y:170,q:2.5},{x:700,y:370,q:-2.5},{x:500,y:120,q:-1.5},{x:370,y:420,q:1.5}]
    };},
    setupField(){const limit={easy:3,normal:4,hard:5}[this.difficulty]||4;this.state={kind:'field',charges:[],target:this.fieldTargets()[this.difficulty],selectedSign:1,limit,accuracy:0,drag:null};const root=this.setControls(`${this.commonDifficulty()}<div class="field-row"><button class="secondary-btn" id="field-plus">+ Positiva</button><button class="secondary-btn" id="field-minus">− Negativa</button></div><button class="primary-btn" id="field-check">Comparar padrão</button><button class="secondary-btn" id="field-undo">Desfazer última</button><button class="secondary-btn" id="field-reset">Reiniciar</button>`);root.querySelector('#mg-difficulty').value=this.difficulty;root.querySelector('#mg-difficulty').onchange=e=>{this.difficulty=e.target.value;this.setupField();};root.querySelector('#field-plus').onclick=()=>{this.state.selectedSign=1;C.ui.toast('Carga positiva selecionada','Toque no laboratório para posicionar.');};root.querySelector('#field-minus').onclick=()=>{this.state.selectedSign=-1;C.ui.toast('Carga negativa selecionada','Toque no laboratório para posicionar.');};root.querySelector('#field-check').onclick=()=>this.checkField();root.querySelector('#field-undo').onclick=()=>this.state.charges.pop();root.querySelector('#field-reset').onclick=()=>this.setupField();this.setHud('Tutorial: copie as setas',`Precisão ${this.state.accuracy}%`,`0/${limit} cargas`,'Clique para posicionar');},
    fieldAt(x,y,charges){let fx=0,fy=0;for(const c of charges){const dx=x-c.x,dy=y-c.y,r2=dx*dx+dy*dy+900,r=Math.sqrt(r2),v=c.q*70000/r2;fx+=v*dx/r;fy+=v*dy/r;}return{x:fx,y:fy,m:Math.hypot(fx,fy)};},
    fieldAccuracy(){let total=0,count=0;for(let y=80;y<500;y+=70)for(let x=80;x<850;x+=70){const a=this.fieldAt(x,y,this.state.target),b=this.fieldAt(x,y,this.state.charges);if(a.m<.02)continue;const direction=b.m>.001?(a.x*b.x+a.y*b.y)/(a.m*b.m):0;const mag=Math.min(a.m,b.m)/Math.max(a.m,b.m,.001);total+=(direction*.75+mag*.25);count++;}return Math.round(U.clamp((total/count+1)/2*100,0,100));},
    checkField(){this.state.accuracy=this.fieldAccuracy();this.setHud(this.state.accuracy>=78?'Padrão aprovado':'Ajuste as cargas',`Precisão ${this.state.accuracy}%`,`${this.state.charges.length}/${this.state.limit} cargas`,this.state.accuracy>=78?'Excelente leitura de campo':'Compare as setas claras e azuis');if(this.state.accuracy>=78){const score=this.state.accuracy*10+(this.state.limit-this.state.charges.length)*80;this.finish(score,[{label:'Precisão',value:`${this.state.accuracy}%`},{label:'Cargas',value:this.state.charges.length}],'Seu campo reproduziu a direção e a intensidade aproximada do padrão-alvo.');}else{C.audio.tone('error');C.ui.toast('Ainda não bateu',`Precisão atual: ${this.state.accuracy}%.`,'warning');}},
    pointerField(p){const hit=[...this.state.charges].reverse().find(c=>Math.hypot(c.x-p.x,c.y-p.y)<24);if(hit){this.state.drag={id:hit.id,ox:p.x-hit.x,oy:p.y-hit.y};return;}if(this.state.charges.length>=this.state.limit){C.ui.toast('Inventário esgotado','Remova ou mova uma carga existente.');return;}this.state.charges.push({id:U.uid('field'),x:p.x,y:p.y,q:this.state.selectedSign*2});C.audio.tone('place');this.setHud('Construindo padrão',`Precisão ${this.state.accuracy}%`,`${this.state.charges.length}/${this.state.limit} cargas`,'Arraste para reposicionar');},
    renderField(ctx){this.background(ctx);ctx.save();ctx.font='700 11px system-ui';ctx.fillStyle='rgba(220,239,250,.7)';ctx.fillText('PADRÃO-ALVO',28,42);for(let y=80;y<500;y+=70)for(let x=80;x<850;x+=70){const target=this.fieldAt(x,y,this.state.target),player=this.fieldAt(x,y,this.state.charges);this.drawMiniArrow(ctx,x,y,target,'rgba(235,245,252,.22)',14);if(player.m>.01)this.drawMiniArrow(ctx,x,y,player,'rgba(74,173,255,.78)',18);}for(const c of this.state.charges)this.drawCharge(ctx,c.x,c.y,c.q,18);ctx.restore();},

    // MAZE
    mazeScene(){const hard=this.difficulty==='hard',easy=this.difficulty==='easy';return{test:{x:90,y:450,q:1},target:{x:820,y:80,r:24},objects:[{type:'obstacle',x:230,y:0,w:65,h:easy?260:330},{type:'obstacle',x:430,y:210,w:70,h:330},{type:'obstacle',x:650,y:0,w:65,h:hard?360:290},{type:'neutral',x:540,y:130,material:'Alumínio',fixed:true,r:32}],friction:false};},
    setupMaze(){const limit={easy:4,normal:3,hard:3}[this.difficulty];this.state={kind:'maze',selectedSign:1,limit,collectibles:[{x:345,y:390,taken:false},{x:555,y:100,taken:false},{x:760,y:405,taken:false}],started:false,drag:null};this.mazeSim=new C.PhysicsSimulation({mode:'minigame',settings:{chargeDynamics:false,dwell:.45,maxTargetSpeed:125}});this.mazeSim.loadScene(this.mazeScene());this.mazeRenderer=new C.PhysicsRenderer(this.stage,this.mazeSim);this.mazeRenderer.setLayers({grid:true,resultant:true,trajectories:true,field:false,labels:false});this.mazeSim.onComplete=()=>{if(this.state.collectibles.every(c=>c.taken)){const score=1200-Math.round(this.mazeSim.elapsed*8)-this.playerChargeCount()*80;this.finish(score,[{label:'Tempo',value:U.formatTime(this.mazeSim.elapsed)},{label:'Partículas',value:'3/3'}],'Você guiou q usando somente o campo produzido pelas cargas.');}else{this.mazeSim.completed=false;this.mazeSim.playing=false;C.ui.toast('Faltam partículas','Colete todos os pontos luminosos antes do alvo.','warning');}};const root=this.setControls(`${this.commonDifficulty()}<div class="field-row"><button class="secondary-btn" id="maze-plus">+ Selecionar</button><button class="secondary-btn" id="maze-minus">− Selecionar</button></div><button class="primary-btn" id="maze-play">Iniciar</button><button class="secondary-btn" id="maze-reset">Reiniciar</button>`);root.querySelector('#mg-difficulty').value=this.difficulty;root.querySelector('#mg-difficulty').onchange=e=>{this.difficulty=e.target.value;this.setupMaze();};root.querySelector('#maze-plus').onclick=()=>this.state.selectedSign=1;root.querySelector('#maze-minus').onclick=()=>this.state.selectedSign=-1;root.querySelector('#maze-play').onclick=()=>{this.mazeSim.playing=!this.mazeSim.playing;root.querySelector('#maze-play').textContent=this.mazeSim.playing?'Pausar':'Iniciar';};root.querySelector('#maze-reset').onclick=()=>this.setupMaze();this.setHud('Tutorial: monte o caminho','0 pontos',`0/${limit} cargas`,'Colete 3 partículas');},
    playerChargeCount(){return this.mazeSim.scene.objects.filter(o=>o.name==='Carga do jogador').length;},
    pointerMaze(p){const hit=this.mazeSim.hitTest(p);if(hit&&hit.name==='Carga do jogador'){this.mazeSim.selectedId=hit.id;this.state.drag={id:hit.id,ox:p.x-hit.x,oy:p.y-hit.y,sim:'maze'};return;}if(this.playerChargeCount()>=this.state.limit){C.ui.toast('Sem cargas restantes');return;}this.mazeSim.addObject(this.state.selectedSign>0?'positive':'negative',p.x,p.y,{q:this.state.selectedSign*1.7,fixed:true,name:'Carga do jogador'});C.audio.tone('place');},
    updateMaze(dt){this.mazeSim.step(dt);const t=this.mazeSim.scene.test;for(const item of this.state.collectibles){if(!item.taken&&Math.hypot(t.x-item.x,t.y-item.y)<24){item.taken=true;this.mazeSim.effect('success',item.x,item.y);C.audio.tone('success');}}this.setHud(this.mazeSim.playing?'Em movimento':'Planejando',`${Math.round((120-this.mazeSim.elapsed)*10)} pontos`,`${this.playerChargeCount()}/${this.state.limit} cargas`,`${this.state.collectibles.filter(c=>c.taken).length}/3 partículas`);},
    renderMaze(ctx,now){this.mazeRenderer.render(now);ctx.save();for(const item of this.state.collectibles)if(!item.taken){ctx.fillStyle='#f7e77a';ctx.shadowColor='#f7e77a';ctx.shadowBlur=16;ctx.beginPath();ctx.arc(item.x,item.y,8,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(item.x-2,item.y-2,2,0,Math.PI*2);ctx.fill();}ctx.restore();},

    // TRIBOELECTRIC
    triboRequests(){return[{target:'Teflon',sign:-1,pair:['Vidro','Teflon']},{target:'Poliestireno',sign:-1,pair:['Lã','Poliestireno']},{target:'Vidro',sign:1,pair:['Vidro','Seda']},{target:'Pele',sign:1,pair:['Pele','Âmbar']},{target:'Seda',sign:-1,pair:['Vidro','Seda']}];},
    setupTribo(){this.state={kind:'tribo',round:0,score:0,combo:0,selected:[],request:null,transfer:0};const materials=['Vidro','Pele','Seda','Madeira','Lã','Âmbar','Poliestireno','Teflon'];const root=this.setControls(`${this.commonDifficulty()}<div class="material-pair">${materials.map(m=>`<button data-material="${m}">${m}</button>`).join('')}</div><button class="primary-btn" id="tribo-rub">Friccionar materiais</button><button class="secondary-btn" id="tribo-reset">Recomeçar</button>`);root.querySelector('#mg-difficulty').value=this.difficulty;root.querySelector('#mg-difficulty').onchange=e=>{this.difficulty=e.target.value;this.setupTribo();};root.querySelectorAll('[data-material]').forEach(btn=>btn.onclick=()=>{const m=btn.dataset.material;if(this.state.selected.includes(m))this.state.selected=this.state.selected.filter(x=>x!==m);else if(this.state.selected.length<2)this.state.selected.push(m);else this.state.selected=[this.state.selected[1],m];root.querySelectorAll('[data-material]').forEach(b=>b.classList.toggle('selected',this.state.selected.includes(b.dataset.material)));});root.querySelector('#tribo-rub').onclick=()=>this.answerTribo();root.querySelector('#tribo-reset').onclick=()=>this.setupTribo();this.nextTribo();},
    nextTribo(){if(this.state.round>=5){this.finish(this.state.score,[{label:'Combo máximo',value:this.state.combo},{label:'Acertos',value:`${Math.round(this.state.score/200)}/5`}],'Você previu a transferência de elétrons usando a série triboelétrica.');return;}this.state.request=this.triboRequests()[this.state.round];this.state.selected=[];document.querySelectorAll('[data-material]').forEach(b=>b.classList.remove('selected'));this.setHud(this.state.round===0?'Rodada tutorial':'Escolha o par',`${this.state.score} pontos`,`Rodada ${this.state.round+1}/5`,`Faça ${this.state.request.target} ficar ${this.state.request.sign>0?'positivo':'negativo'}`);},
    answerTribo(){if(this.state.selected.length!==2){C.ui.toast('Escolha dois materiais');return;}const [a,b]=this.state.selected,ma=C.data.materials.find(m=>m.name===a),mb=C.data.materials.find(m=>m.name===b);const loser=ma.rank<mb.rank?a:b,gainer=ma.rank<mb.rank?b:a;const req=this.state.request;const correct=req.sign>0?loser===req.target:gainer===req.target;if(correct){this.state.combo++;this.state.score+=200+this.state.combo*25;this.state.transfer=1;C.audio.tone('spark');C.ui.toast('Transferência correta',`${loser} perde elétrons; ${gainer} ganha.`,'success');}else{this.state.combo=0;C.audio.tone('error');C.ui.toast('Par incorreto',`${loser} ficaria positivo e ${gainer} negativo.`,'warning');}this.state.round++;const token=this.state;setTimeout(()=>{if(this.state===token&&this.current==='tribo')this.nextTribo();},450);},
    renderTribo(ctx){this.background(ctx);const selected=this.state.selected;ctx.save();ctx.textAlign='center';ctx.fillStyle='rgba(230,244,252,.8)';ctx.font='800 14px system-ui';ctx.fillText(`Objetivo: ${this.state.request?`${this.state.request.target} ${this.state.request.sign>0?'+':'−'}`:'—'}`,450,72);const positions=[300,600];selected.forEach((m,i)=>{const mat=C.data.materials.find(x=>x.name===m);ctx.fillStyle=mat.rank<4?'#d8b88d':'#9db8c7';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(positions[i]-75,205,150,130,24);ctx.fill();ctx.stroke();ctx.fillStyle='#153042';ctx.font='900 18px system-ui';ctx.fillText(m,positions[i],275);ctx.font='700 11px system-ui';ctx.fillText(`posição ${mat.rank+1} na série`,positions[i],302);});if(selected.length===2){for(let i=0;i<8;i++){const t=(performance.now()*.0004+i/8)%1;ctx.fillStyle='#6bb7ff';ctx.beginPath();ctx.arc(U.lerp(positions[0]+75,positions[1]-75,t),260+Math.sin(t*Math.PI*4)*10,4,0,Math.PI*2);ctx.fill();}}ctx.restore();},

    // VECTOR RUSH
    setupVector(){this.state={kind:'vector',round:0,total:10,score:0,streak:0,time:12,charges:[],correct:null,answered:false};const root=this.setControls(`${this.commonDifficulty()}<div class="direction-grid">${dirs.map(d=>d[1]===null?'<span class="blank"></span>':`<button data-dir="${d[0]}">${d[0]}</button>`).join('')}</div><button class="secondary-btn" id="vector-reset">Recomeçar</button>`);root.querySelector('#mg-difficulty').value=this.difficulty;root.querySelector('#mg-difficulty').onchange=e=>{this.difficulty=e.target.value;this.setupVector();};root.querySelectorAll('[data-dir]').forEach(btn=>btn.onclick=()=>this.answerVector(btn.dataset.dir));root.querySelector('#vector-reset').onclick=()=>this.setupVector();this.nextVector();},
    nextVector(){if(this.state.round>=this.state.total){this.finish(this.state.score,[{label:'Sequência final',value:this.state.streak},{label:'Rodadas',value:this.state.total}],'Você estimou a direção da soma vetorial em situações cada vez mais complexas.');return;}const random=U.seededRandom(`${Date.now()}-${this.state.round}`),count=this.difficulty==='easy'?2:this.difficulty==='hard'?4:3;this.state.charges=[];for(let i=0;i<count;i++){const angle=i/count*Math.PI*2+random()*.8,dist=120+random()*110;this.state.charges.push({x:450+Math.cos(angle)*dist,y:270+Math.sin(angle)*dist,q:(random()<.5?-1:1)*(1+random()*2)});}let fx=0,fy=0;for(const ch of this.state.charges){const f=this.tempForce(1,450,270,ch.q,ch.x,ch.y);fx+=f.x;fy+=f.y;}this.state.correct=this.quantizeDirection(fx,fy);this.state.time=this.difficulty==='hard'?6:this.difficulty==='easy'?15:10;this.state.answered=false;this.setHud(this.state.round===0?'Rodada tutorial':'Responda rápido',`${this.state.score} pontos`,`Rodada ${this.state.round+1}/${this.state.total}`,`🔥 ${this.state.streak} · ${this.state.time.toFixed(1)}s`);},
    tempForce(q1,x1,y1,q2,x2,y2){const dx=x1-x2,dy=y1-y2,r2=dx*dx+dy*dy+900,r=Math.sqrt(r2),f=78000*q1*q2/r2;return{x:f*dx/r,y:f*dy/r};},
    quantizeDirection(x,y){const angle=Math.atan2(y,x);let best='→',err=99;for(const [symbol,a] of dirs){if(a===null)continue;const e=Math.abs(Math.atan2(Math.sin(angle-a),Math.cos(angle-a)));if(e<err){err=e;best=symbol;}}return best;},
    answerVector(dir){if(this.state.answered)return;this.state.answered=true;if(dir===this.state.correct){this.state.streak++;this.state.score+=100+this.state.streak*12+Math.round(this.state.time*4);C.audio.tone('success');if(this.state.streak>=10)C.app.unlockAchievement('vector-master');}else{this.state.streak=0;C.audio.tone('error');C.ui.toast('Direção correta',this.state.correct,'warning');}this.state.round++;const token=this.state;setTimeout(()=>{if(this.state===token&&this.current==='vector')this.nextVector();},380);},
    updateVector(dt){if(this.state.answered)return;this.state.time-=dt;if(this.state.time<=0){this.state.answered=true;this.state.streak=0;C.audio.tone('error');C.ui.toast('Tempo esgotado',`A resposta era ${this.state.correct}.`,'warning');this.state.round++;const token=this.state;setTimeout(()=>{if(this.state===token&&this.current==='vector')this.nextVector();},400);}this.setHud('Direção da resultante',`${this.state.score} pontos`,`Rodada ${this.state.round+1}/${this.state.total}`,`🔥 ${this.state.streak} · ${Math.max(0,this.state.time).toFixed(1)}s`);},
    renderVector(ctx){this.background(ctx);ctx.save();ctx.strokeStyle='rgba(255,255,255,.08)';ctx.beginPath();ctx.arc(450,270,120,0,Math.PI*2);ctx.stroke();for(const ch of this.state.charges)this.drawCharge(ctx,ch.x,ch.y,ch.q,20);ctx.fillStyle='#24d8bd';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(450,270,16,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#073f37';ctx.font='900 12px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('q+',450,271);ctx.fillStyle='rgba(223,239,249,.7)';ctx.font='800 13px system-ui';ctx.fillText('Qual é a direção da força resultante?',450,475);ctx.restore();},

    // COULOMB TARGET
    coulombScene(){return{test:{x:100,y:430,q:1},target:{x:790,y:100,r:22},objects:[{type:'obstacle',x:370,y:190,w:90,h:350},{type:'obstacle',x:610,y:0,w:70,h:250}],friction:false};},
    setupCoulomb(){this.state={kind:'coulomb',selectedSign:1,limit:this.difficulty==='easy'?4:3,attempts:this.difficulty==='hard'?3:5,preview:true,drag:null,bonus:{x:525,y:110,taken:false}};this.coulombSim=new C.PhysicsSimulation({mode:'minigame',settings:{chargeDynamics:false,dwell:.35,maxTargetSpeed:150}});this.coulombSim.loadScene(this.coulombScene());this.coulombRenderer=new C.PhysicsRenderer(this.stage,this.coulombSim);this.coulombRenderer.setLayers({grid:true,resultant:true,trajectories:true,field:false,labels:false});this.coulombSim.onComplete=()=>{const score=1100-this.coulombSim.elapsed*10+this.state.attempts*90+(this.state.bonus.taken?250:0);this.finish(score,[{label:'Tentativas restantes',value:this.state.attempts},{label:'Bônus',value:this.state.bonus.taken?'Coletado':'Não coletado'}],'A configuração das cargas lançou q pela trajetória planejada.');};const root=this.setControls(`${this.commonDifficulty()}<div class="field-row"><button class="secondary-btn" id="coulomb-plus">+ Selecionar</button><button class="secondary-btn" id="coulomb-minus">− Selecionar</button></div><button class="primary-btn" id="coulomb-launch">Lançar q</button><button class="secondary-btn" id="coulomb-resetq">Nova tentativa</button><label class="toggle"><input id="coulomb-preview" type="checkbox" checked><span></span>Prévia de trajetória</label>`);root.querySelector('#mg-difficulty').value=this.difficulty;root.querySelector('#mg-difficulty').onchange=e=>{this.difficulty=e.target.value;this.setupCoulomb();};root.querySelector('#coulomb-plus').onclick=()=>this.state.selectedSign=1;root.querySelector('#coulomb-minus').onclick=()=>this.state.selectedSign=-1;root.querySelector('#coulomb-launch').onclick=()=>{this.coulombSim.playing=true;};root.querySelector('#coulomb-resetq').onclick=()=>this.resetCoulombAttempt();root.querySelector('#coulomb-preview').onchange=e=>this.state.preview=e.target.checked;this.setHud('Posicione e lance','0 pontos',`${this.state.attempts} tentativas`,`${this.playerCoulombCharges()}/${this.state.limit} cargas`);},
    playerCoulombCharges(){return this.coulombSim.scene.objects.filter(o=>o.name==='Carga do jogador').length;},
    pointerCoulomb(p){const hit=this.coulombSim.hitTest(p);if(hit&&hit.name==='Carga do jogador'){this.coulombSim.selectedId=hit.id;this.state.drag={id:hit.id,ox:p.x-hit.x,oy:p.y-hit.y,sim:'coulomb'};return;}if(this.playerCoulombCharges()>=this.state.limit){C.ui.toast('Limite de cargas atingido');return;}this.coulombSim.addObject(this.state.selectedSign>0?'positive':'negative',p.x,p.y,{q:this.state.selectedSign*2,fixed:true,name:'Carga do jogador'});C.audio.tone('place');},
    resetCoulombAttempt(){if(this.state.attempts<=0){C.ui.result({kicker:'Sem tentativas',title:'Tente outra configuração',description:'Reinicie o minigame e use a prévia para planejar o lançamento.',icon:'↻',details:[],primary:'Recomeçar',secondary:'Sair',onPrimary:()=>this.setupCoulomb(),onSecondary:()=>this.close()});return;}this.state.attempts--;const t=this.coulombSim.scene.test;t.x=100;t.y=430;t.vx=t.vy=0;t.trail=[];this.coulombSim.elapsed=0;this.coulombSim.targetDwell=0;this.coulombSim.completed=false;this.coulombSim.playing=false;this.state.bonus.taken=false;},
    updateCoulomb(dt){this.coulombSim.step(dt);const t=this.coulombSim.scene.test;if(!this.state.bonus.taken&&Math.hypot(t.x-this.state.bonus.x,t.y-this.state.bonus.y)<22){this.state.bonus.taken=true;C.audio.tone('success');}if(this.coulombSim.playing&&(t.x<=14||t.y>=526)&&this.coulombSim.elapsed>1)this.coulombSim.playing=false;this.setHud(this.coulombSim.playing?'Lançamento em curso':'Ajuste as cargas',`${Math.max(0,Math.round(1000-this.coulombSim.elapsed*10))} pontos`,`${this.state.attempts} tentativas`,`${this.playerCoulombCharges()}/${this.state.limit} cargas`);},
    renderCoulomb(ctx,now){this.coulombRenderer.render(now);ctx.save();if(!this.state.bonus.taken){ctx.fillStyle='#f4dd63';ctx.shadowColor='#f4dd63';ctx.shadowBlur=18;ctx.beginPath();ctx.arc(this.state.bonus.x,this.state.bonus.y,9,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#3b2b06';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('+',this.state.bonus.x,this.state.bonus.y);}if(this.state.preview&&!this.coulombSim.playing)this.drawTrajectoryPreview(ctx);ctx.restore();},
    drawTrajectoryPreview(ctx){const snapshot=this.coulombSim.serialize(),preview=new C.PhysicsSimulation({settings:{chargeDynamics:false,dwell:99,maxTargetSpeed:999}});preview.loadScene(snapshot);preview.playing=true;ctx.save();ctx.setLineDash([5,5]);ctx.strokeStyle='rgba(255,255,255,.28)';ctx.beginPath();ctx.moveTo(preview.scene.test.x,preview.scene.test.y);for(let i=0;i<240;i++){preview.step(1/120);if(i%5===0)ctx.lineTo(preview.scene.test.x,preview.scene.test.y);}ctx.stroke();ctx.restore();},

    pointerDown(p){if(!this.state)return;if(this.state.kind==='field')this.pointerField(p);else if(this.state.kind==='maze')this.pointerMaze(p);else if(this.state.kind==='coulomb')this.pointerCoulomb(p);},
    pointerMove(p){const drag=this.state?.drag;if(!drag)return;if(this.state.kind==='field'){const o=this.state.charges.find(c=>c.id===drag.id);if(o){o.x=U.clamp(p.x-drag.ox,20,880);o.y=U.clamp(p.y-drag.oy,20,520);}}else{const sim=drag.sim==='maze'?this.mazeSim:this.coulombSim,o=sim.scene.objects.find(x=>x.id===drag.id);if(o)sim.setPosition(o,p.x-drag.ox,p.y-drag.oy);}},
    pointerUp(){if(this.state)this.state.drag=null;},
    update(dt){if(!this.current||!this.state)return;if(this.state.kind==='maze')this.updateMaze(dt);else if(this.state.kind==='vector')this.updateVector(dt);else if(this.state.kind==='coulomb')this.updateCoulomb(dt);},
    render(now){if(!this.current||!this.state)return;this.stage.begin();const ctx=this.ctx;if(this.state.kind==='field')this.renderField(ctx);else if(this.state.kind==='maze')this.renderMaze(ctx,now);else if(this.state.kind==='tribo')this.renderTribo(ctx);else if(this.state.kind==='vector')this.renderVector(ctx);else if(this.state.kind==='coulomb')this.renderCoulomb(ctx,now);},
    background(ctx){ctx.save();const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,'#0a1a2b');g.addColorStop(1,'#06111c');ctx.fillStyle=g;ctx.fillRect(0,0,900,540);ctx.strokeStyle='rgba(142,190,220,.07)';for(let x=20;x<900;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,540);ctx.stroke();}for(let y=20;y<540;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(900,y);ctx.stroke();}ctx.restore();},
    drawCharge(ctx,x,y,q,r=18){ctx.save();ctx.fillStyle=q>0?'#ff5c63':'#4a8dff';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.shadowColor=q>0?'rgba(255,92,99,.45)':'rgba(74,141,255,.45)';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font='900 18px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(q>0?'+':'−',x,y+1);ctx.restore();},
    drawMiniArrow(ctx,x,y,field,color,max){if(field.m<.001)return;const len=U.clamp(Math.log1p(field.m)*3,4,max),nx=field.x/field.m,ny=field.y/field.m,x2=x+nx*len,y2=y+ny*len,a=Math.atan2(ny,nx);ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=1.3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-Math.cos(a-.5)*4,y2-Math.sin(a-.5)*4);ctx.lineTo(x2-Math.cos(a+.5)*4,y2-Math.sin(a+.5)*4);ctx.fill();ctx.restore();},
    onKey(event){if(C.app?.activeView!=='minigames'||!this.current||document.querySelector('dialog[open]'))return false;if(event.key==='Escape'){this.close();return true;}if(event.key===' '&&(this.state.kind==='maze'||this.state.kind==='coulomb')){event.preventDefault();const sim=this.state.kind==='maze'?this.mazeSim:this.coulombSim;sim.playing=!sim.playing;return true;}return false;}
  };
})();
