(function(){
  'use strict';
  const C=window.Cargas,U=C.util,K=C.CONSTANTS;

  function finite(value,fallback=0){return Number.isFinite(value)?value:fallback;}
  function materialByName(name){return C.data.materials.find(m=>m.name===name)||C.data.materials[0];}

  C.PhysicsSimulation=class{
    constructor(options={}){
      this.width=K.WIDTH;this.height=K.HEIGHT;this.mode=options.mode||'lab';this.playing=false;this.speed=1;this.elapsed=0;this.targetDwell=0;
      this.scene={objects:[],test:null,target:null};this.selectedId=null;this.effects=[];this.contactTimes=new Map();this.transferPulseTimes=new Map();this.trajectories=[];this.lastMetrics={force:{x:0,y:0,magnitude:0},field:{x:0,y:0,magnitude:0}};
      this.settings={friction:true,induction:true,dipoleInteractions:true,chargeDynamics:true,dwell:.7,maxTargetSpeed:90,...options.settings};
      this.onComplete=null;this.onTransfer=null;this.onCollision=null;this.completed=false;this.dirty=true;
    }
    loadScene(raw){
      const source=U.deepClone(raw||{});this.elapsed=0;this.targetDwell=0;this.completed=false;this.effects=[];this.contactTimes.clear();this.transferPulseTimes.clear();this.trajectories=[];
      this.scene={
        test:this.normalizeTest(source.test||{x:120,y:270,q:1}),
        target:{x:finite(source.target?.x,780),y:finite(source.target?.y,270),r:finite(source.target?.r,K.TARGET_RADIUS)},
        objects:(source.objects||[]).map(obj=>this.normalizeObject(obj)),
        friction:source.friction!==false,
        title:source.title||''
      };
      this.settings.friction=source.friction!==false;
      this.selectedId=this.scene.test.id;this.dirty=true;return this;
    }
    normalizeTest(test){return{id:test.id||U.uid('test'),type:'test',name:test.name||'Carga-teste',x:U.clamp(finite(test.x,140),K.TEST_RADIUS,this.width-K.TEST_RADIUS),y:U.clamp(finite(test.y,270),K.TEST_RADIUS,this.height-K.TEST_RADIUS),vx:finite(test.vx),vy:finite(test.vy),q:Math.abs(finite(test.q,1))<.01?1:finite(test.q,1),mass:U.clamp(finite(test.mass,1.2),.2,10),r:K.TEST_RADIUS,fixed:false,trail:[]};}
    normalizeObject(obj){
      const type=['charge','neutral','conductor','insulator','obstacle'].includes(obj.type)?obj.type:'charge';
      if(type==='obstacle')return{id:obj.id||U.uid('wall'),type,name:obj.name||'Obstáculo',x:finite(obj.x,400),y:finite(obj.y,200),w:Math.max(12,finite(obj.w,80)),h:Math.max(12,finite(obj.h,120)),solid:obj.solid!==false,conductive:!!obj.conductive,hollow:!!obj.hollow,fixed:true,moving:obj.moving?{...obj.moving,originX:finite(obj.x,400),originY:finite(obj.y,200),phase:obj.moving.phase||0}:null};
      const material=materialByName(obj.material);
      const radius=U.clamp(finite(obj.r,type==='charge'?K.CHARGE_RADIUS:25),12,70);
      return{id:obj.id||U.uid(type),type,name:obj.name||(type==='charge'?(obj.q>=0?'Carga positiva':'Carga negativa'):obj.material||'Material neutro'),x:U.clamp(finite(obj.x,450),radius,this.width-radius),y:U.clamp(finite(obj.y,270),radius,this.height-radius),vx:finite(obj.vx),vy:finite(obj.vy),q:type==='charge'?U.clamp(finite(obj.q,obj.intensity||1),-4,4):0,intensity:U.clamp(Math.abs(finite(obj.intensity,obj.q||1)),.1,4),mass:U.clamp(finite(obj.mass,type==='charge'?2:3.4),.2,10),r:radius,fixed:obj.fixed!==false,material:obj.material||material.name,polarizability:U.clamp(finite(obj.polarizability,material.polarizability),0,1),staticCharge:U.clamp(finite(obj.staticCharge),-4,4),inducedCharge:0,dipX:1,dipY:0,contactGlow:0,trail:[]};
    }
    serialize(){return{test:U.deepClone(this.scene.test),target:U.deepClone(this.scene.target),objects:U.deepClone(this.scene.objects),friction:this.settings.friction};}
    restore(snapshot){this.loadScene(snapshot);}
    allSelectable(){return[this.scene.test,...this.scene.objects.filter(o=>o.type!=='obstacle')];}
    get selected(){return this.allSelectable().find(o=>o.id===this.selectedId)||null;}
    addObject(type,x=450,y=270,extra={}){
      if(type==='test'){this.scene.test=this.normalizeTest({x,y,...extra});this.selectedId=this.scene.test.id;}
      else{let data;if(type==='positive')data={type:'charge',x,y,q:Math.abs(extra.q||1),fixed:extra.fixed??false,...extra};else if(type==='negative')data={type:'charge',x,y,q:-Math.abs(extra.q||1),fixed:extra.fixed??false,...extra};else if(type==='neutral')data={type:'neutral',x,y,material:extra.material||'Vidro',fixed:extra.fixed??false,...extra};else if(type==='conductor')data={type:'conductor',x,y,material:extra.material||'Alumínio',r:30,fixed:extra.fixed??false,...extra};else if(type==='insulator')data={type:'insulator',x,y,material:extra.material||'Teflon',r:27,fixed:extra.fixed??false,...extra};else return null;const obj=this.normalizeObject(data);this.scene.objects.push(obj);this.selectedId=obj.id;}
      this.effect('place',x,y,{kind:type});this.dirty=true;return this.selected;
    }
    removeSelected(){if(this.selectedId===this.scene.test.id)return false;const index=this.scene.objects.findIndex(o=>o.id===this.selectedId);if(index<0)return false;const [removed]=this.scene.objects.splice(index,1);this.effect('impact',removed.x,removed.y);this.selectedId=this.scene.test.id;this.dirty=true;return true;}
    duplicateSelected(){const object=this.selected;if(!object||object.type==='test'||object.type==='obstacle')return null;const copy=U.deepClone(object);copy.id=U.uid(copy.type);copy.name=`${copy.name} cópia`;copy.x=U.clamp(copy.x+34,copy.r,this.width-copy.r);copy.y=U.clamp(copy.y+24,copy.r,this.height-copy.r);copy.vx=copy.vy=0;copy.trail=[];this.scene.objects.push(copy);this.selectedId=copy.id;this.effect('place',copy.x,copy.y);this.dirty=true;return copy;}
    hitTest(point,includeObstacles=false){const list=[...this.scene.objects].reverse();for(const o of list){if(o.type==='obstacle'){if(includeObstacles&&point.x>=o.x&&point.x<=o.x+o.w&&point.y>=o.y&&point.y<=o.y+o.h)return o;}else if(Math.hypot(point.x-o.x,point.y-o.y)<=o.r+5)return o;}if(Math.hypot(point.x-this.scene.test.x,point.y-this.scene.test.y)<=this.scene.test.r+6)return this.scene.test;return null;}
    setPosition(object,x,y){if(!object)return;const r=object.r||0;object.x=U.clamp(finite(x,object.x),r,this.width-r);object.y=U.clamp(finite(y,object.y),r,this.height-r);object.vx=object.vy=0;this.resolveObjectAgainstObstacles(object);this.dirty=true;}
    sources(includeTest=false){const out=[];for(const o of this.scene.objects){if(o.type==='charge')out.push({id:o.id,x:o.x,y:o.y,q:o.q});else if(Math.abs(o.staticCharge||0)>.001)out.push({id:o.id,x:o.x,y:o.y,q:o.staticCharge});if(this.settings.induction&&Math.abs(o.inducedCharge||0)>.001){const sep=Math.min(20,o.r*.7),dx=o.dipX*sep,dy=o.dipY*sep;out.push({id:`${o.id}-p`,x:o.x+dx,y:o.y+dy,q:o.inducedCharge});out.push({id:`${o.id}-n`,x:o.x-dx,y:o.y-dy,q:-o.inducedCharge});}}
      if(includeTest)out.push({id:this.scene.test.id,x:this.scene.test.x,y:this.scene.test.y,q:this.scene.test.q});return out;
    }
    forcePair(q1,x1,y1,q2,x2,y2){const dx=x1-x2,dy=y1-y2;const r2=dx*dx+dy*dy+K.SOFTENING*K.SOFTENING;const r=Math.sqrt(r2);let magnitude=K.COULOMB_K*q1*q2/r2;magnitude=U.clamp(magnitude,-K.MAX_FORCE,K.MAX_FORCE);return{x:magnitude*dx/r,y:magnitude*dy/r,magnitude:Math.abs(magnitude),distance:Math.sqrt(Math.max(0,r2-K.SOFTENING*K.SOFTENING))};}
    fieldAt(x,y,sources=this.sources()){let fx=0,fy=0;for(const s of sources){const f=this.forcePair(1,x,y,s.q,s.x,s.y);fx+=f.x;fy+=f.y;}return{x:fx,y:fy,magnitude:Math.hypot(fx,fy)};}
    forceOn(object,includeInduced=true){let x=0,y=0;const parts=[];for(const source of this.sources(false)){if(source.id===object.id||String(source.id).startsWith(`${object.id}-`))continue;if(!includeInduced&&String(source.id).includes('-p'))continue;const f=this.forcePair(object.q||object.staticCharge||0,object.x,object.y,source.q,source.x,source.y);x+=f.x;y+=f.y;parts.push({...f,source});}return{x,y,magnitude:Math.hypot(x,y),parts};}
    potentialAt(x,y){let value=0;for(const s of this.sources()){const d=Math.sqrt((x-s.x)**2+(y-s.y)**2+K.SOFTENING**2);value+=s.q/d;}return value*120;}
    updateInduction(){const real=this.sources(false).filter(s=>!String(s.id).includes('-p')&&!String(s.id).includes('-n'));for(const o of this.scene.objects){if(!['neutral','conductor','insulator'].includes(o.type))continue;const field=this.fieldAt(o.x,o.y,real.filter(s=>s.id!==o.id));const strength=field.magnitude;const response=o.type==='conductor'?1.25:(o.type==='insulator' ? .72 : 1);o.inducedCharge=U.clamp(o.polarizability*strength*.008*response,0,2.7);if(strength>.0001){o.dipX=field.x/strength;o.dipY=field.y/strength;}else{o.dipX=1;o.dipY=0;}o.contactGlow=Math.max(0,(o.contactGlow||0)-.03);}}
    updateFriction(dt){if(!this.settings.friction)return;const mats=this.scene.objects.filter(o=>['neutral','conductor','insulator'].includes(o.type));const activeKeys=new Set();for(let i=0;i<mats.length;i++)for(let j=i+1;j<mats.length;j++){const a=mats[i],b=mats[j];const key=a.id<b.id?`${a.id}|${b.id}`:`${b.id}|${a.id}`;if(U.distance(a,b)<=a.r+b.r+3){activeKeys.add(key);const time=(this.contactTimes.get(key)||0)+dt;this.contactTimes.set(key,time);const ma=materialByName(a.material),mb=materialByName(b.material);const diff=mb.rank-ma.rank;if(diff!==0&&time>.18){const rate=Math.min(.52,Math.abs(diff)*.055);const capacity=Math.max(0,4-Math.max(Math.abs(a.staticCharge),Math.abs(b.staticCharge)));const transfer=Math.min(rate*dt,capacity);if(transfer>0){const loser=diff>0?a:b,gainer=diff>0?b:a;loser.staticCharge=U.clamp(loser.staticCharge+transfer,-4,4);gainer.staticCharge=U.clamp(gainer.staticCharge-transfer,-4,4);loser.contactGlow=gainer.contactGlow=1;const lastPulse=this.transferPulseTimes.get(key)??-Infinity;if(time-lastPulse>=.16){this.transferPulseTimes.set(key,time);this.effect('spark',(a.x+b.x)/2,(a.y+b.y)/2,{from:loser.id,to:gainer.id});this.onTransfer?.({loser,gainer,amount:Math.min(rate*.16,capacity)});}}}}else{this.contactTimes.delete(key);this.transferPulseTimes.delete(key);}}
      for(const key of [...this.contactTimes.keys()])if(!activeKeys.has(key)){this.contactTimes.delete(key);this.transferPulseTimes.delete(key);}
    }
    integrateBody(body,force,dt){if(body.fixed)return;const mass=Math.max(.2,body.mass||1);body.vx=finite(body.vx+force.x/mass*dt,0);body.vy=finite(body.vy+force.y/mass*dt,0);const drag=Math.pow(.985,dt*60);body.vx*=drag;body.vy*=drag;const speed=Math.hypot(body.vx,body.vy);if(speed>K.MAX_SPEED){body.vx=body.vx/speed*K.MAX_SPEED;body.vy=body.vy/speed*K.MAX_SPEED;}body.x=finite(body.x+body.vx*dt,this.width/2);body.y=finite(body.y+body.vy*dt,this.height/2);this.resolveBounds(body);this.resolveObjectAgainstObstacles(body);}
    resolveBounds(body){const r=body.r||10;if(body.x<r){body.x=r;body.vx=Math.abs(body.vx)*.42;this.collisionEffect(body);}if(body.x>this.width-r){body.x=this.width-r;body.vx=-Math.abs(body.vx)*.42;this.collisionEffect(body);}if(body.y<r){body.y=r;body.vy=Math.abs(body.vy)*.42;this.collisionEffect(body);}if(body.y>this.height-r){body.y=this.height-r;body.vy=-Math.abs(body.vy)*.42;this.collisionEffect(body);}}
    resolveObjectAgainstObstacles(body){if(!body||body.type==='obstacle')return;const r=body.r||10;for(const wall of this.scene.objects.filter(o=>o.type==='obstacle'&&o.solid)){const nearestX=U.clamp(body.x,wall.x,wall.x+wall.w),nearestY=U.clamp(body.y,wall.y,wall.y+wall.h);let dx=body.x-nearestX,dy=body.y-nearestY;let d=Math.hypot(dx,dy);if(d<r){if(d<.001){const left=Math.abs(body.x-wall.x),right=Math.abs(body.x-(wall.x+wall.w)),top=Math.abs(body.y-wall.y),bottom=Math.abs(body.y-(wall.y+wall.h));const m=Math.min(left,right,top,bottom);if(m===left){dx=-1;dy=0;}else if(m===right){dx=1;dy=0;}else if(m===top){dx=0;dy=-1;}else{dx=0;dy=1;}d=1;}const nx=dx/d,ny=dy/d;body.x=nearestX+nx*(r+.2);body.y=nearestY+ny*(r+.2);const vn=body.vx*nx+body.vy*ny;if(vn<0){body.vx-=1.55*vn*nx;body.vy-=1.55*vn*ny;}this.collisionEffect(body);}}
    }
    resolveCirclePairs(){const bodies=[this.scene.test,...this.scene.objects.filter(o=>o.type!=='obstacle'&&!o.fixed)];for(let i=0;i<bodies.length;i++)for(let j=i+1;j<bodies.length;j++){const a=bodies[i],b=bodies[j],dx=b.x-a.x,dy=b.y-a.y,min=(a.r||10)+(b.r||10),d=Math.hypot(dx,dy);if(d>0&&d<min){const nx=dx/d,ny=dy/d,overlap=min-d;const wa=a.fixed?0:.5,wb=b.fixed?0:.5;if(!a.fixed){a.x-=nx*overlap*(b.fixed?1:wa);a.y-=ny*overlap*(b.fixed?1:wa);}if(!b.fixed){b.x+=nx*overlap*(a.fixed?1:wb);b.y+=ny*overlap*(a.fixed?1:wb);}const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel<0){const impulse=-rel*.55;if(!a.fixed){a.vx-=impulse*nx;a.vy-=impulse*ny;}if(!b.fixed){b.vx+=impulse*nx;b.vy+=impulse*ny;}}}}}
    updateMovingObstacles(dt){for(const o of this.scene.objects){if(o.type!=='obstacle'||!o.moving)continue;o.moving.phase+=dt*o.moving.speed/(o.moving.range||100);const offset=Math.sin(o.moving.phase)*(o.moving.range||100)/2;if(o.moving.axis==='x')o.x=o.moving.originX+offset;else o.y=o.moving.originY+offset;}}
    step(dt){if(!this.playing||this.completed)return;dt=U.clamp(dt*this.speed,0,.025);this.elapsed+=dt;this.updateMovingObstacles(dt);this.updateInduction();this.updateFriction(dt);
      const force=this.forceOn(this.scene.test);this.lastMetrics.force=force;this.lastMetrics.field={x:force.x/(this.scene.test.q||1),y:force.y/(this.scene.test.q||1),magnitude:force.magnitude/Math.max(.01,Math.abs(this.scene.test.q||1))};this.integrateBody(this.scene.test,force,dt);
      if(this.settings.chargeDynamics){for(const o of this.scene.objects){if(o.type==='charge'&&!o.fixed){this.integrateBody(o,this.forceOn(o),dt);}else if(['neutral','conductor','insulator'].includes(o.type)&&!o.fixed&&Math.abs(o.staticCharge)>.01){this.integrateBody(o,this.forceOn({ ...o,q:o.staticCharge}),dt);}}}
      this.resolveCirclePairs();this.recordTrail(this.scene.test);for(const o of this.scene.objects)if(o.trail&&!o.fixed)this.recordTrail(o);this.updateEffects(dt);this.checkTarget(dt);this.dirty=true;
    }
    stepOnce(dt=1/60){const was=this.playing;this.playing=true;this.step(dt);this.playing=was;}
    recordTrail(body){if(C.storage.data.settings.reducedMotion)return;body.trail=body.trail||[];const last=body.trail[body.trail.length-1];if(!last||Math.hypot(last.x-body.x,last.y-body.y)>4){body.trail.push({x:body.x,y:body.y});if(body.trail.length>90)body.trail.shift();}}
    checkTarget(dt){const t=this.scene.test,target=this.scene.target;const inside=U.distance(t,target)<=target.r;const speed=Math.hypot(t.vx,t.vy);const maxSpeed=this.settings.maxTargetSpeed||90;if(inside&&speed<=maxSpeed){this.targetDwell+=dt;this.effect('target',target.x,target.y,{quiet:true});}else this.targetDwell=Math.max(0,this.targetDwell-dt*1.8);if(this.targetDwell>=(this.settings.dwell||.7)&&!this.completed){this.completed=true;this.playing=false;this.effect('success',target.x,target.y);C.audio.tone('success');this.onComplete?.({elapsed:this.elapsed,speed,dwell:this.targetDwell});}}
    collisionEffect(body){if((body._collisionCooldown||0)>this.elapsed)return;body._collisionCooldown=this.elapsed+.12;this.effect('impact',body.x,body.y,{quiet:true});this.onCollision?.(body);}
    effect(type,x,y,extra={}){if(extra.quiet&&C.storage.data.settings.reducedMotion)return;if(this.effects.length>70)this.effects.splice(0,this.effects.length-70);this.effects.push({type,x,y,life:1,maxLife:type==='spark'?.45:type==='success'?1.2:.55,...extra});}
    updateEffects(dt){for(const e of this.effects)e.life-=dt/e.maxLife;this.effects=this.effects.filter(e=>e.life>0);}
    metricsForSelected(){const object=this.selected;return{staticCharge:object?.staticCharge||0,inducedCharge:object?.inducedCharge||0,material:object?.material||'—'};}
  };

  C.PhysicsRenderer=class{
    constructor(stage,simulation){this.stage=stage;this.sim=simulation;this.layers={...C.storage.data.settings.layers};this.heatmap=document.createElement('canvas');this.heatmap.width=90;this.heatmap.height=54;this.heatCtx=this.heatmap.getContext('2d');this.lastHeatmap=0;this.lastSourceHash='';}
    setLayers(layers){Object.assign(this.layers,layers);}
    sourceHash(){return this.sim.sources().map(s=>`${Math.round(s.x/4)},${Math.round(s.y/4)},${Math.round(s.q*20)}`).join('|');}
    render(now=performance.now()){
      const ctx=this.stage.ctx;this.stage.begin();ctx.save();ctx.clearRect(0,0,K.WIDTH,K.HEIGHT);this.drawBackground(ctx);
      if(this.layers.heatmap)this.drawHeatmap(ctx,now);if(this.layers.grid)this.drawGrid(ctx);if(this.layers.field)this.drawFieldGrid(ctx);if(this.layers.lines)this.drawFieldLines(ctx);if(this.layers.trajectories)this.drawTrails(ctx);
      this.drawTarget(ctx,now);for(const o of this.sim.scene.objects.filter(o=>o.type==='obstacle'))this.drawObstacle(ctx,o,now);for(const o of this.sim.scene.objects.filter(o=>o.type!=='obstacle'))this.drawObject(ctx,o,now);this.drawTest(ctx,this.sim.scene.test,now);if(this.layers.individual)this.drawIndividualForces(ctx);if(this.layers.resultant)this.drawResultant(ctx);if(this.layers.components)this.drawComponents(ctx);if(this.layers.velocity)this.drawVelocity(ctx);if(this.layers.distance)this.drawDistances(ctx);this.drawEffects(ctx);this.drawSelection(ctx);ctx.restore();
    }
    drawBackground(ctx){const g=ctx.createLinearGradient(0,0,0,K.HEIGHT);g.addColorStop(0,'#0a1a2b');g.addColorStop(.55,'#071522');g.addColorStop(1,'#06111c');ctx.fillStyle=g;ctx.fillRect(0,0,K.WIDTH,K.HEIGHT);const glow=ctx.createRadialGradient(K.WIDTH*.55,K.HEIGHT*.42,20,K.WIDTH*.55,K.HEIGHT*.42,430);glow.addColorStop(0,'rgba(27,86,122,.13)');glow.addColorStop(1,'rgba(2,10,18,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,K.WIDTH,K.HEIGHT);}
    drawGrid(ctx){ctx.save();ctx.strokeStyle='rgba(142,190,220,.075)';ctx.lineWidth=1;for(let x=20;x<K.WIDTH;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,K.HEIGHT);ctx.stroke();}for(let y=20;y<K.HEIGHT;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(K.WIDTH,y);ctx.stroke();}ctx.strokeStyle='rgba(142,190,220,.12)';for(let x=100;x<K.WIDTH;x+=200){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,K.HEIGHT);ctx.stroke();}for(let y=70;y<K.HEIGHT;y+=200){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(K.WIDTH,y);ctx.stroke();}ctx.restore();}
    updateHeatmap(){const image=this.heatCtx.createImageData(this.heatmap.width,this.heatmap.height);for(let y=0;y<this.heatmap.height;y++)for(let x=0;x<this.heatmap.width;x++){const p=this.sim.potentialAt((x+.5)/this.heatmap.width*K.WIDTH,(y+.5)/this.heatmap.height*K.HEIGHT);const t=Math.tanh(Math.abs(p)/2.4);const i=(y*this.heatmap.width+x)*4;if(p>=0){image.data[i]=235;image.data[i+1]=62;image.data[i+2]=76;}else{image.data[i]=43;image.data[i+1]=114;image.data[i+2]=236;}image.data[i+3]=Math.round(t*90);}this.heatCtx.putImageData(image,0,0);}
    drawHeatmap(ctx,now){const hash=this.sourceHash();if(now-this.lastHeatmap>250||hash!==this.lastSourceHash){this.updateHeatmap();this.lastHeatmap=now;this.lastSourceHash=hash;}ctx.save();ctx.imageSmoothingEnabled=true;ctx.drawImage(this.heatmap,0,0,K.WIDTH,K.HEIGHT);ctx.restore();}
    drawFieldGrid(ctx){ctx.save();for(let y=60;y<K.HEIGHT;y+=62)for(let x=60;x<K.WIDTH;x+=62){const f=this.sim.fieldAt(x,y);const mag=Math.hypot(f.x,f.y);if(mag<.01)continue;const len=U.clamp(Math.log1p(mag)*2.6,4,17);this.arrow(ctx,x,y,x+f.x/mag*len,y+f.y/mag*len,'rgba(119,213,255,.5)',1.1,4);}ctx.restore();}
    drawFieldLines(ctx){const positives=this.sim.sources().filter(s=>s.q>0).slice(0,8);ctx.save();ctx.lineWidth=1.15;ctx.strokeStyle='rgba(116,194,238,.3)';for(const source of positives){for(let n=0;n<10;n++){let x=source.x+Math.cos(n/10*Math.PI*2)*20,y=source.y+Math.sin(n/10*Math.PI*2)*20;ctx.beginPath();ctx.moveTo(x,y);for(let step=0;step<72;step++){const f=this.sim.fieldAt(x,y),m=Math.hypot(f.x,f.y);if(m<.001)break;x+=f.x/m*6;y+=f.y/m*6;if(x<0||x>K.WIDTH||y<0||y>K.HEIGHT)break;ctx.lineTo(x,y);const nearNegative=this.sim.sources().some(s=>s.q<0&&Math.hypot(x-s.x,y-s.y)<18);if(nearNegative)break;}ctx.stroke();}}ctx.restore();}
    drawTrails(ctx){ctx.save();ctx.lineCap='round';for(const body of [this.sim.scene.test,...this.sim.scene.objects]){if(!body.trail||body.trail.length<2)continue;ctx.beginPath();body.trail.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle=body.type==='test'?'rgba(36,216,189,.34)':'rgba(196,219,234,.16)';ctx.lineWidth=body.type==='test'?3:1.5;ctx.stroke();}ctx.restore();}
    drawTarget(ctx,now){const t=this.sim.scene.target,pulse=C.storage.data.settings.reducedMotion?0:Math.sin(now*.004)*3;ctx.save();ctx.translate(t.x,t.y);ctx.strokeStyle='rgba(255,191,74,.28)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,t.r+10+pulse,0,Math.PI*2);ctx.stroke();const g=ctx.createRadialGradient(0,0,2,0,0,t.r+12);g.addColorStop(0,'rgba(255,225,132,.95)');g.addColorStop(.38,'rgba(255,191,74,.5)');g.addColorStop(1,'rgba(255,191,74,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,t.r+12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ffbf4a';ctx.beginPath();ctx.arc(0,0,t.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#35220a';ctx.font='900 18px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('★',0,1);ctx.restore();}
    drawObstacle(ctx,o,now){ctx.save();const g=ctx.createLinearGradient(o.x,o.y,o.x+o.w,o.y+o.h);g.addColorStop(0,o.conductive?'#607f94':'#263d52');g.addColorStop(1,o.conductive?'#2e536b':'#142a3d');ctx.fillStyle=g;ctx.strokeStyle=o.conductive?'rgba(174,220,244,.55)':'rgba(151,187,211,.25)';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(o.x,o.y,o.w,o.h,Math.min(14,o.w/4,o.h/4));ctx.fill();ctx.stroke();if(o.conductive){ctx.strokeStyle='rgba(222,243,255,.13)';for(let y=o.y+10;y<o.y+o.h;y+=12){ctx.beginPath();ctx.moveTo(o.x+8,y);ctx.lineTo(o.x+o.w-8,y);ctx.stroke();}}ctx.restore();}
    chargeColors(q){return q>=0?{fill:'#ff5c63',dark:'#661e2a',glow:'rgba(255,92,99,.4)',symbol:'+'}:{fill:'#4a8dff',dark:'#173c79',glow:'rgba(74,141,255,.4)',symbol:'−'};}
    drawObject(ctx,o,now){if(o.type==='charge')return this.drawCharge(ctx,o,now);this.drawMaterial(ctx,o,now);}
    drawCharge(ctx,o,now){const c=this.chargeColors(o.q),pulse=C.storage.data.settings.reducedMotion?0:Math.sin(now*.005+o.x)*1.2;ctx.save();ctx.shadowColor=c.glow;ctx.shadowBlur=15+pulse*2;ctx.fillStyle=c.fill;ctx.strokeStyle='rgba(255,255,255,.86)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(o.x,o.y,o.r+pulse*.25,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,255,255,.22)';if(o.q<0){for(let a=0;a<Math.PI*2;a+=Math.PI/3){ctx.beginPath();ctx.arc(o.x,o.y,o.r-5,a,a+.34);ctx.stroke();}}else{ctx.beginPath();ctx.arc(o.x,o.y,o.r-5,0,Math.PI*2);ctx.stroke();}ctx.fillStyle='#fff';ctx.font='900 20px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(c.symbol,o.x,o.y+1);if(this.layers.labels){ctx.font='700 10px system-ui';ctx.fillStyle='rgba(232,246,255,.78)';ctx.fillText(o.name||'Carga',o.x,o.y+o.r+15);}if(this.layers.values){ctx.fillStyle='#fff';ctx.font='800 9px ui-monospace,monospace';ctx.fillText(`${o.q>0?'+':''}${U.formatNumber(o.q,1)}q`,o.x,o.y-o.r-10);}ctx.restore();}
    drawMaterial(ctx,o,now){const conductive=o.type==='conductor';ctx.save();ctx.shadowColor=o.contactGlow>0?'rgba(255,219,105,.8)':'rgba(163,205,229,.18)';ctx.shadowBlur=o.contactGlow>0?24:10;const g=ctx.createRadialGradient(o.x-o.r*.3,o.y-o.r*.35,2,o.x,o.y,o.r);g.addColorStop(0,conductive?'#d6edf8':'#f1e8d9');g.addColorStop(1,conductive?'#678ca3':'#9cb0bc');ctx.fillStyle=g;ctx.strokeStyle=conductive?'rgba(224,247,255,.9)':'rgba(255,255,255,.72)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;
      if(Math.abs(o.inducedCharge)>.01){const sep=Math.min(18,o.r*.62),px=o.x+o.dipX*sep,py=o.y+o.dipY*sep,nx=o.x-o.dipX*sep,ny=o.y-o.dipY*sep;ctx.strokeStyle='rgba(18,40,55,.48)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(nx,ny);ctx.lineTo(px,py);ctx.stroke();this.smallPole(ctx,px,py,'+',true);this.smallPole(ctx,nx,ny,'−',false);}
      if(Math.abs(o.staticCharge)>.025){const sign=o.staticCharge>0?'+':'−',positive=o.staticCharge>0,count=Math.min(8,Math.max(2,Math.ceil(Math.abs(o.staticCharge)*2)));for(let i=0;i<count;i++){const a=i/count*Math.PI*2+(o.id.length*.3);this.smallPole(ctx,o.x+Math.cos(a)*(o.r-5),o.y+Math.sin(a)*(o.r-5),sign,positive,5);}}
      ctx.fillStyle='#1c3446';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(conductive?'≋':'◐',o.x,o.y+1);if(this.layers.labels){ctx.fillStyle='rgba(232,246,255,.78)';ctx.font='700 10px system-ui';ctx.fillText(o.material,o.x,o.y+o.r+15);}if(this.layers.values){ctx.fillStyle='#fff';ctx.font='800 9px ui-monospace,monospace';ctx.fillText(`Qe ${o.staticCharge>=0?'+':''}${U.formatNumber(o.staticCharge,1)}`,o.x,o.y-o.r-10);}ctx.restore();}
    smallPole(ctx,x,y,symbol,positive,r=7){ctx.save();ctx.fillStyle=positive?'#ff5c63':'#4a8dff';ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font=`900 ${Math.max(7,r+2)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(symbol,x,y+.5);ctx.restore();}
    drawTest(ctx,t,now){ctx.save();ctx.shadowColor='rgba(36,216,189,.55)';ctx.shadowBlur=18;const g=ctx.createRadialGradient(t.x-4,t.y-5,1,t.x,t.y,t.r+3);g.addColorStop(0,'#8effec');g.addColorStop(1,'#20c9af');ctx.fillStyle=g;ctx.strokeStyle='#eafffb';ctx.lineWidth=2.2;ctx.beginPath();ctx.arc(t.x,t.y,t.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#063f38';ctx.font='900 11px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(t.q>0?'q+':'q−',t.x,t.y+1);if(this.layers.labels){ctx.fillStyle='rgba(190,255,244,.88)';ctx.font='800 10px system-ui';ctx.fillText('carga-teste',t.x,t.y+t.r+15);}ctx.restore();}
    vectorScale(magnitude,max=112){return U.clamp(Math.log1p(magnitude)*14,7,max);}
    drawResultant(ctx){const f=this.sim.forceOn(this.sim.scene.test);if(f.magnitude<.01)return;const len=this.vectorScale(f.magnitude),nx=f.x/f.magnitude,ny=f.y/f.magnitude;this.arrow(ctx,this.sim.scene.test.x,this.sim.scene.test.y,this.sim.scene.test.x+nx*len,this.sim.scene.test.y+ny*len,'#5df28c',3.2,10);}
    drawIndividualForces(ctx){const t=this.sim.scene.test,force=this.sim.forceOn(t);for(const part of force.parts){if(part.magnitude<.01)continue;const len=this.vectorScale(part.magnitude,75),nx=part.x/part.magnitude,ny=part.y/part.magnitude;this.arrow(ctx,t.x,t.y,t.x+nx*len,t.y+ny*len,'rgba(116,205,255,.72)',1.5,6);}}
    drawComponents(ctx){const t=this.sim.scene.test,f=this.sim.forceOn(t);const sx=Math.sign(f.x)*this.vectorScale(Math.abs(f.x),72),sy=Math.sign(f.y)*this.vectorScale(Math.abs(f.y),72);if(Math.abs(sx)>2)this.arrow(ctx,t.x,t.y,t.x+sx,t.y,'rgba(255,191,74,.85)',1.7,6);if(Math.abs(sy)>2)this.arrow(ctx,t.x,t.y,t.x,t.y+sy,'rgba(225,129,255,.85)',1.7,6);}
    drawVelocity(ctx){const t=this.sim.scene.test,speed=Math.hypot(t.vx,t.vy);if(speed<1)return;const len=U.clamp(speed*.22,7,75);this.arrow(ctx,t.x,t.y,t.x+t.vx/speed*len,t.y+t.vy/speed*len,'rgba(255,255,255,.8)',1.5,6);}
    drawDistances(ctx){const t=this.sim.scene.test;ctx.save();ctx.setLineDash([5,5]);ctx.strokeStyle='rgba(255,255,255,.18)';ctx.fillStyle='rgba(225,239,248,.75)';ctx.font='700 9px system-ui';ctx.textAlign='center';for(const o of this.sim.scene.objects.filter(o=>o.type==='charge')){ctx.beginPath();ctx.moveTo(t.x,t.y);ctx.lineTo(o.x,o.y);ctx.stroke();ctx.fillText(`${Math.round(U.distance(t,o))} u`,(t.x+o.x)/2,(t.y+o.y)/2-5);}ctx.restore();}
    drawSelection(ctx){const o=this.sim.selected;if(!o)return;ctx.save();ctx.strokeStyle='rgba(93,242,140,.9)';ctx.lineWidth=1.5;ctx.setLineDash([5,4]);ctx.beginPath();ctx.arc(o.x,o.y,(o.r||15)+7,0,Math.PI*2);ctx.stroke();ctx.restore();}
    drawEffects(ctx){ctx.save();for(const e of this.sim.effects){const alpha=U.clamp(e.life,0,1);if(e.type==='spark'){ctx.strokeStyle=`rgba(255,225,117,${alpha})`;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(e.x-12,e.y+6);ctx.lineTo(e.x-4,e.y-6);ctx.lineTo(e.x+2,e.y+4);ctx.lineTo(e.x+12,e.y-8);ctx.stroke();}else if(e.type==='impact'||e.type==='place'){ctx.strokeStyle=`rgba(143,220,255,${alpha*.7})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(e.x,e.y,(1-alpha)*28+5,0,Math.PI*2);ctx.stroke();}else if(e.type==='target'||e.type==='success'){ctx.strokeStyle=`rgba(255,204,76,${alpha*.75})`;ctx.lineWidth=e.type==='success'?4:2;ctx.beginPath();ctx.arc(e.x,e.y,(1-alpha)*(e.type==='success'?65:20)+24,0,Math.PI*2);ctx.stroke();}}ctx.restore();}
    arrow(ctx,x1,y1,x2,y2,color,width=2,head=7){const angle=Math.atan2(y2-y1,x2-x1);ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-Math.cos(angle-.48)*head,y2-Math.sin(angle-.48)*head);ctx.lineTo(x2-Math.cos(angle+.48)*head,y2-Math.sin(angle+.48)*head);ctx.closePath();ctx.fill();ctx.restore();}
  };
})();
