(function(){
  'use strict';
  const C=window.Cargas,U=C.util;
  C.quiz={
    initialized:false,difficulty:'basic',mode:'practice',questions:[],index:0,score:0,streak:0,answered:false,time:0,incorrect:[],topicResults:{},reviewMode:false,
    difficulties:{basic:['Básico','Sinais, atração, materiais e campo.','●'],intermediate:['Intermediário','Distância, intensidade, vetores e indução.','◆'],advanced:['Avançado','Potencial, equilíbrio, dipolos e blindagem.','↗'],expert:['Expert','Modelagem, energia e estabilidade numérica.','⚡']},
    init(){if(this.initialized)return;this.initialized=true;this.stage=new C.CanvasStage(document.getElementById('canvas-quiz'),620,250);this.renderDifficulties();this.bind();},
    renderDifficulties(){const root=document.getElementById('quiz-difficulties');root.innerHTML=Object.entries(this.difficulties).map(([id,d])=>`<button class="difficulty-card ${id===this.difficulty?'active':''}" data-difficulty="${id}"><span class="eyebrow">${d[2]} ${d[0]}</span><h2>${d[0]}</h2><p>${d[1]}</p></button>`).join('');root.querySelectorAll('[data-difficulty]').forEach(btn=>btn.addEventListener('click',()=>{this.difficulty=btn.dataset.difficulty;this.renderDifficulties();}));},
    bind(){document.getElementById('quiz-start-btn').addEventListener('click',()=>{this.mode=document.querySelector('[name="quizMode"]:checked').value;this.start();});document.getElementById('quiz-next-btn').addEventListener('click',()=>this.next());document.getElementById('quiz-why-btn').addEventListener('click',()=>this.showWhy());},
    start(customQuestions=null){this.questions=customQuestions||U.shuffle(C.data.quiz.filter(q=>q.difficulty===this.difficulty)).slice(0,8);this.index=0;this.score=0;this.streak=0;this.incorrect=[];this.topicResults={};this.reviewMode=!!customQuestions;document.getElementById('quiz-setup').classList.add('hidden');document.getElementById('quiz-stage').classList.remove('hidden');document.getElementById('quiz-question-total').textContent=this.questions.length;this.showQuestion();},
    showQuestion(){if(this.index>=this.questions.length){this.finish();return;}this.answered=false;this.time=this.mode==='challenge'?15:999;const q=this.questions[this.index];document.getElementById('quiz-difficulty-label').textContent=this.difficulties[this.difficulty][0];document.getElementById('quiz-topic').textContent=q.topic;document.getElementById('quiz-question-number').textContent=this.index+1;document.getElementById('quiz-streak').textContent=this.streak;document.getElementById('quiz-score').textContent=this.score;document.getElementById('quiz-progress-bar').style.width=`${this.index/this.questions.length*100}%`;document.getElementById('quiz-prompt').textContent=q.prompt;const answers=document.getElementById('quiz-answers');answers.innerHTML=q.answers.map((answer,i)=>`<button class="quiz-answer" data-answer="${i}"><span>${String.fromCharCode(65+i)}.</span> ${C.ui.escape(answer)}</button>`).join('');answers.querySelectorAll('[data-answer]').forEach(btn=>btn.addEventListener('click',()=>this.answer(Number(btn.dataset.answer))));document.getElementById('quiz-feedback').className='quiz-feedback hidden';document.getElementById('quiz-feedback').textContent='';document.getElementById('quiz-next-btn').classList.add('hidden');document.getElementById('quiz-why-btn').classList.add('hidden');this.drawVisual(q);},
    answer(choice,timedOut=false){if(this.answered)return;this.answered=true;const q=this.questions[this.index],correct=choice===q.correct;const buttons=[...document.querySelectorAll('.quiz-answer')];buttons.forEach((button,i)=>{button.disabled=true;if(i===q.correct)button.classList.add('correct');if(i===choice&&!correct)button.classList.add('incorrect');});const topic=this.topicResults[q.topic]||(this.topicResults[q.topic]={correct:0,total:0});topic.total++;if(correct){topic.correct++;this.streak++;this.score+=100+Math.min(100,this.streak*10)+(this.mode==='challenge'?Math.round(this.time*3):0);C.audio.tone('success');}else{this.streak=0;this.incorrect.push(q);C.audio.tone('error');}
      C.storage.update(data=>{data.quiz.answered++;if(correct)data.quiz.correct++;data.quiz.bestStreak=Math.max(data.quiz.bestStreak,this.streak);const record=data.quiz.topics[q.topic]||(data.quiz.topics[q.topic]={correct:0,total:0});record.total++;if(correct)record.correct++;});
      const feedback=document.getElementById('quiz-feedback');feedback.className=`quiz-feedback ${correct?'correct':'incorrect'}`;feedback.innerHTML=`<b>${correct?'Resposta correta':'Resposta incorreta'}</b><br>${C.ui.escape(timedOut?'O tempo terminou. '+q.explanation:q.explanation)}`;document.getElementById('quiz-why-btn').classList.remove('hidden');document.getElementById('quiz-next-btn').classList.remove('hidden');document.getElementById('quiz-next-btn').textContent=this.index===this.questions.length-1?'Ver resultado':'Próxima';document.getElementById('quiz-streak').textContent=this.streak;document.getElementById('quiz-score').textContent=this.score;if(this.streak>=10)C.app.unlockAchievement('quiz-streak');},
    showWhy(){const q=this.questions[this.index];C.ui.toast('Conceito por trás',q.explanation,'info',5200);},
    next(){this.index++;this.showQuestion();},
    finish(){document.getElementById('quiz-progress-bar').style.width='100%';const correct=this.questions.length-this.incorrect.length,percent=Math.round(correct/this.questions.length*100);const details=[{label:'Acertos',value:`${correct}/${this.questions.length}`},{label:'Aproveitamento',value:`${percent}%`},{label:'Pontos',value:this.score},{label:'Maior sequência',value:this.streak}];C.audio.tone('success');C.ui.result({kicker:this.reviewMode?'Revisão concluída':'Quiz concluído',title:percent>=80?'Excelente leitura elétrica':percent>=55?'Boa base — continue testando':'Hora de experimentar no laboratório',description:this.performanceSummary(),icon:percent>=80?'★':'?',details,primary:this.incorrect.length?'Refazer erros':'Novo quiz',secondary:'Voltar às categorias',onPrimary:()=>{if(this.incorrect.length){const list=U.shuffle(this.incorrect);this.start(list);}else this.start();},onSecondary:()=>this.backToSetup()});C.app.checkAchievements();},
    performanceSummary(){const entries=Object.entries(this.topicResults);if(!entries.length)return 'Continue praticando.';entries.sort((a,b)=>(a[1].correct/a[1].total)-(b[1].correct/b[1].total));const weakest=entries[0],strongest=entries[entries.length-1];return `Melhor desempenho em ${strongest[0]}. Vale revisar ${weakest[0]} e testar esse conceito no laboratório.`;},
    backToSetup(){document.getElementById('quiz-stage').classList.add('hidden');document.getElementById('quiz-setup').classList.remove('hidden');this.renderDifficulties();},
    drawVisual(q){const canvas=document.getElementById('canvas-quiz'),ctx=this.stage.ctx;const visual=['Sinais','Vetores','Distância','Campo elétrico','Resultante','Intensidade'].includes(q.topic);canvas.classList.toggle('hidden',!visual);if(!visual)return;this.stage.begin();const w=620,h=250;const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#0a1a2b');g.addColorStop(1,'#06111c');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(140,190,220,.08)';for(let x=20;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=20;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}
      if(q.topic==='Sinais'){const same=q.prompt.includes('positivas')||q.prompt.includes('negativas');this.drawCharge(ctx,220,125,q.prompt.includes('negativas')?-1:1);this.drawCharge(ctx,400,125,same?(q.prompt.includes('negativas')?-1:1):-1);this.drawArrow(ctx,290,125,330,125,same?'#ffbf4a':'#5df28c');}
      else if(q.topic==='Distância'||q.topic==='Intensidade'){this.drawCharge(ctx,140,125,1);this.drawCharge(ctx,q.topic==='Distância'?450:360,125,-1);ctx.setLineDash([6,5]);ctx.strokeStyle='rgba(255,255,255,.35)';ctx.beginPath();ctx.moveTo(165,125);ctx.lineTo((q.topic==='Distância'?425:335),125);ctx.stroke();ctx.setLineDash([]);}
      else{this.drawTest(ctx,310,125);this.drawArrow(ctx,310,125,410,125,'rgba(255,191,74,.9)');this.drawArrow(ctx,310,125,310,45,'rgba(225,129,255,.9)');ctx.fillStyle='rgba(235,246,252,.75)';ctx.font='700 12px system-ui';ctx.textAlign='center';ctx.fillText('Some as direções',310,220);}
    },
    drawCharge(ctx,x,y,q){ctx.save();ctx.fillStyle=q>0?'#ff5c63':'#4a8dff';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,24,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font='900 24px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(q>0?'+':'−',x,y+1);ctx.restore();},
    drawTest(ctx,x,y){ctx.save();ctx.fillStyle='#24d8bd';ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#073f37';ctx.font='900 12px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('q+',x,y+1);ctx.restore();},
    drawArrow(ctx,x1,y1,x2,y2,color){const a=Math.atan2(y2-y1,x2-x1);ctx.save();ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-Math.cos(a-.5)*10,y2-Math.sin(a-.5)*10);ctx.lineTo(x2-Math.cos(a+.5)*10,y2-Math.sin(a+.5)*10);ctx.fill();ctx.restore();},
    update(dt){if(document.getElementById('quiz-stage').classList.contains('hidden')||this.mode!=='challenge'||this.answered)return;this.time-=dt;document.getElementById('quiz-difficulty-label').textContent=`${this.difficulties[this.difficulty][0]} · ${Math.max(0,Math.ceil(this.time))}s`;if(this.time<=0)this.answer(-1,true);},
    render(){},
    onKey(event){if(C.app?.activeView!=='quiz'||document.querySelector('dialog[open]'))return false;if(event.key==='Escape'&&!document.getElementById('quiz-stage').classList.contains('hidden')){this.backToSetup();return true;}if(!this.answered&&/^[1-4]$/.test(event.key)){const index=Number(event.key)-1;document.querySelector(`[data-answer="${index}"]`)?.click();return true;}return false;}
  };
})();
