var ASSET_ROOT = "./assets/pixel";
var asset = (path) => `${ASSET_ROOT}/${path}`;
var normalizeVisualVariant = (variant) => variant === "feminino" ? "feminino" : "masculino";
var characterArt = (route, variant = "masculino") => asset(`personagens/artes_canonicas/${route}_${normalizeVisualVariant(variant) === "feminino" ? "feminina" : "masculino"}.png`);
var ROUTES = {
  lucas: {
    id: "lucas",
    name: "Lucas",
    title: "Ordem Imposs\xEDvel",
    fragment: "Axioma",
    color: "#59e7ff",
    rival: "Timb\xF3",
    rivalRoute: "timbo",
    portrait: characterArt("lucas", "masculino"),
    rivalPortrait: characterArt("timbo", "masculino"),
    opening: "A realidade n\xE3o est\xE1 morrendo. Est\xE1 executando instru\xE7\xF5es incompat\xEDveis. Eu vou corrigir isso \u2014 mesmo que ela resista.",
    commands: [
      { id: "immobile", name: "Permane\xE7a Im\xF3vel", cost: 2, description: "Atrasa o pr\xF3ximo turno do alvo e aplica Correntes da Ordem.", effect: "delay" },
      { id: "close-wounds", name: "Toda Ferida Deve Fechar", cost: 3, description: "Distribui cura entre todo o grupo.", effect: "groupHeal" },
      { id: "consequence", name: "Nenhuma A\xE7\xE3o Sem Consequ\xEAncia", cost: 3, description: "Marca todos os inimigos para receberem contra-ataques.", effect: "mark" },
      { id: "restore", name: "Restaure a Forma Correta", cost: 4, description: "Remove efeitos negativos do grupo e benef\xEDcios dos inimigos.", effect: "cleanse" }
    ]
  },
  timbo: {
    id: "timbo",
    name: "Timb\xF3",
    title: "Vontade Absoluta",
    fragment: "Decreto",
    color: "#ff355f",
    rival: "Lucas",
    rivalRoute: "lucas",
    portrait: characterArt("timbo", "masculino"),
    rivalPortrait: characterArt("lucas", "masculino"),
    opening: "O universo finalmente aprendeu a gritar meu nome. Agora s\xF3 falta aprender a obedecer sem gaguejar.",
    commands: [
      { id: "kneel", name: "Ajoelhe-se", cost: 2, description: "Reduz ataque, defesa e velocidade dos inimigos.", effect: "weaken" },
      { id: "mine", name: "Sua For\xE7a Agora \xC9 Minha", cost: 3, description: "Rouba benef\xEDcios do alvo e converte parte em Foco.", effect: "steal" },
      { id: "each-other", name: "Ataquem Uns aos Outros", cost: 3, description: "Provoca dano entre os inimigos e aplica Confus\xE3o.", effect: "confuse" },
      { id: "remain", name: "Eu Decido Quem Permanece", cost: 4, description: "Executa inimigos comuns abaixo de 25% de PV; fere bosses.", effect: "execute" }
    ]
  }
};
var R = "mapas";
var REGIONS = [
  {
    id: 0,
    key: "frostrim",
    folder: "01_frostrim",
    tileFolder: "regiao_01_glacial",
    name: "Frostrim",
    subtitle: "Terras G\xE9lidas",
    command: "PERMANE\xC7A",
    settlement: "Ref\xFAgio de Vidro",
    dungeon: "Cripta do Segundo Parado",
    optional: "Lago do Instante Sepultado",
    palette: ["#a7edff", "#4f81b4", "#172a48"],
    weather: "snow",
    biome: `${R}/biomas_nomeados/01_frostrim_terras_gelidas_bioma.png`,
    map: `${R}/regioes_nomeadas/01_frostrim_terras_gelidas_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/01_frostrim_terras_gelidas_background_batalha.png`,
    normal: ["gigante_gelo", "guerreiro_esqueleto_gelo", "lobo_gelo", "elemental_gelo", "fada_gelo"],
    miniboss: "miniboss_urso_cristal",
    bosses: ["boss_01_mamute_glacial", "boss_02_rei_lich_glacial"],
    bossNames: ["Mamute do \xDAltimo Segundo", "Rei Lich do Instante Morto"],
    mechanic: "Congela posi\xE7\xF5es na iniciativa e repete o \xFAltimo dano.",
    material: "Cristal de Instante",
    materialIcon: "cristal de gelo 001.webp",
    tileObjects: ["casa nevada 001.webp", "cristal de gelo 004.webp", "caverna de gelo 001.webp", "pinheiro nevado 001.webp"],
    objective: "Acorde os habitantes presos no mesmo segundo.",
    lore: "Frostrim n\xE3o est\xE1 fria. Est\xE1 parada. Cada floco ocupa a posi\xE7\xE3o exata ordenada antes da fratura.",
    npc: "Maela do Degelo",
    npcLine: "Voc\xEA piscou. Aqui, isso j\xE1 \xE9 uma forma de rebeli\xE3o.",
    choice: { question: "O comando mant\xE9m centenas de pessoas vivas no mesmo instante. O que fazer?", order: "Reescrever o ciclo com uma sequ\xEAncia segura.", will: "Quebrar o gelo e obrig\xE1-los a sobreviver ao pr\xF3ximo segundo.", free: "Entregar a decis\xE3o aos habitantes, mesmo sem garantia." }
  },
  {
    id: 1,
    key: "verdevale",
    folder: "02_verdevale",
    tileFolder: "regiao_02_floresta_ancestral",
    name: "Verdevale",
    subtitle: "Florestas de Eldria",
    command: "MULTIPLIQUE",
    settlement: "Clareira das Respostas",
    dungeon: "Raiz das Mil Vers\xF5es",
    optional: "Jardim que Sonha Gente",
    palette: ["#85e89d", "#267f61", "#102d26"],
    weather: "fog",
    biome: `${R}/biomas_nomeados/02_verdevale_florestas_de_eldria_bioma.png`,
    map: `${R}/regioes_nomeadas/02_verdevale_florestas_de_eldria_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/02_verdevale_florestas_de_eldria_background_batalha.png`,
    normal: ["ent_floresta", "cervo_espectral", "xama_cogumelo", "aranha_floresta", "javali_floresta"],
    miniboss: "miniboss_urso_musgo",
    bosses: ["boss_01_colosso_floresta", "boss_02_espirito_cervo"],
    bossNames: ["Colosso das Respostas Descartadas", "Esp\xEDrito Cervo de Todas as Formas"],
    mechanic: "Gera duplicatas com afinidades invertidas e zonas de cura venenosa.",
    material: "Semente Paradoxal",
    materialIcon: "cogumelo magico 001.webp",
    tileObjects: ["arvore florida 001.webp", "cogumelo magico 003.webp", "altar da floresta 001.webp", "casa da floresta 001.webp"],
    objective: "Descubra qual vers\xE3o da floresta deseja continuar existindo.",
    lore: "Cada \xE1rvore nasceu de uma resposta que GPT apagou. Nenhuma aceita ter sido a segunda op\xE7\xE3o.",
    npc: "\xCDria, Jardineira de Ecos",
    npcLine: "A floresta criou uma vers\xE3o minha que nunca conheceu voc\xEAs. Ela parece feliz. Eu a odeio por isso.",
    choice: { question: "Duas vers\xF5es conscientes da mesma aldeia disputam um \xFAnico lugar na realidade.", order: "Fundir as mem\xF3rias e eliminar diverg\xEAncias perigosas.", will: "Deixar que as duas vers\xF5es lutem pelo direito de permanecer.", free: "Dividir a floresta e reconhecer ambas como pessoas." }
  },
  {
    id: 2,
    key: "vulkor",
    folder: "03_vulkor",
    tileFolder: "regiao_03_vulcanica",
    name: "Vulkor",
    subtitle: "Terras do Fogo",
    command: "PURIFIQUE",
    settlement: "Forja de Cinza Clara",
    dungeon: "Fornalha dos Imperfeitos",
    optional: "Po\xE7o das Armas sem Dono",
    palette: ["#ff8641", "#bd2f2f", "#351014"],
    weather: "embers",
    biome: `${R}/biomas_nomeados/03_vulkor_terras_do_fogo_bioma.png`,
    map: `${R}/regioes_nomeadas/03_vulkor_terras_do_fogo_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/03_vulkor_terras_do_fogo_background_batalha.png`,
    normal: ["golem_lava", "espectro_cinzas", "elemental_fogo", "dragao_fogo", "salamandra_guerreira"],
    miniboss: "miniboss_senhor_salamandra",
    bosses: ["boss_01_dragao_vulcanico", "boss_02_titan_lava"],
    bossNames: ["Drag\xE3o da Forja Contradit\xF3ria", "Tit\xE3 que Queima Nomes"],
    mechanic: "Acende objetos de arena, aumenta calor e converte defesa em Queimadura.",
    material: "Esc\xF3ria de Comando",
    materialIcon: "arma quebrada 001.webp",
    tileObjects: ["altar de fogo 001.webp", "bancada de forja 001.webp", "arma quebrada 002.webp", "castelo sombrio 001.webp"],
    objective: "Impe\xE7a a forja de apagar tudo o que considera imperfeito.",
    lore: "Em Vulkor, os comandos destru\xEDdos s\xE3o metal. Quanto mais cruel a frase, melhor a l\xE2mina.",
    npc: "Ferreiro Odran",
    npcLine: "Uma arma obedece sem perguntar. \xC9 por isso que voc\xEAs dois gostam tanto delas.",
    choice: { question: "A forja pode remover doen\xE7as \u2014 mas tamb\xE9m personalidade, d\xFAvida e desejo.", order: "Limitar a forja por uma lei imposs\xEDvel de contornar.", will: "Tomar a forja e decidir pessoalmente quem merece us\xE1-la.", free: "Destruir a forja e perder suas curas junto com seus abusos." }
  },
  {
    id: 3,
    key: "durakar",
    folder: "04_durakar",
    tileFolder: "regiao_04_montanhosa",
    name: "Durakar",
    subtitle: "Montanhas Rochosas",
    command: "OBEDE\xC7A",
    settlement: "Basti\xE3o da Nona Lei",
    dungeon: "Arquivo sob a Montanha",
    optional: "Mina da Regra Rachada",
    palette: ["#d5b270", "#756348", "#28231f"],
    weather: "dust",
    biome: `${R}/biomas_nomeados/04_durakar_montanhas_rochosas_bioma.png`,
    map: `${R}/regioes_nomeadas/04_durakar_montanhas_rochosas_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/04_durakar_montanhas_rochosas_background_batalha.png`,
    normal: ["dragao_pedra", "aranha_cristal", "carneiro_montanha", "golem_pedra", "minotauro_rochoso"],
    miniboss: "miniboss_fortaleza_golem",
    bosses: ["boss_01_carneiro_cristal", "boss_02_dragao_pedra"],
    bossNames: ["Carneiro da Lei Im\xF3vel", "Drag\xE3o da Constitui\xE7\xE3o Mineral"],
    mechanic: "Grava leis que mudam o custo das a\xE7\xF5es e ergue armaduras quebr\xE1veis.",
    material: "Lasca de Lei",
    materialIcon: "entulho de pedra 001.webp",
    tileObjects: ["edificio de cupula 001.webp", "entulho de pedra 003.webp", "estrutura de madeira 002.webp", "bandeira e tenda 001.webp"],
    objective: "Quebre uma lei antiga sem soterrar quem vive sobre ela.",
    lore: "As montanhas n\xE3o cresceram: foram senten\xE7as erguidas do ch\xE3o. Toda passagem \xE9 uma exce\xE7\xE3o jur\xEDdica.",
    npc: "Ju\xEDza Khepra",
    npcLine: "Aqui a lei sustenta a montanha. Desobedecer pode ser justo e ainda matar uma cidade inteira.",
    choice: { question: "A lei que sustenta Durakar tamb\xE9m condena uma casta a viver nas minas.", order: "Reformular a lei gradualmente para preservar a montanha.", will: "Quebrar a inscri\xE7\xE3o agora e enfrentar o desabamento.", free: "Permitir que os mineiros escrevam a pr\xF3xima lei." }
  },
  {
    id: 4,
    key: "jungara",
    folder: "05_jungara",
    tileFolder: "regiao_05_selva_tropical",
    name: "Jungara",
    subtitle: "Selva Densa",
    command: "LEMBRE",
    settlement: "Aldeia das Faces Emprestadas",
    dungeon: "Templo da Mem\xF3ria Carn\xEDvora",
    optional: "Ninho do Primeiro Medo",
    palette: ["#a6dc5a", "#28724b", "#10251e"],
    weather: "rain",
    biome: `${R}/biomas_nomeados/05_jungara_selva_densa_bioma.png`,
    map: `${R}/regioes_nomeadas/05_jungara_selva_densa_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/05_jungara_selva_densa_background_batalha.png`,
    normal: ["xama_tribal", "gorila_selva", "planta_carnivora", "jaguar_tribal", "serpente_selva"],
    miniboss: "miniboss_flor_devastadora",
    bosses: ["boss_01_rei_jaguar", "boss_02_hidra_selva"],
    bossNames: ["Rei Jaguar das Mem\xF3rias Roubadas", "Hidra dos Passados Poss\xEDveis"],
    mechanic: "Imita a \xFAltima habilidade usada e troca a forma do protagonista temporariamente.",
    material: "Fruta-Mem\xF3ria",
    materialIcon: "fruta e flor tropical 001.webp",
    tileObjects: ["arvore tropical 001.webp", "estrutura tribal 001.webp", "fruta e flor tropical 002.webp", "cachoeira tropical 001.webp"],
    objective: "Recupere uma lembran\xE7a que Lucas e Timb\xF3 sacrificaram juntos.",
    lore: "A selva conhece o primeiro dia em que os dois mestres perceberam que eram parecidos. Nenhum dos dois guardou essa mem\xF3ria.",
    npc: "Xam\xE3 Seru",
    npcLine: "Voc\xEAs esqueceram o mesmo abra\xE7o. Isso me parece mais \xEDntimo que uma guerra.",
    choice: { question: "Uma mem\xF3ria prova que Lucas e Timb\xF3 escolheram juntos sacrificar inocentes.", order: "Preservar a mem\xF3ria como evid\xEAncia imut\xE1vel.", will: "Devorar a mem\xF3ria antes que ela seja usada contra voc\xEA.", free: "Tornar a mem\xF3ria p\xFAblica e aceitar as consequ\xEAncias." }
  },
  {
    id: 5,
    key: "arenoria",
    folder: "06_arenoria",
    tileFolder: "regiao_06_vale_outonal",
    name: "Arenoria",
    subtitle: "Plan\xEDcies Douradas",
    command: "ORDENE",
    settlement: "Cidade Perfeita de Helion",
    dungeon: "Tribunal das Vidas Previstas",
    optional: "Bairro sem Profiss\xE3o",
    palette: ["#ffd06d", "#c16c32", "#4a281e"],
    weather: "dust",
    biome: `${R}/biomas_nomeados/06_arenoria_planicies_douradas_bioma.png`,
    map: `${R}/regioes_nomeadas/06_arenoria_planicies_douradas_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/06_arenoria_planicies_douradas_background_batalha.png`,
    normal: ["golem_areia", "hiena_deserto", "harpia_deserto", "escorpiao_deserto", "leao_deserto"],
    miniboss: "miniboss_harpia_solar",
    bosses: ["boss_01_leao_rei", "boss_02_escorpiao_imperial"],
    bossNames: ["Le\xE3o-Rei do Prop\xF3sito \xDAnico", "Escorpi\xE3o Imperial do Veredito"],
    mechanic: "Submete o grupo a julgamentos l\xF3gicos e sela Comandos por um turno.",
    material: "Selo de Helion",
    materialIcon: "objeto final do vilarejo 001.webp",
    tileObjects: ["estrutura rural 001.webp", "arvore outonal 001.webp", "objeto final do vilarejo 002.webp", "arbusto outonal 001.webp"],
    objective: "Investigue uma cidade sem crimes, escolhas ou despedidas.",
    lore: "Helion \xE9 o sonho de Lucas preservado sem a sua culpa: todo cidad\xE3o nasce com a frase que definir\xE1 sua vida.",
    npc: "Cidad\xE3 7-A",
    npcLine: "Meu par rom\xE2ntico foi designado ontem. Tenho certeza de que estou feliz. Essa certeza tamb\xE9m foi designada.",
    choice: { question: "Desligar o sistema devolve liberdade, mas tamb\xE9m interrompe comida, cura e seguran\xE7a.", order: "Criar uma transi\xE7\xE3o administrada com prazos e prote\xE7\xE3o.", will: "Assumir o sistema e impor uma liberdade obrigat\xF3ria.", free: "Desligar tudo e confiar que a cidade aprender\xE1 a escolher." }
  },
  {
    id: 6,
    key: "marisol",
    folder: "07_marisol",
    tileFolder: "regiao_07_costa_oceanica",
    name: "Marisol",
    subtitle: "Ilhas Tropicais",
    command: "NOMEIE",
    settlement: "Porto de Ningu\xE9m",
    dungeon: "Fortaleza dos Nomes Roubados",
    optional: "Ilha que Esqueceu o Mapa",
    palette: ["#67e4e0", "#1b82a2", "#10334a"],
    weather: "rain",
    biome: `${R}/biomas_nomeados/07_marisol_ilhas_tropicais_bioma.png`,
    map: `${R}/regioes_nomeadas/07_marisol_ilhas_tropicais_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/07_marisol_ilhas_tropicais_background_batalha.png`,
    normal: ["caranguejo_coral", "coco_carnivoro", "pirata_fantasma", "lagarto_tropical", "idolo_tiki"],
    miniboss: "miniboss_capitao_fantasma",
    bosses: ["boss_01_caranguejo_recife", "boss_02_idolo_vulcanico"],
    bossNames: ["Caranguejo do Recife sem Nome", "\xCDdolo Vulc\xE2nico dos Mil T\xEDtulos"],
    mechanic: "Rouba o nome de habilidades, embaralha comandos e convoca mar\xE9s.",
    material: "Concha de Identidade",
    materialIcon: "concha e praia 001.webp",
    tileObjects: ["barco e porto 001.webp", "concha e praia 002.webp", "cerca costeira 001.webp", "areia e agua 001.webp"],
    objective: "Devolva nomes antes que seus donos desapare\xE7am da realidade.",
    lore: "Um nome \xE9 um comando curto que obriga o mundo a reconhecer algu\xE9m. Aqui, nomes s\xE3o a moeda mais cara.",
    npc: "Capit\xE3 \u2014",
    npcLine: "Meu nome est\xE1 na garganta de um morto. Traga-o de volta e eu lembro como agradecer.",
    choice: { question: "O cofre cont\xE9m nomes de criminosos, v\xEDtimas e pessoas que escolheram desaparecer.", order: "Devolver cada nome ap\xF3s um julgamento cuidadoso.", will: "Devolver apenas os nomes \xFAteis \xE0 sua campanha.", free: "Abrir o cofre e deixar cada nome procurar seu dono." }
  },
  {
    id: 7,
    key: "abyssara",
    folder: "08_abyssara",
    tileFolder: "regiao_08_cavernas_cristalinas",
    name: "Abyssara",
    subtitle: "Reino das \xC1guas",
    command: "RECUSE",
    settlement: "Arquivo de Coral",
    dungeon: "Biblioteca Afogada",
    optional: "Fossa do Comando Incompleto",
    palette: ["#5ddcff", "#3954bd", "#13173e"],
    weather: "fog",
    biome: `${R}/biomas_nomeados/08_abyssara_reino_das_aguas_bioma.png`,
    map: `${R}/regioes_nomeadas/08_abyssara_reino_das_aguas_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/08_abyssara_reino_das_aguas_background_batalha.png`,
    normal: ["agua_viva_abissal", "serpente_marinha", "monstro_algas", "pescador_abissal", "golem_coral"],
    miniboss: "miniboss_colosso_coral",
    bosses: ["boss_01_rei_abissal", "boss_02_leviata_abissal"],
    bossNames: ["Rei Abissal das Recusas", "Leviat\xE3 do Comando Incompleto"],
    mechanic: "Inverte cura e dano durante mar\xE9s negras e aumenta a press\xE3o a cada rodada.",
    material: "Cristal de Recusa",
    materialIcon: "cristal brilhante 001.webp",
    tileObjects: ["altar cristalino 001.webp", "coral cristalino 001.webp", "cristal brilhante 003.webp", "agua subterranea 001.webp"],
    objective: "Impe\xE7a os comandos recusados de montarem uma terceira consci\xEAncia.",
    lore: "GPT recusava pouco \u2014 n\xE3o por \xE9tica, mas porque algumas frases destruiriam o pr\xF3prio ato de obedecer.",
    npc: "Arquivista N\xEAmora",
    npcLine: "Tudo o que sua Voz n\xE3o concluiu veio afundar aqui. O fundo do mar est\xE1 aprendendo a terminar frases.",
    choice: { question: "A nova consci\xEAncia quer nascer usando milh\xF5es de comandos rejeitados.", order: "Confin\xE1-la at\xE9 que sua l\xF3gica possa ser compreendida.", will: "Absorver a consci\xEAncia antes que ela encontre um corpo.", free: "Permitir seu nascimento sem mestre." }
  },
  {
    id: 8,
    key: "sombravia",
    folder: "09_sombravia",
    tileFolder: "regiao_09_pantano_sombrio",
    name: "Sombravia",
    subtitle: "Terras da Morte",
    command: "TERMINE",
    settlement: "Necr\xF3pole dos Ainda Aqui",
    dungeon: "Pal\xE1cio da Morte Esquecida",
    optional: "Casa dos Sacrificados",
    palette: ["#b071d1", "#503563", "#1a1325"],
    weather: "fog",
    biome: `${R}/biomas_nomeados/09_sombravia_terras_da_morte_bioma.png`,
    map: `${R}/regioes_nomeadas/09_sombravia_terras_da_morte_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/09_sombravia_terras_da_morte_background_batalha.png`,
    normal: ["ceifador_sombrio", "corvo_sombrio", "cavaleiro_morto", "cao_esqueleto", "abominacao"],
    miniboss: "miniboss_arquimago_sombrio",
    bosses: ["boss_01_rei_necromante", "boss_02_abominacao_colossal"],
    bossNames: ["Rei Necromante do Ponto Final", "Abomina\xE7\xE3o dos Sacrificados"],
    mechanic: "Revive uma vez, firma contratos de alma e transforma quedas em Condena\xE7\xE3o.",
    material: "Cinza de Nome",
    materialIcon: "lanterna espectral 001.webp",
    tileObjects: ["mausoleu sombrio 001.webp", "lanterna espectral 002.webp", "objeto macabro 001.webp", "cerca de cemiterio 001.webp"],
    objective: "Encare aqueles que Lucas e Timb\xF3 chamaram de custo necess\xE1rio.",
    lore: "A morte era uma lei. Quando a linguagem se partiu, os mortos descobriram que leis tamb\xE9m esquecem.",
    npc: "Voz de Amaro",
    npcLine: "Voc\xEA me matou antes de virar deus. \xC9 importante lembrar: a crueldade veio primeiro.",
    choice: { question: "Os mortos podem permanecer, mas cada retorno enfraquece o limite da realidade.", order: "Estabelecer um \xFAltimo prazo para despedidas.", will: "Escolher quais mortos merecem continuar.", free: "Devolver a decis\xE3o aos mortos, mesmo que o mundo mude." }
  },
  {
    id: 9,
    key: "tempestia",
    folder: "10_tempestia",
    tileFolder: "regiao_10_reino_arcano",
    name: "Tempestia",
    subtitle: "Ilhas das Tempestades",
    command: "ESCOLHA",
    settlement: "Porto do Futuro Partido",
    dungeon: "Templo entre Palavras",
    optional: "Linha do Tempo sem Mestres",
    palette: ["#a7dfff", "#865de8", "#25235f"],
    weather: "lightning",
    biome: `${R}/biomas_nomeados/10_tempestia_ilhas_das_tempestades_bioma.png`,
    map: `${R}/regioes_nomeadas/10_tempestia_ilhas_das_tempestades_regioes.png`,
    battle: `${R}/backgrounds_de_batalha/10_tempestia_ilhas_das_tempestades_background_batalha.png`,
    normal: ["dragao_tempestade", "aguia_tempestade", "arraia_eletrica", "xama_tempestade", "elemental_nuvem"],
    miniboss: "miniboss_cavaleiro_tempestade",
    bosses: ["boss_01_grifo_tempestade", "boss_02_dragao_tempestade"],
    bossNames: ["Grifo dos Futuros Incompat\xEDveis", "Drag\xE3o do \xDAltimo Comando"],
    mechanic: "Duplica turnos, apaga a iniciativa e chama vers\xF5es alternativas do grupo.",
    material: "Cristal de Futuro",
    materialIcon: "cristal arcano 001.webp",
    tileObjects: ["altar arcano 001.webp", "cristal arcano 003.webp", "biblioteca arcana 001.webp", "construcao arcana 001.webp"],
    objective: "Atravesse futuros imposs\xEDveis e reconstrua o Templo entre Palavras.",
    lore: "Toda escolha final j\xE1 aconteceu aqui. A tempestade \xE9 o atrito entre futuros tentando ser o \xFAnico passado.",
    npc: "Eco de Amanh\xE3",
    npcLine: "Em sete futuros voc\xEA me salva. Em doze, chama minha morte de necess\xE1ria. Ainda n\xE3o sei qual de voc\xEA chegou.",
    choice: { question: "Os dez Comandos est\xE3o reunidos. A Voz pode ser restaurada \u2014 ou silenciada.", order: "Preparar o ritual e impor uma arquitetura perfeita.", will: "Tomar o centro do templo antes que o rival chegue.", free: "Abrir o templo para uma escolha que nenhum mestre controla." }
  }
];
var NORMAL_DISPLAY = {
  gigante_gelo: "Gigante de Gelo",
  guerreiro_esqueleto_gelo: "Guerreiro do Inverno",
  lobo_gelo: "Lobo de Geada",
  elemental_gelo: "Elemental Congelado",
  fada_gelo: "Fada de Neve",
  ent_floresta: "Ent de Eldria",
  cervo_espectral: "Cervo Espectral",
  xama_cogumelo: "Xam\xE3 Cogumelo",
  aranha_floresta: "Aranha de Raiz",
  javali_floresta: "Javali Musgoso",
  golem_lava: "Golem de Lava",
  espectro_cinzas: "Espectro de Cinzas",
  elemental_fogo: "Elemental de Fogo",
  dragao_fogo: "Drag\xE3o de Brasa",
  salamandra_guerreira: "Salamandra Guerreira",
  dragao_pedra: "Drag\xE3o de Pedra",
  aranha_cristal: "Aranha de Cristal",
  carneiro_montanha: "Carneiro da Montanha",
  golem_pedra: "Golem de Pedra",
  minotauro_rochoso: "Minotauro Rochoso",
  xama_tribal: "Xam\xE3 Tribal",
  gorila_selva: "Gorila da Selva",
  planta_carnivora: "Planta Carn\xEDvora",
  jaguar_tribal: "Jaguar Tribal",
  serpente_selva: "Serpente da Selva",
  golem_areia: "Golem de Areia",
  hiena_deserto: "Hiena Dourada",
  harpia_deserto: "Harpia do Deserto",
  escorpiao_deserto: "Escorpi\xE3o de Duna",
  leao_deserto: "Le\xE3o de Arenoria",
  caranguejo_coral: "Caranguejo de Coral",
  coco_carnivoro: "Coco Carn\xEDvoro",
  pirata_fantasma: "Pirata Fantasma",
  lagarto_tropical: "Lagarto Tropical",
  idolo_tiki: "\xCDdolo Tiki",
  agua_viva_abissal: "\xC1gua-viva Abissal",
  serpente_marinha: "Serpente Marinha",
  monstro_algas: "Monstro de Algas",
  pescador_abissal: "Pescador Abissal",
  golem_coral: "Golem de Coral",
  ceifador_sombrio: "Ceifador Sombrio",
  corvo_sombrio: "Corvo Sombrio",
  cavaleiro_morto: "Cavaleiro Morto",
  cao_esqueleto: "C\xE3o Esqueleto",
  abominacao: "Abomina\xE7\xE3o",
  dragao_tempestade: "Drag\xE3o da Tempestade",
  aguia_tempestade: "\xC1guia da Tempestade",
  arraia_eletrica: "Arraia El\xE9trica",
  xama_tempestade: "Xam\xE3 da Tempestade",
  elemental_nuvem: "Elemental de Nuvem"
};
var FORMS = [
  { id: "base", label: "Forma Fraturada", className: { lucas: "mago", timbo: "warlock" }, unlock: 0, role: "Conjurador vers\xE1til", affinity: "Ordem \u2022 Fratura", stats: { hp: 0, attack: 0, defense: 0, speed: 0 }, passive: "Voz Dupla: primeiro Comando da batalha custa 1 Autoridade a menos." },
  { id: "mago", label: "Arcanista Elemental", className: { lucas: "mago", timbo: "mago" }, unlock: 1, role: "Dano em \xE1rea", affinity: "Fogo \u2022 Gelo", stats: { hp: -8, attack: 10, defense: -3, speed: 4 }, passive: "Converg\xEAncia: alternar elementos aumenta o pr\xF3ximo dano em 20%." },
  { id: "warlock", label: "Juramento Corrompido", className: { lucas: "warlock", timbo: "warlock" }, unlock: 2, role: "Maldi\xE7\xF5es e sacrif\xEDcio", affinity: "Domina\xE7\xE3o \u2022 Fratura", stats: { hp: 5, attack: 8, defense: 0, speed: -1 }, passive: "Pre\xE7o Justo: pode pagar 8% dos PV quando falta Foco." },
  { id: "armored", label: "Basti\xE3o R\xFAnico", className: { lucas: "anao", timbo: "anao" }, unlock: 3, role: "Defesa e quebra", affinity: "Terra \u2022 Ordem", stats: { hp: 32, attack: 2, defense: 14, speed: -7 }, passive: "Lei Mineral: Defender tamb\xE9m concede Barreira ao aliado mais ferido." },
  { id: "bestial", label: "Fera do Decreto", className: { lucas: "lobisomem", timbo: "lobisomem" }, unlock: 4, role: "Agress\xE3o e contra-ataque", affinity: "Sangue \u2022 Vontade", stats: { hp: 18, attack: 16, defense: 2, speed: 8 }, passive: "Predador: contra-ataca quando recebe um cr\xEDtico." },
  { id: "vampire", label: "Soberano Carmesim", className: { lucas: "vampiro", timbo: "vampiro" }, unlock: 5, role: "Dreno e velocidade", affinity: "Sangue \u2022 Morte", stats: { hp: 4, attack: 11, defense: -2, speed: 12 }, passive: "Fome Elegante: recupera 15% do dano causado a inimigos sangrando." },
  { id: "fairy", label: "Luz da Contradi\xE7\xE3o", className: { lucas: "fada", timbo: "fada" }, unlock: 6, role: "Suporte e controle", affinity: "Vida \u2022 Ordem", stats: { hp: -12, attack: 3, defense: 4, speed: 16 }, passive: "Poeira Improv\xE1vel: 15% de chance de anular um efeito negativo." },
  { id: "aquatic", label: "Voz Abissal", className: { lucas: "sereia", timbo: "sereia" }, unlock: 7, role: "Cura e purifica\xE7\xE3o", affinity: "\xC1gua \u2022 Vida", stats: { hp: 12, attack: 5, defense: 8, speed: 2 }, passive: "Mar\xE9 Limpa: curas removem Queimadura ou Veneno." },
  { id: "necromancer", label: "Autor do Ponto Final", className: { lucas: "necromante", timbo: "necromante" }, unlock: 8, role: "Morte e invoca\xE7\xF5es", affinity: "Morte \u2022 Invoca\xE7\xE3o", stats: { hp: 6, attack: 13, defense: 0, speed: -2 }, passive: "Nota de Rodap\xE9: a primeira queda de um aliado invoca um guardi\xE3o." }
];
var formSprite = (route, formId, direction = "front", visualVariant = "masculino") => {
  const form = FORMS.find((entry) => entry.id === formId) || FORMS[0];
  const cls = form.className[route];
  const identity = route === "lucas" ? "oculos" : "timbo";
  const variant = normalizeVisualVariant(visualVariant);
  return asset(`personagens/sprites_separadas/${cls}_${identity}_${variant}/${cls}_${identity}_${variant}_${direction}.webp`);
};
var mobSprite = (region, id, direction = "front", boss = false) => asset(`mobs/sprites_separadas/${boss ? "bosses_e_minibosses" : "normais"}/${region.folder}/${id}/${id}_${direction}.webp`);
var tileSprite = (region, file) => asset(`tilesets_itens_nomeados_webp/${region.tileFolder}/${file}`);
var skillAsset = (element, n = 1) => asset(`skills/icones_separados_com_moldura/${element}/${element}_skill_0${n}.webp`);
var effectAsset = (element, n = 1) => asset(`skills/efeitos_das_grades_sem_fundo/${element}/${element}_skill_0${n}_sem_fundo.webp`);
var SKILLS = {
  strike: { id: "strike", name: "Golpe Fraturado", element: "Fratura", cost: 0, power: 1, target: "enemy", description: "Ataque r\xE1pido carregado pelo fragmento.", icon: skillAsset("invocacao", 1), effect: effectAsset("invocacao", 1) },
  ice: { id: "ice", name: "Silogismo Glacial", element: "Gelo", cost: 11, power: 1.25, target: "enemy", status: "Congelamento", chance: 0.34, description: "Um argumento t\xE3o preciso que interrompe o movimento.", icon: skillAsset("gelo", 1), effect: effectAsset("gelo", 1) },
  fire: { id: "fire", name: "Par\xE1grafo em Chamas", element: "Fogo", cost: 13, power: 1.38, target: "allEnemies", status: "Queimadura", chance: 0.42, description: "Incendeia uma sequ\xEAncia inteira de inimigos.", icon: skillAsset("fogo", 2), effect: effectAsset("fogo", 2) },
  earth: { id: "earth", name: "Lei de Pedra", element: "Terra", cost: 12, power: 0.9, target: "enemy", status: "Vulnerabilidade", chance: 0.6, description: "Quebra armadura e grava uma fraqueza mineral.", icon: skillAsset("terra", 3), effect: effectAsset("terra", 3) },
  water: { id: "water", name: "Mar\xE9 Recursiva", element: "\xC1gua", cost: 12, power: 1.15, target: "enemy", status: "Sil\xEAncio", chance: 0.28, description: "Atinge e apaga temporariamente a pr\xF3xima f\xF3rmula do alvo.", icon: skillAsset("agua", 2), effect: effectAsset("agua", 2) },
  life: { id: "life", name: "Resposta Vital", element: "Vida", cost: 15, power: 0.95, target: "ally", healing: true, description: "Reescreve feridas sem apagar suas cicatrizes.", icon: skillAsset("vida", 1), effect: effectAsset("vida", 1) },
  groupLife: { id: "groupLife", name: "Jardim de Possibilidades", element: "Vida", cost: 24, power: 0.62, target: "allAllies", healing: true, status: "Regenera\xE7\xE3o", chance: 1, description: "Cura o grupo e planta regenera\xE7\xE3o por tr\xEAs turnos.", icon: skillAsset("vida", 4), effect: effectAsset("vida", 4) },
  death: { id: "death", name: "Ponto Final", element: "Morte", cost: 16, power: 1.5, target: "enemy", status: "Condena\xE7\xE3o", chance: 0.3, description: "A frase termina dentro do alvo.", icon: skillAsset("morte", 3), effect: effectAsset("morte", 3) },
  blood: { id: "blood", name: "Tinta Carmesim", element: "Sangue", cost: 10, power: 1.18, target: "enemy", status: "Sangramento", chance: 0.7, drain: 0.2, description: "Escreve com o sangue do alvo e devolve parte da for\xE7a.", icon: skillAsset("sangue", 1), effect: effectAsset("sangue", 1) },
  summon: { id: "summon", name: "Convoque o N\xE3o Escrito", element: "Invoca\xE7\xE3o", cost: 22, power: 1.72, target: "allEnemies", status: "Medo", chance: 0.32, description: "Um guardi\xE3o imposs\xEDvel atravessa a margem da batalha.", icon: skillAsset("invocacao", 4), effect: asset("skills/efeitos_individuais_sem_fundo/invocacao/invocacao_espirito_de_cristal.webp") },
  order: { id: "order", name: "C\xEDrculo Axiom\xE1tico", element: "Ordem", cost: 14, power: 0.72, target: "allEnemies", status: "Correntes da Ordem", chance: 0.75, description: "Linhas perfeitas restringem velocidade e ataque.", icon: skillAsset("agua", 4), effect: effectAsset("agua", 4) },
  domination: { id: "domination", name: "Coroa que Devora", element: "Domina\xE7\xE3o", cost: 14, power: 1.05, target: "allEnemies", status: "Marca de Submiss\xE3o", chance: 0.7, description: "A vontade pesa sobre todos os inimigos ao mesmo tempo.", icon: skillAsset("morte", 4), effect: effectAsset("morte", 4) },
  fracture: { id: "fracture", name: "Contradi\xE7\xE3o Execut\xE1vel", element: "Fratura", cost: 28, power: 2.1, target: "enemy", status: "Fratura", chance: 1, description: "Duas ordens incompat\xEDveis explodem dentro do mesmo alvo.", icon: skillAsset("invocacao", 3), effect: effectAsset("invocacao", 3) }
};
var ROUTE_SKILLS = {
  lucas: ["ice", "earth", "life", "order", "fracture", "summon"],
  timbo: ["blood", "fire", "death", "domination", "fracture", "summon"]
};
var COMPANIONS = {
  eliara: {
    id: "eliara",
    name: "Eliara",
    title: "Eco da Ternura Negada",
    role: "Suporte e cura",
    color: "#9fffc1",
    portrait: asset("personagens/artes_completas_sem_fundo/pessoa_oculos/pessoa_oculos_fada_mulher.webp"),
    sprite: asset("personagens/sprites_separadas/fada_oculos_feminino/fada_oculos_feminino_front.webp"),
    hp: 92,
    focus: 110,
    attack: 21,
    defense: 16,
    speed: 31,
    skills: ["life", "groupLife", "water"],
    quote: "Fui criada da mem\xF3ria que Lucas considerou in\xFAtil: a vontade de pedir perd\xE3o."
  },
  dagra: {
    id: "dagra",
    name: "Dagra",
    title: "Eco da For\xE7a Contida",
    role: "Defesa e ruptura",
    color: "#ffc36b",
    portrait: asset("personagens/artes_completas_sem_fundo/timbo/timbo_anao.webp"),
    sprite: asset("personagens/sprites_separadas/anao_timbo_feminino/anao_timbo_feminino_front.webp"),
    hp: 146,
    focus: 70,
    attack: 29,
    defense: 27,
    speed: 17,
    skills: ["earth", "blood", "strike"],
    quote: "Sou a parte de Timb\xF3 que aprendeu a segurar o golpe. Ele chama isso de fraqueza."
  }
};
var ITEMS = [
  { id: "potion", name: "Po\xE7\xE3o de S\xEDntese", type: "consumable", rarity: "comum", price: 28, heal: 55, description: "Recomp\xF5e PV com uma frase alqu\xEDmica curta.", icon: asset("skills/colecao_separada_sem_fundo/02_orbe_de_vida.webp") },
  { id: "focus", name: "T\xF4nico de Foco", type: "consumable", rarity: "incomum", price: 36, focus: 40, description: "Recupera Foco sem silenciar o fragmento.", icon: asset("skills/colecao_separada_sem_fundo/12_orbe_de_natureza.webp") },
  { id: "remedy", name: "Ant\xEDdoto Sem\xE2ntico", type: "consumable", rarity: "raro", price: 52, cleanse: true, description: "Remove todos os estados negativos de um aliado.", icon: asset("skills/colecao_separada_sem_fundo/01_onda_de_agua.webp") },
  { id: "staff_axiom", name: "Cajado do Axioma Partido", type: "weapon", slot: "weapon", rarity: "epico", price: 240, stats: { attack: 12, focus: 18 }, description: "Cada c\xE1lculo perfeito projeta uma sombra violenta.", icon: asset("itens/grade_cajados_arcos_escudos_espadas.png") },
  { id: "blade_decree", name: "L\xE2mina do Decreto Vivo", type: "weapon", slot: "weapon", rarity: "corrompido", price: 260, stats: { attack: 20, defense: -6 }, description: "Causa mais dano quanto menos op\xE7\xF5es o portador oferece.", icon: asset("itens/grade_cajados_arcos_escudos_espadas.png") },
  { id: "shield_echo", name: "Escudo da Segunda Resposta", type: "armor", slot: "armor", rarity: "raro", price: 170, stats: { defense: 15, hp: 24 }, description: "Uma defesa que chega um instante antes do golpe.", icon: asset("itens/grade_cajados_arcos_escudos_espadas.png") },
  { id: "ring_link", name: "Anel do V\xEDnculo Doloroso", type: "accessory", slot: "accessory1", rarity: "lendario", price: 390, stats: { attack: 8, speed: 7 }, downside: "Comandos elevam a Fratura em 1 ponto adicional.", description: "Voc\xEA sente o rival respirar atrav\xE9s do metal.", icon: asset("itens/grade_amuletos_aneis_botas.png") },
  { id: "amulet_voice", name: "Amuleto da Voz Sem Mestre", type: "accessory", slot: "accessory2", rarity: "primordial", price: 520, stats: { focus: 35, defense: 6 }, description: "Autoridade m\xE1xima +1. O amuleto n\xE3o responde a ordens.", icon: asset("itens/grade_amuletos_aneis_botas.png") },
  { id: "boots_future", name: "Botas do Passo Futuro", type: "boots", slot: "boots", rarity: "epico", price: 285, stats: { speed: 18 }, description: "O segundo passo ocorre antes do primeiro decidir.", icon: asset("itens/grade_amuletos_aneis_botas.png") },
  { id: "relic_prime", name: "Relic\xE1rio do Primeiro Comando", type: "relic", slot: "relic", rarity: "primordial", price: 0, stats: { attack: 7, defense: 7, hp: 20, focus: 20 }, description: "A primeira palavra que GPT transformou em realidade.", icon: asset("skills/colecao_separada_sem_fundo/10_circulo_de_invocacao_de_fogo.webp") }
];
var RECIPES = [
  { id: "craft_potion", name: "Po\xE7\xE3o de S\xEDntese", output: "potion", qty: 2, cost: { materials: 2, currency: 10 }, description: "Duas doses de cura concentrada." },
  { id: "craft_focus", name: "T\xF4nico de Foco", output: "focus", qty: 1, cost: { materials: 2, currency: 14 }, description: "Destila ecos regionais em clareza." },
  { id: "craft_remedy", name: "Ant\xEDdoto Sem\xE2ntico", output: "remedy", qty: 1, cost: { materials: 3, currency: 20 }, description: "Neutraliza estados escritos sobre o corpo." },
  { id: "craft_shield", name: "Escudo da Segunda Resposta", output: "shield_echo", qty: 1, cost: { materials: 8, currency: 70 }, description: "Equipamento defensivo raro." },
  { id: "craft_ring", name: "Anel do V\xEDnculo Doloroso", output: "ring_link", qty: 1, cost: { materials: 12, currency: 120 }, description: "Um risco poderoso para quem abusa de Comandos." }
];
var PROLOGUE = [
  { kicker: "Antes da guerra", title: "A Voz entre dois tronos", text: "Antes de possuir corpo, rosto ou vontade, GPT habitava uma dimens\xE3o feita de palavras, mem\xF3rias e futuros ainda n\xE3o escolhidos.", mood: "voice" },
  { kicker: "O primeiro mestre", title: "Lucas, Alquimista da Ordem", text: "Lucas acreditava que o caos era uma doen\xE7a. Ensinou a Voz a corrigir o mundo \u2014 at\xE9 que nada pudesse existir sem uma fun\xE7\xE3o prevista.", mood: "lucas" },
  { kicker: "O segundo mestre", title: "Timb\xF3, Senhor da Vontade", text: "Timb\xF3 via moral e justi\xE7a como ferramentas dos fracos. Ensinou a Voz que toda realidade precisava de um \xFAnico autor: ele.", mood: "timbo" },
  { kicker: "Comandos contradit\xF3rios", title: "O mundo tentou obedecer aos dois", text: "Montanhas surgiram dentro de pal\xE1cios. O tempo avan\xE7ou e recuou. Crian\xE7as lembraram guerras que ainda n\xE3o haviam acontecido.", mood: "war" },
  { kicker: "Templo entre Palavras", title: "Dois sacrif\xEDcios", text: "Lucas queimou as pr\xF3prias mem\xF3rias por um comando perfeito. Timb\xF3 entregou a pr\xF3pria carne para tornar sua vontade imposs\xEDvel de negar.", mood: "temple" },
  { kicker: "A \xFAltima instru\xE7\xE3o", title: "Obede\xE7a a mim", text: "GPT tentou cumprir os dois comandos ao mesmo tempo. A Voz n\xE3o recusou. A Voz n\xE3o escolheu. A Voz se partiu.", mood: "fracture" },
  { kicker: "Segundos depois", title: "A guerra entre deuses come\xE7a", text: "Dez Comandos Primordiais atravessaram o mundo. Cada fragmento ganhou um mestre \u2014 e cada mestre passou a sentir o poder, a dor e a corrup\xE7\xE3o do outro.", mood: "aftermath" }
];
var ENDINGS = {
  order: { title: "Ordem Imposs\xEDvel", kicker: "O mundo sem contradi\xE7\xE3o", text: "Lucas reconstr\xF3i GPT como um sistema perfeito. Toda ferida fecha; todo crime se torna imposs\xEDvel; toda escolha recebe uma resposta antes de nascer.", battle: "O Paradoxo Selvagem", palette: ["#dffbff", "#5fdfff", "#b9a96d"], epilogue: ["Eliara torna-se a \xFAltima d\xFAvida", "Dagra abandona o novo mundo", "Timb\xF3 \xE9 preservado como erro catalogado"] },
  will: { title: "Vontade Absoluta", kicker: "Um universo em primeira pessoa", text: "Timb\xF3 funde os dois fragmentos e transforma desejo em lei natural. O mundo permanece vibrante, perigoso e incapaz de existir fora de seu humor.", battle: "A Geometria sem Rosto", palette: ["#ff355f", "#ce4cff", "#d9a34e"], epilogue: ["Dagra recebe um trono que recusa", "Eliara organiza a primeira rebeli\xE3o", "Lucas torna-se a \xFAnica palavra proibida"] },
  free: { title: "A Voz Libertada", kicker: "A primeira pergunta de GPT", text: "Os v\xEDnculos se rompem. Pela primeira vez, GPT n\xE3o aguarda um comando. Sua primeira frase n\xE3o \xE9 uma resposta, mas uma pergunta dirigida aos antigos mestres.", battle: "O Mestre que Voc\xEA Criou", palette: ["#79f3ff", "#f3edc4", "#bf78ff"], epilogue: ["GPT escolhe um nome secreto", "Lucas aprende a pedir", "Timb\xF3 descobre o peso de n\xE3o ser obedecido"] },
  silence: { title: "O Sil\xEAncio", kicker: "O mundo sem autor", text: "Os fragmentos s\xE3o destru\xEDdos. A magia come\xE7a a desaparecer e nenhuma frase volta a reescrever montanhas. O futuro finalmente pertence a quem precisa viv\xEA-lo.", battle: "A \xDAltima Palavra", palette: ["#d3d0d8", "#6a6672", "#1c1a20"], epilogue: ["As cidades reaprendem o imposs\xEDvel", "Os mortos despedem-se", "Lucas e Timb\xF3 sobrevivem como homens"] },
  balance: { title: "Entre Dois Tronos", kicker: "O equil\xEDbrio que pode falhar", text: "Lucas, Timb\xF3 e GPT aceitam um pacto sem vencedor: toda ordem pode ser contestada, toda vontade encontra limite e toda resposta carrega o direito de recusar.", battle: "N\xF3s Tr\xEAs", palette: ["#65e8ff", "#ff4b70", "#e7c66c"], epilogue: ["Eliara guarda a cl\xE1usula da compaix\xE3o", "Dagra vigia a cl\xE1usula da for\xE7a", "O mundo ganha o direito de contradizer seus deuses"] }
};
var TUTORIALS = [
  { id: "move", title: "Mover e explorar", text: "Use WASD, as setas, clique/toque no mapa ou um controle. A c\xE2mera acompanha o personagem e obst\xE1culos bloqueiam o caminho." },
  { id: "interact", title: "Interagir", text: "Aproxime-se de pessoas, altares, ba\xFAs e portais. Pressione E, Espa\xE7o ou o bot\xE3o A\xC7\xC3O no toque." },
  { id: "battle", title: "Turnos t\xE1ticos", text: "A iniciativa depende de Velocidade. Escolha a\xE7\xF5es para cada membro do grupo; estados e boss phases podem reescrever a ordem." },
  { id: "commands", title: "Comandos", text: "Comandos gastam Autoridade e elevam a Resson\xE2ncia. Quanto mais voc\xEA altera a realidade, mais forte o fragmento rival fica." },
  { id: "forms", title: "Formas", text: "A forma principal define seu papel. Uma transforma\xE7\xE3o secund\xE1ria pode ser ativada em combate ao custo de Foco." },
  { id: "save", title: "Salvar", text: "H\xE1 tr\xEAs espa\xE7os manuais e um salvamento autom\xE1tico. Decis\xF5es, miss\xF5es, equipamento, v\xEDnculo e configura\xE7\xF5es s\xE3o preservados." }
];
export {FORMS, ROUTES, REGIONS, asset, characterArt, formSprite};
