const StudentAccess=(()=>{
 const vaultKey='orbital-student-locks-v1',encoder=new TextEncoder(),decoder=new TextDecoder();
 const publicDer='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAl9TxHXMAA/yAxAbQLgerrgmkQYlSPgXw/uhxzl5XeNqnp7MU2KUFQtdKp3uEw12wn9GZMKyJNUw8S8X5RGLwXRkxxjP2Sx5FKq58SnbOglsHlgzZbmsPpHijv+AtEGgE3D7Z0VheC2z3+/m47+tGSEVJ3EmUX80CRfdItEegBs0NR/xJhTBE9UQLtZOu8/pTY82qUJHv154Wjy06tihPUuxC92/LWc24Nv4yNXyX2uZJ1KwVPH0QzI0/L17a+bNFPrAyDfdJCHGr3ZxDxel5dAwpkEFTtPItHn14VCa5kPqqbjeRIvdc4OwKYxxMAYefc0Aigx1OJ8Jo03CnVAtVoQIDAQAB',privateEncrypted='7J9NOEuiXP4aWIr3/PTdEDmY2lAZYxHVdu3Jjr5PE2DyxtmOUFZxH2RKBiDbH1Ei2Mv+5fGlokdFN5hK3wNHA55qURs/3QjH9KNgJKycJLJ3c7qnO9QNB7irTex2KyGg9vZHs3btNoo7aqQsmM4K59RLCQyVBkG7rh4byKV8W/pfBaZfJ1T8etuMiLZOmowMwedwMbcwxd9YcGmOOYLaDRCi/ma4/JHIf1g2gcmW2DlOO4Jnaq9BNZRG/iMdSfrlcFz2uRFutzakMOM9ZPj23QkIBZNWEDOpUrTzDrQX9HXMQtSRQJRXBhMyd5JbCf0b7xS+V4WXb9BBgq/vZgj25Q7KhlK7le2wvVfhPCTAy8mWyLD7+s/g93GjfNi0EHyMoJ0GY1B6E1/z8xJl+d29xfYsC8V7xwisG6GZeHYrQcRi4AiriALTezh4c4u0CvIZrmZuunnYDyaArBXblUm3LX1wq1l94E6vQuPnlXyV00/j+ReKFuapLfLH2zYOr51QOJYLgvl2JW+WJyAzOZDvZBbOqFUmTzbEAqYPd2/ge7zINTZCkr1DflfiV8olEA31wMhV1U39jdZyc7INyLVmqwYnxhM7x9Xt5RT/vTbOYc0arwFe9YSgzaIAlA96hGCUYKopZvbUX08c8NTrWVgGQcHfL81WdvLGW7x5yle17QWv7c8DcvBexgBR8PVCa0gZdlaEpCrwu/lS2WWqp/ODpHp4dzDY9WVcribcXM57lZBSrCG3BJmkm5QqBHrmXdG8NDvhSyMihCrVOfTC/iBX8SsrZ34NBuzqgmsGWAB9MsEIrFJFwx9g7Y8MBvtnH6Lr8uwn80KXDfUhvlRhwZs4HGkxgu1oGc0Mb5fe+BAP8wi55Ct6XT0uj6KzNACbYmpqaRP86Yf0oUc2qc1ZTe9ezBNY0BLVq4DOFI6+KeNPycaQe9AfrdnkjasZqEkaYW+xYL3kSjYGcw3yPRR3fP6ZZ5rQZy7dx1XBAn0/EfwASVMI6abaeyKRPuDp3ebx+9g+EPOUq5TFmoU/8J+YHd7t1Mff7/pPcFubtXqcW5yr4ffMKWSr0IpnedtahpE/CzoM8pK5vSp//4v9LYaYeYdfGvwhWzdXqdv7w6Tr0reI+iJelB6s2SxF3TVvRSzI7H4I/UlEkN1D4vCqQ2wEl/TTT81QUg9dX1a7Gs3JbtYzKAhET7JdD38a64YYXL0T+z6B5al4cRfLFuBnlvPJsTn21uLP6oDBt1t02K/NjABFXbJSVmqW9isen5KkMMK8A1ejiEYMg5OKv1B4s00l5YLchGwz5ywZ1dt+SXcgHy7Xr+jlFLQ7DaJNaXEbKzbz5bU0aLKnHHUbV6/IHHfEC6jT8PYLyhHKAG9Zp306liOSAwsC92BqZA4sbyf5TvXGiUMQYvYyYfd2/Y3q0GR8HnDk8PfmGeWaAP3//kLchXaf5Z9n2fHKCv4WuHK6x5FPWoqY1nlEEzcw5UQLKuXJdV9U225ZF2gDVDA5o1S6R8+obAHE6GmBMcgl8xuuV+EwktbEPqXTW6qKGCkigH0h7aZHVXd36+tCIGzAWJ31xCVSZbz9QVH9+Lmgl2W3B8MrrykrNH0Sb4U8ITYp66JqmXLlERNZAaSubW87wciKYQfa83jY',privateSalt='Q877pcWcrypKbBUGQ7H9kw==',privateIv='S3gd+vAWiAmfoYyF';
 const b64=bytes=>{let s='';for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s)};
 const from64=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
 const random=n=>{const bytes=new Uint8Array(n);crypto.getRandomValues(bytes);return bytes};
 const available=()=>!!(globalThis.crypto?.subtle&&globalThis.crypto?.getRandomValues);
 const requireCrypto=()=>{if(!available())throw Error('Seu navegador não oferece criptografia. Abra o jogo num navegador atualizado ou em HTTPS.')};
 function read(){try{const obj=JSON.parse(localStorage.getItem(vaultKey)||'{}');return obj&&typeof obj==='object'&&!Array.isArray(obj)?obj:{}}catch{throw Error('Não foi possível abrir o registro de senhas. O acesso está bloqueado para proteger os perfis.')}}
 function write(obj){localStorage.setItem(vaultKey,JSON.stringify(obj))}
 function has(id){return !!(id&&read()[id]?.verifier&&read()[id]?.encrypted)}
 const policy=p=>typeof p==='string'&&p.length>=4&&p.length<=64&&!/^\s+$/.test(p);
 async function verifier(password,salt){const base=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']);return b64(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:140000,hash:'SHA-256'},base,256))}
 async function encrypt(password){const publicKey=await crypto.subtle.importKey('spki',from64(publicDer),{name:'RSA-OAEP',hash:'SHA-256'},false,['encrypt']);const aesRaw=random(32),aesKey=await crypto.subtle.importKey('raw',aesRaw,{name:'AES-GCM'},false,['encrypt']),iv=random(12);return {key:b64(await crypto.subtle.encrypt({name:'RSA-OAEP'},publicKey,aesRaw)),iv:b64(iv),data:b64(await crypto.subtle.encrypt({name:'AES-GCM',iv},aesKey,encoder.encode(password)))}}
 async function prepare(password){requireCrypto();if(!policy(password))throw Error('Crie uma senha de 4 a 64 caracteres.');const salt=random(16);return {version:1,salt:b64(salt),verifier:await verifier(password,salt),encrypted:await encrypt(password),updated:Date.now()}}
 function store(id,credentials){if(!id||!credentials?.encrypted||!credentials?.verifier)throw Error('Credenciais inválidas.');const all=read();all[id]=credentials;write(all)}
 async function create(id,password){const credentials=await prepare(password);store(id,credentials)}
 async function verify(id,password){requireCrypto();const record=read()[id];if(!record?.verifier||!record.salt||!record.encrypted)return false;const got=await verifier(String(password),from64(record.salt));const a=from64(got),b=from64(record.verifier);if(a.length!==b.length)return false;let mismatch=0;for(let i=0;i<a.length;i++)mismatch|=a[i]^b[i];return mismatch===0}
 async function teacherKey(password){requireCrypto();const base=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:from64(privateSalt),iterations:210000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt']);const der=await crypto.subtle.decrypt({name:'AES-GCM',iv:from64(privateIv),additionalData:encoder.encode('ORBITAL-student-v1')},key,from64(privateEncrypted));return crypto.subtle.importKey('pkcs8',der,{name:'RSA-OAEP',hash:'SHA-256'},false,['decrypt'])}
 async function reveal(id,teacherPassword){const record=read()[id];if(!record?.encrypted)throw Error('Este perfil ainda não possui senha cadastrada.');const key=await teacherKey(teacherPassword);const envelope=record.encrypted;if(typeof envelope==='string')return decoder.decode(await crypto.subtle.decrypt({name:'RSA-OAEP'},key,from64(envelope)));const aesRaw=await crypto.subtle.decrypt({name:'RSA-OAEP'},key,from64(envelope.key)),aesKey=await crypto.subtle.importKey('raw',aesRaw,{name:'AES-GCM'},false,['decrypt']);return decoder.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:from64(envelope.iv)},aesKey,from64(envelope.data)))}
 return {has,prepare,store,create,verify,reveal,policy,available};
})();
