import { MapEditor } from "./map_editor.js";
import { TOWER_ASSETS } from "./tower_manifest.js";
import { asJavaScriptModule, copyText, downloadText, stableStringify } from "./editor_export.js";

const PREFS_KEY="voz_partida_dev_prefs_v1";
const clone=value=>typeof structuredClone==="function"?structuredClone(value):JSON.parse(JSON.stringify(value));
const number=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,character=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[character]);
const optionList=(entries,value,label="name")=>entries.map(entry=>`<option value="${escapeHtml(entry.id)}" ${entry.id===value?"selected":""}>${escapeHtml(entry[label]||entry.id)}</option>`).join("");

export class DeveloperMode{
  constructor(context){
    this.context=context;this.__vozDevController=true;const params=new URLSearchParams(location.search),host=String(location.hostname||"").toLowerCase(),localAccess=location.protocol==="file:"||["localhost","127.0.0.1","::1"].includes(host),githubPagesAccess=host==="devilsir.github.io";this.accessAllowed=params.get("dev")==="1"||localAccess||githubPagesAccess;this.enabled=false;this.panelOpen=true;this.tab="test";this.snapshot=null;this.snapshotStateRef=null;this.entitySerial=0;this.flags={playerCollision:true,enemyCollision:true,enemyAI:true,invulnerable:false,instantVictory:false,encounterTriggers:true,simulationPaused:false};this.preferences=this.loadPreferences();
    this.editor=new MapEditor({canvas:context.canvas,getState:context.getState,getEngine:context.getEngine,cache:context.cache,regions:context.regions,worldMapOverride:context.worldMapOverride,worldNavigationValue:context.worldNavigationValue,notify:(...args)=>this.context.notify?.(...args),onChange:()=>this.refreshStatus(),onSelection:selection=>this.renderProperties(selection),onValidation:result=>this.renderValidation(result),onMapChanged:()=>this.context.updateHud?.(true),createEntity:(engine,spec,world)=>this.createEntity(engine,spec,world)});
    this.installStyles();this.createInterface();this.bindGlobal();globalThis.__VOZ_DEV__=this;if(params.get("dev")==="1")queueMicrotask(()=>this.enable());
  }
  loadPreferences(){try{return{gridSize:64,overlayOpacity:.48,showPaths:false,...JSON.parse(localStorage.getItem(PREFS_KEY)||"{}")};}catch{return{gridSize:64,overlayOpacity:.48,showPaths:false};}}
  savePreferences(){localStorage.setItem(PREFS_KEY,JSON.stringify({...this.preferences,gridSize:this.editor.gridSize,overlayOpacity:this.editor.overlayOpacity,panelOpen:this.panelOpen,tab:this.tab}));}
  installStyles(){const style=document.createElement("style");style.id="voz-dev-styles";style.textContent=`
    .dev-indicator{position:fixed;right:14px;top:14px;z-index:10020;border:1px solid #ff4d82;background:linear-gradient(135deg,#230915,#0b0711);color:#ffd3df;padding:7px 11px;font:800 11px/1 ui-monospace,monospace;letter-spacing:.14em;box-shadow:0 0 0 1px #000,0 8px 30px #000b;cursor:pointer}.dev-indicator i{display:inline-block;width:7px;height:7px;border-radius:50%;background:#5ffff0;box-shadow:0 0 10px #5ffff0;margin-right:7px}
    .dev-panel{position:fixed;right:14px;top:50px;z-index:10019;width:min(440px,calc(100vw - 28px));height:min(780px,calc(100vh - 66px));display:grid;grid-template-rows:auto auto 1fr auto;background:linear-gradient(180deg,#130b18f5,#08070cf7);border:1px solid #8c3b61;color:#eadde6;box-shadow:0 20px 70px #000d;font:12px/1.35 ui-sans-serif,system-ui,sans-serif;backdrop-filter:blur(14px)}.dev-panel[hidden],.dev-indicator[hidden]{display:none}.dev-panel.collapsed{height:auto}.dev-panel.collapsed .dev-tabs,.dev-panel.collapsed .dev-content,.dev-panel.collapsed .dev-footer{display:none}
    .dev-head{display:flex;align-items:center;gap:8px;padding:10px 12px;border-bottom:1px solid #5a2941;background:#1b0d19}.dev-head strong{font:700 13px Georgia,serif;color:#ffe1b2}.dev-head span{color:#82e9ff;font:10px ui-monospace,monospace}.dev-head button{margin-left:auto}.dev-panel button,.dev-panel select,.dev-panel input,.dev-panel textarea{border:1px solid #57354d;background:#100b13;color:#f3e9ef;border-radius:3px;font:inherit}.dev-panel button{padding:7px 9px;cursor:pointer}.dev-panel button:hover,.dev-panel button.active{border-color:#72e9ff;color:#fff;background:#281127}.dev-panel button.danger{border-color:#9d3958;color:#ff9cb8}.dev-panel button:disabled{opacity:.38;cursor:not-allowed}.dev-panel input,.dev-panel select{padding:7px;min-width:0}.dev-panel input[type=checkbox]{accent-color:#ff4f86}.dev-panel input[type=range]{padding:0}.dev-panel textarea{width:100%;min-height:180px;padding:9px;resize:vertical;font:10px/1.4 ui-monospace,monospace}
    .dev-tabs{display:flex;overflow:auto;border-bottom:1px solid #4e263c;background:#0c0910}.dev-tabs button{border:0;border-radius:0;border-right:1px solid #3e2232;padding:9px 10px;white-space:nowrap}.dev-tabs button.active{box-shadow:inset 0 -2px #57dcf7}.dev-content{overflow:auto;padding:12px}.dev-tab[hidden]{display:none}.dev-section{border:1px solid #3c2838;background:#0d0a10;margin-bottom:10px;padding:10px}.dev-section h3{margin:0 0 8px;color:#ffd58d;font:700 13px Georgia,serif}.dev-section p{margin:4px 0 9px;color:#bdaeb9}.dev-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.dev-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.dev-field{display:grid;gap:4px}.dev-field label,.dev-label{font:9px ui-monospace,monospace;color:#bfa8b8;text-transform:uppercase;letter-spacing:.08em}.dev-row{display:flex;gap:6px;flex-wrap:wrap;align-items:center}.dev-row>*{flex:1 1 auto}.dev-flags label{display:flex;align-items:center;gap:6px;padding:6px;border:1px solid #382534;background:#0a080d}.dev-flags label input{min-width:auto}.dev-footer{padding:8px 11px;border-top:1px solid #48293b;display:flex;justify-content:space-between;color:#9bbdc4;font:9px ui-monospace,monospace}.dev-asset-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;max-height:330px;overflow:auto}.dev-asset{padding:5px!important;display:grid;gap:4px;text-align:left}.dev-asset img{width:100%;aspect-ratio:1;object-fit:contain;background:#07060a;image-rendering:pixelated}.dev-asset span{font-size:8px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dev-status.good{color:#6affbf}.dev-status.bad{color:#ff7597}.dev-properties{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.dev-properties .wide{grid-column:1/-1}.dev-validation{white-space:pre-wrap;font:10px/1.45 ui-monospace,monospace;max-height:320px;overflow:auto}.dev-tool-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.dev-hint{color:#8ca4ae;font:9px ui-monospace,monospace}.dev-path-legend{display:flex;gap:12px;align-items:center;margin-top:8px;color:#d8cbd3;font:9px ui-monospace,monospace}.dev-path-legend span{display:flex;align-items:center;gap:5px}.dev-path-legend i{display:inline-block;width:12px;height:12px;border:1px solid #ffffff55}.dev-path-legend .path{background:#26eb68}.dev-path-legend .blocked{background:#ff304e}.dev-map-overlay{image-rendering:pixelated}.dev-toast{position:fixed;left:50%;bottom:20px;z-index:10030;transform:translateX(-50%);background:#100a12eF;border:1px solid #63e8ff;color:#fff;padding:10px 14px;box-shadow:0 12px 35px #000c;pointer-events:none}
    @media(max-width:700px){.dev-panel{right:4px;top:42px;width:calc(100vw - 8px);height:calc(100vh - 46px)}.dev-indicator{right:4px;top:4px}.dev-grid.three{grid-template-columns:repeat(2,minmax(0,1fr))}.dev-asset-grid{grid-template-columns:repeat(3,1fr)}}
  `;document.head.appendChild(style);}
  createInterface(){this.indicator=document.createElement("button");this.indicator.className="dev-indicator";this.indicator.hidden=true;this.indicator.innerHTML="<i></i>DEV MODE";document.body.appendChild(this.indicator);this.panel=document.createElement("aside");this.panel.className="dev-panel";this.panel.hidden=true;this.panel.innerHTML=this.panelTemplate();document.body.appendChild(this.panel);this.indicator.addEventListener("click",()=>{this.panelOpen=!this.panelOpen;this.panel.hidden=!this.panelOpen;this.savePreferences();});this.panel.addEventListener("click",event=>this.handleClick(event));this.panel.addEventListener("input",event=>this.handleInput(event));this.panel.addEventListener("change",event=>this.handleChange(event));this.populateStatic();}
  panelTemplate(){return`<header class="dev-head"><div><strong>Console da Voz</strong><br><span data-dev-engine>MOTOR —</span></div><button data-dev-collapse title="Recolher painel (F2)">—</button><button class="danger" data-dev-disable title="Desativar modo dev">×</button></header>
    <nav class="dev-tabs">${[["test","TESTE"],["map","MAPA"],["assets","ASSETS"],["entities","ENTIDADES"],["validation","VALIDAÇÃO"],["export","EXPORTAR"]].map(([id,label])=>`<button data-dev-tab="${id}" class="${id===this.tab?"active":""}">${label}</button>`).join("")}</nav>
    <div class="dev-content">
      <section class="dev-tab" data-tab="test">${this.testTemplate()}</section>
      <section class="dev-tab" data-tab="map" hidden>${this.mapTemplate()}</section>
      <section class="dev-tab" data-tab="assets" hidden>${this.assetsTemplate()}</section>
      <section class="dev-tab" data-tab="entities" hidden>${this.entitiesTemplate()}</section>
      <section class="dev-tab" data-tab="validation" hidden>${this.validationTemplate()}</section>
      <section class="dev-tab" data-tab="export" hidden>${this.exportTemplate()}</section>
    </div><footer class="dev-footer"><span data-dev-coordinates>X — / Y —</span><span>CTRL+SHIFT+D · F2 · F7 PATH · F8</span></footer>`;}
  testTemplate(){return`<div class="dev-section"><h3>Acesso temporário</h3><p>Os desbloqueios abaixo vivem apenas nesta sessão DEV e nunca são gravados no save normal.</p><div class="dev-row"><button data-dev-unlock>Reaplicar tudo</button><button data-dev-heal>Curar grupo</button><button data-dev-focus>Restaurar foco</button></div></div>
    <div class="dev-section"><h3>Região e coordenadas</h3><div class="dev-grid"><div class="dev-field"><label>Região</label><select data-dev-region></select></div><button data-dev-teleport-region>Teleportar</button><div class="dev-field"><label>X</label><input data-dev-x type="number" step="1"></div><div class="dev-field"><label>Y</label><input data-dev-y type="number" step="1"></div></div><div class="dev-row" style="margin-top:7px"><button data-dev-teleport-xy>Ir para X/Y</button><button data-dev-copy-coords>Copiar coordenadas</button></div></div>
    <div class="dev-section"><h3>Forma e aparência</h3><div class="dev-grid three"><div class="dev-field"><label>Rota</label><select data-dev-route><option value="lucas">Lucas</option><option value="timbo">Timbó</option></select></div><div class="dev-field"><label>Variante</label><select data-dev-variant><option value="masculino">Masculina</option><option value="feminino">Feminina</option></select></div><div class="dev-field"><label>Forma</label><select data-dev-form></select></div></div><div class="dev-row" style="margin-top:7px"><button data-dev-apply-visual>Aplicar e pré-carregar</button><button data-dev-sprite-test>Testar matriz completa</button></div><div data-dev-sprite-result class="dev-hint"></div></div>
    <div class="dev-section"><h3>Combate</h3><div class="dev-grid"><div class="dev-field"><label>Encontro</label><select data-dev-encounter><option value="normal">Normal</option><option value="miniboss">Miniboss</option><option value="boss1">Boss 1</option><option value="boss2">Boss 2</option></select></div><button data-dev-start-battle>Iniciar batalha</button><div class="dev-field"><label>Final</label><select data-dev-ending><option value="order">Ordem</option><option value="will">Vontade</option><option value="free">Liberdade</option><option value="silence">Silêncio</option><option value="balance">Equilíbrio</option></select></div><button data-dev-final-battle>Batalha final</button></div><div class="dev-row" style="margin-top:7px"><button data-dev-win>Vitória instantânea</button><button data-dev-reset-encounter>Reiniciar encontro</button></div></div>
    <div class="dev-section"><h3>Torre da Carne</h3><div class="dev-grid three"><div class="dev-field"><label>Run seed</label><input data-dev-seed value="DEV-VOZ-PARTIDA"></div><div class="dev-field"><label>Floor seed exato</label><input data-dev-floor-seed type="number" min="0" step="1" placeholder="Automático"></div><div class="dev-field"><label>Andar</label><input data-dev-floor type="number" min="1" value="1"></div><div class="dev-field"><label>Dificuldade</label><input data-dev-difficulty type="number" min=".5" max="8" step=".1" value="1"></div><div class="dev-field"><label>Família</label><select data-dev-family><option value="">Automática</option></select></div><div class="dev-field"><label>Híbrida</label><select data-dev-hybrid><option value="">Automática</option></select></div><div class="dev-field"><label>Gramática</label><select data-dev-grammar><option value="">Automática</option></select></div><div class="dev-field"><label>Mutação</label><select data-dev-mutation><option value="">Automática</option></select></div></div><div class="dev-row" style="margin-top:7px"><button data-dev-enter-tower>Entrar no andar</button><button data-dev-regenerate>Regenerar</button><button data-dev-reset-map>Resetar mapa</button></div></div>
    <div class="dev-section"><h3>Recursos</h3><div class="dev-grid three"><div class="dev-field"><label>EXP</label><input data-dev-xp type="number" value="1000"></div><button data-dev-add-xp>Adicionar</button><div class="dev-field"><label>Nível</label><input data-dev-level type="number" min="1" value="20"></div><button data-dev-set-level>Definir</button><div class="dev-field"><label>Ecos</label><input data-dev-currency type="number" value="5000"></div><button data-dev-add-currency>Adicionar</button><div class="dev-field"><label>Carne</label><input data-dev-tower-currency type="number" value="500"></div><button data-dev-add-tower-currency>Adicionar</button></div></div>
    <div class="dev-section dev-flags"><h3>Simulação</h3><div class="dev-grid"><label><input type="checkbox" data-dev-flag="playerCollision" checked> Colisão jogador</label><label><input type="checkbox" data-dev-flag="enemyCollision" checked> Colisão inimigos</label><label><input type="checkbox" data-dev-flag="enemyAI" checked> IA inimiga</label><label><input type="checkbox" data-dev-flag="encounterTriggers" checked> Gatilhos</label><label><input type="checkbox" data-dev-flag="invulnerable"> Invulnerável</label><label><input type="checkbox" data-dev-flag="instantVictory"> Vitória imediata</label></div><div class="dev-row" style="margin-top:7px"><button data-dev-pause-sim>Pausar/continuar</button><button data-dev-step>Avançar 1 frame</button></div></div>`;}
  mapTemplate(){const tools=[["select","Selecionar"],["move","Mover"],["brush","Pincel"],["rectangle","Retângulo"],["line","Linha"],["fill","Preencher"],["eraser","Restaurar"],["eyedropper","Conta-gotas"]];return`<div class="dev-section"><h3>Visualização de colisão</h3><div class="dev-flags"><label><input data-editor-show-paths type="checkbox"> Mostrar PATH e BLOCK PATH durante o jogo</label></div><div class="dev-path-legend"><span><i class="path"></i> VERDE = PATH</span><span><i class="blocked"></i> VERMELHO = BLOCK PATH</span></div><p class="dev-hint">A visualização é apenas um overlay DEV: não pinta nem altera a arte do mapa. Atalho: F7.</p></div><div class="dev-section"><h3>Editor sobre o mapa real</h3><div class="dev-grid"><div class="dev-field"><label>Camada</label><select data-editor-layer><option value="navigation">Navegação</option><option value="scenery">Cenário</option><option value="entity">Entidades</option></select></div><div class="dev-field"><label>Valor</label><select data-editor-nav><option value="walkable">Caminhável</option><option value="path">Path</option><option value="blocked">Block path</option><option value="hazard">Perigo</option><option value="void">Vazio</option><option value="bridge">Ponte</option><option value="restore">Original</option></select></div></div><div class="dev-tool-grid" style="margin-top:8px">${tools.map(([id,label])=>`<button data-editor-tool="${id}" title="${label}">${label}</button>`).join("")}</div></div>
    <div class="dev-section"><h3>Precisão</h3><div class="dev-grid three"><div class="dev-field"><label>Pincel</label><input data-editor-brush type="number" min="1" max="9" value="1"></div><div class="dev-field"><label>Grade mundo</label><input data-editor-grid type="number" min="16" max="128" step="8" value="64"></div><div class="dev-field"><label>Overlay</label><input data-editor-opacity type="range" min=".1" max=".85" step=".05" value=".48"></div></div><div class="dev-flags dev-grid" style="margin-top:8px"><label><input data-editor-snap type="checkbox" checked> Snap na grade</label><label><input data-editor-invalid type="checkbox"> Permitir layout inválido</label></div></div>
    <div class="dev-section"><h3>Histórico e rascunho</h3><div class="dev-row"><button data-editor-test>Testar movimento</button><button data-editor-undo>Desfazer</button><button data-editor-redo>Refazer</button><button data-editor-save-draft>Salvar rascunho</button><button data-editor-load-draft>Carregar</button><button data-editor-delete-draft>Apagar</button><button class="danger" data-editor-reset>Restaurar original</button></div></div><div class="dev-section"><h3>Objeto selecionado</h3><div data-editor-properties><p>Nenhum objeto selecionado.</p></div></div>`;}
  assetsTemplate(){return`<div class="dev-section"><h3>Browser de tilesets e doodads</h3><div class="dev-grid"><input data-asset-search placeholder="Buscar nome ou grupo"><select data-asset-region><option value="">Todas as regiões</option></select><select data-asset-category><option value="">Todas as categorias</option></select><select data-asset-role><option value="">Todos os papéis</option></select><select data-asset-source><option value="">Todas as fontes</option></select><select data-asset-composition><option value="">Todas as composições</option></select><select data-asset-collision><option value="">Toda colisão</option></select><select data-asset-special><option value="">Qualquer tipo</option><option value="structure">Estruturas</option><option value="wall">Paredes</option><option value="bridge">Pontes</option><option value="hazard">Perigos</option><option value="watercraft">Embarcações</option><option value="dock">Docas</option><option value="altar">Altares</option></select></div><p class="dev-hint">Clique numa miniatura e depois no mapa para posicionar. O asset usa sua escala e âncora recomendadas.</p></div><div class="dev-asset-grid" data-asset-grid></div>`;}
  entitiesTemplate(){return`<div class="dev-section"><h3>Inimigos</h3><div class="dev-grid"><select data-entity-region></select><select data-entity-kind><option value="normal">Normal</option><option value="miniboss">Miniboss</option><option value="boss1">Boss 1</option><option value="boss2">Boss 2</option></select></div><div class="dev-field" style="margin-top:7px"><label>Sprite / inimigo</label><select data-entity-id></select></div><button data-entity-place-enemy style="margin-top:7px;width:100%">Posicionar inimigo no mapa</button></div><div class="dev-section"><h3>Entidades utilitárias</h3><div class="dev-tool-grid">${["npc","chest","altar","portal","objective","rest","event","tower"].map(type=>`<button data-entity-place="${type}">${type}</button>`).join("")}</div></div><div class="dev-section"><h3>Propriedades de encontro</h3><p class="dev-hint">Selecione a entidade no mapa para ajustar posição, escala, patrulha, aggro, nível, elite, mutação, recompensa e fuga.</p></div>`;}
  validationTemplate(){return`<div class="dev-section"><h3>Validação ao vivo</h3><div class="dev-row"><button data-dev-validate>Executar validação completa</button></div><pre class="dev-validation" data-dev-validation>Aguardando uma edição.</pre></div>`;}
  exportTemplate(){return`<div class="dev-section"><h3>Exportação determinística</h3><div class="dev-flags"><label><input data-export-full type="checkbox"> Snapshot completo da Torre (debug)</label></div><div class="dev-row" style="margin-top:7px"><button data-export-json>Gerar JSON</button><button data-export-js>Gerar módulo JS</button><button data-export-copy>Copiar</button><button data-export-download>Baixar</button></div><textarea data-export-output spellcheck="false" placeholder="O JSON ou módulo aparecerá aqui."></textarea><div class="dev-row"><button data-import-apply>Importar conteúdo acima</button></div></div><div class="dev-section"><h3>Integração</h3><p>World: copie a entrada para <b>WORLD_MAP_OVERRIDES</b>. Torre: use a chave runSeed + floor + floorSeed em <b>TOWER_FLOOR_OVERRIDES</b>. Deltas são aplicados após a geração procedural.</p></div>`;}
  populateStatic(){const c=this.context,panel=this.panel;panel.querySelector("[data-dev-region]").innerHTML=optionList(c.regions,c.getState()?.regionIndex);panel.querySelector("[data-entity-region]").innerHTML=optionList(c.regions,c.getState()?.regionIndex);panel.querySelector("[data-dev-form]").innerHTML=optionList(c.forms,c.getState()?.activeForm,"label");for(const selector of["[data-dev-family]","[data-dev-hybrid]"])panel.querySelector(selector).insertAdjacentHTML("beforeend",optionList(c.towerFamilies));panel.querySelector("[data-dev-grammar]").insertAdjacentHTML("beforeend",optionList(c.towerGrammars));panel.querySelector("[data-dev-mutation]").insertAdjacentHTML("beforeend",optionList(c.towerMutations));const add=(selector,values)=>panel.querySelector(selector).insertAdjacentHTML("beforeend",[...new Set(values.filter(Boolean))].sort().map(value=>`<option>${escapeHtml(value)}</option>`).join(""));add("[data-asset-region]",TOWER_ASSETS.map(asset=>asset.region));add("[data-asset-category]",TOWER_ASSETS.map(asset=>asset.category));add("[data-asset-role]",TOWER_ASSETS.map(asset=>asset.tileRole));add("[data-asset-source]",TOWER_ASSETS.map(asset=>asset.sourceCategory));add("[data-asset-composition]",TOWER_ASSETS.map(asset=>asset.compositionSet));add("[data-asset-collision]",TOWER_ASSETS.map(asset=>asset.collision));this.refreshEntityIds();this.renderAssets();}
  bindGlobal(){if(globalThis.__VOZ_DEV_KEYDOWN_HANDLER__){window.removeEventListener("keydown",globalThis.__VOZ_DEV_KEYDOWN_HANDLER__);window.removeEventListener("keydown",globalThis.__VOZ_DEV_KEYDOWN_HANDLER__,true);}this.globalKeyHandler=event=>{if(event.code==="F2"){if(!this.accessAllowed)return;event.preventDefault();event.stopImmediatePropagation?.();if(!this.enabled){this.panelOpen=true;this.enable();this.panelOpen=true;this.panel.hidden=false;this.panel.classList.remove("collapsed");this.savePreferences();return;}const shouldOpen=this.panel.hidden||!this.panelOpen||this.panel.classList.contains("collapsed");this.panelOpen=shouldOpen;this.panel.hidden=!shouldOpen;this.panel.classList.remove("collapsed");this.savePreferences();return;}if(event.ctrlKey&&event.shiftKey&&event.code==="KeyD"){if(!this.accessAllowed)return;event.preventDefault();event.stopImmediatePropagation?.();this.toggle();return;}if(!this.enabled)return;if(event.code==="F7"){event.preventDefault();this.setPathPreview(!this.preferences.showPaths,true);}if(event.code==="F8"&&this.context.getState()?.gameMode==="tower"){const engine=this.context.getEngine();if(!engine.debugAllowed){event.preventDefault();engine.debugVisual=!engine.debugVisual;engine.invalidateVisualCaches?.();}}};globalThis.__VOZ_DEV_KEYDOWN_HANDLER__=this.globalKeyHandler;window.addEventListener("keydown",this.globalKeyHandler,true);}
  toggle(){this.enabled?this.disable():this.enable();}
  enable(){if(!this.accessAllowed||this.enabled)return;this.enabled=true;this.indicator.hidden=false;this.panel.hidden=!this.panelOpen;this.captureState();this.applyTemporaryUnlocks();this.refreshAll();this.setPathPreview(Boolean(this.preferences.showPaths));this.context.notify?.("DEV MODE","Estado de teste isolado; saves normais protegidos.","good");}
  disable(){if(!this.enabled)return;this.editor.setNavigationPreview(false);this.editor.setEnabled(false);this.enabled=false;this.indicator.hidden=true;this.panel.hidden=true;if(this.snapshot){const restored=clone(this.snapshot);this.context.setState(restored);this.snapshot=null;this.snapshotStateRef=null;this.context.reloadState?.(restored);}this.context.notify?.("DEV MODE desativado","Progressão normal restaurada.","good");}
  captureState(){const state=this.context.getState();if(!state||state.flags?.draft)return;if(this.snapshotStateRef===state&&this.snapshot)return;this.snapshot=clone(state);this.snapshotStateRef=state;}
  onStateChanged(){if(!this.enabled)return;this.captureState();this.applyTemporaryUnlocks();this.refreshAll();}
  sanitizeState(state){return this.enabled&&this.snapshot?clone(this.snapshot):state;}
  applyTemporaryUnlocks(){const state=this.context.getState();if(!state||state.flags?.draft)return;state.flags.devSession=true;state.discoveredRegions=this.context.regions.map(region=>region.id);state.unlockedForms=this.context.forms.map(form=>form.id);state.learnedSkills=Object.keys(this.context.skills);state.activeParty=["hero",...Object.keys(this.context.companions)];for(const companion of Object.values(state.companions||{})){companion.unlocked=true;companion.hp=companion.maxHp;}for(const item of this.context.items)state.inventory[item.id]=Math.max(20,state.inventory[item.id]||0);for(const region of this.context.regions)state.materials[region.key]=Math.max(99,state.materials[region.key]||0);for(const quest of state.quests||[])if(quest.status==="locked")quest.status="active";state.tower.unlocked=true;state.tower.currency=Math.max(999,state.tower.currency||0);for(const upgrade of this.context.towerPermanentUpgrades)state.tower.permanentUpgrades[upgrade.id]=upgrade.max;this.context.updateHud?.(true);}
  refreshAll(){const state=this.context.getState();if(!state)return;this.panel.querySelector("[data-dev-region]").value=String(state.regionIndex);this.panel.querySelector("[data-entity-region]").value=String(state.regionIndex);this.panel.querySelector("[data-dev-route]").value=state.route;this.panel.querySelector("[data-dev-variant]").value=state.visualVariant;this.panel.querySelector("[data-dev-form]").value=state.activeForm;const floor=this.context.getEngine()?.floor;if(floor)this.panel.querySelector("[data-dev-floor-seed]").placeholder=String(floor.floorSeed);this.editor.gridSize=this.preferences.gridSize||64;this.editor.overlayOpacity=this.preferences.overlayOpacity||.48;const showPaths=this.panel.querySelector("[data-editor-show-paths]");if(showPaths)showPaths.checked=Boolean(this.preferences.showPaths);if(this.enabled)this.editor.setNavigationPreview(Boolean(this.preferences.showPaths));this.refreshStatus();this.renderProperties(this.editor.selected);this.renderValidation(this.editor.validate());}
  refreshStatus(){if(!this.enabled)return;const state=this.context.getState(),engine=this.context.getEngine(),type=state?.gameMode==="tower"?"TORRE":"MUNDO",locationLabel=state?.gameMode==="tower"?`ANDAR ${engine?.floor?.floor||"—"} · SEED ${engine?.floor?.floorSeed||"—"}`:this.context.regions[state?.regionIndex]?.name||"—";this.panel.querySelector("[data-dev-engine]").textContent=`${type} · ${locationLabel}`;const position=state?.gameMode==="tower"?engine?.position:state?.position;if(position)this.panel.querySelector("[data-dev-coordinates]").textContent=`X ${Math.round(position.x)} / Y ${Math.round(position.y)} · CÉLULA ${Math.floor(position.x/64)},${Math.floor(position.y/64)}`;}
  handleClick(event){const button=event.target.closest("button");if(!button)return;const data=button.dataset;if(data.devTab)return this.openTab(data.devTab);if("devCollapse"in data){this.panel.classList.toggle("collapsed");return;}if("devDisable"in data)return this.disable();if("devUnlock"in data)return this.applyTemporaryUnlocks();if("devHeal"in data)return this.heal();if("devFocus"in data)return this.restoreFocus();if("devTeleportRegion"in data)return this.teleportRegion();if("devTeleportXy"in data)return this.teleportXY();if("devCopyCoords"in data)return this.copyCoordinates();if("devApplyVisual"in data)return this.applyVisual();if("devSpriteTest"in data)return this.testCharacterVisuals();if("devStartBattle"in data)return this.startBattle();if("devFinalBattle"in data)return this.startFinalBattle();if("devWin"in data)return this.instantWin();if("devResetEncounter"in data)return this.resetEncounter();if("devEnterTower"in data)return this.enterTower();if("devRegenerate"in data)return this.regenerateTower();if("devResetMap"in data)return this.resetCurrentMap();if("devAddXp"in data)return this.addXp();if("devSetLevel"in data)return this.setLevel();if("devAddCurrency"in data)return this.addCurrency();if("devAddTowerCurrency"in data)return this.addTowerCurrency();if("devPauseSim"in data)return this.toggleSimulation();if("devStep"in data)return this.stepSimulation();if(data.editorTool)return this.setEditorTool(data.editorTool);if("editorTest"in data)return this.toggleEditorTest(button);if("editorUndo"in data)return this.editor.undo();if("editorRedo"in data)return this.editor.redo();if("editorSaveDraft"in data)return this.editor.saveDraft();if("editorLoadDraft"in data)return this.safe(()=>this.editor.loadDraft());if("editorDeleteDraft"in data)return this.editor.deleteDraft();if("editorReset"in data)return this.editor.reset();if(data.assetId)return this.editor.setPlacingAsset(TOWER_ASSETS.find(asset=>asset.id===data.assetId));if("entityPlaceEnemy"in data)return this.placeEnemy();if(data.entityPlace)return this.editor.setPlacingEntity({type:data.entityPlace});if("devValidate"in data)return this.renderValidation(this.editor.validate());if("exportJson"in data)return this.generateExport("json");if("exportJs"in data)return this.generateExport("js");if("exportCopy"in data)return copyText(this.panel.querySelector("[data-export-output]").value);if("exportDownload"in data)return this.downloadExport();if("importApply"in data)return this.importExport();}
  handleInput(event){const input=event.target;if(input.matches("[data-asset-search],[data-asset-region],[data-asset-category],[data-asset-role],[data-asset-source],[data-asset-composition],[data-asset-collision],[data-asset-special]"))this.renderAssets();if(input.matches("[data-editor-opacity]")){this.editor.overlayOpacity=number(input.value,.48);this.preferences.overlayOpacity=this.editor.overlayOpacity;this.savePreferences();}}
  handleChange(event){const input=event.target;if(input.dataset.devFlag){this.flags[input.dataset.devFlag]=input.checked;return;}if(input.matches("[data-editor-show-paths]"))return this.setPathPreview(input.checked,true);if(input.matches("[data-editor-layer]"))this.editor.layer=input.value;if(input.matches("[data-editor-nav]"))this.editor.navigationValue=input.value;if(input.matches("[data-editor-brush]"))this.editor.brushSize=number(input.value,1);if(input.matches("[data-editor-grid]")){this.editor.gridSize=number(input.value,64);this.preferences.gridSize=this.editor.gridSize;this.savePreferences();}if(input.matches("[data-editor-snap]"))this.editor.snap=input.checked;if(input.matches("[data-editor-invalid]"))this.editor.allowInvalid=input.checked;if(input.matches("[data-entity-region],[data-entity-kind]"))this.refreshEntityIds();}
  openTab(id){this.tab=id;this.panel.querySelectorAll("[data-dev-tab]").forEach(button=>button.classList.toggle("active",button.dataset.devTab===id));this.panel.querySelectorAll(".dev-tab").forEach(section=>section.hidden=section.dataset.tab!==id);const editing=id==="map"||id==="assets"||id==="entities";this.editor.setEnabled(editing);if(editing)this.editor.ensureCurrentDraft();else if(!this.flags.simulationPaused)this.context.getEngine()?.resume?.();this.savePreferences();}
  toggleEditorTest(button){const testing=this.editor.overlay.style.pointerEvents!=="none";this.editor.overlay.style.pointerEvents=testing?"none":"auto";button.classList.toggle("active",testing);button.textContent=testing?"Voltar a editar":"Testar movimento";testing?this.context.getEngine()?.resume?.():this.context.getEngine()?.stop?.();}
  setEditorTool(tool){this.editor.tool=tool;this.editor.placingAsset=null;this.editor.placingEntity=null;this.panel.querySelectorAll("[data-editor-tool]").forEach(button=>button.classList.toggle("active",button.dataset.editorTool===tool));}
  setPathPreview(value,notify=false){const visible=Boolean(value);this.preferences.showPaths=visible;const checkbox=this.panel.querySelector("[data-editor-show-paths]");if(checkbox)checkbox.checked=visible;this.editor.setNavigationPreview(this.enabled&&visible);this.savePreferences();if(notify)this.context.notify?.(visible?"Paths visíveis":"Paths ocultos",visible?"Verde = PATH · vermelho = BLOCK PATH.":"O overlay de colisão foi desativado.","good");}
  heal(){const state=this.context.getState(),stats=this.context.getPlayerStats(state);state.hp=stats.hp;for(const member of Object.values(state.companions))member.hp=member.maxHp;this.context.combat?.party?.forEach(actor=>actor.hp=actor.maxHp);this.context.updateHud(true);}
  restoreFocus(){const state=this.context.getState(),stats=this.context.getPlayerStats(state);state.focus=stats.focus;state.authority=state.maxAuthority;this.context.combat?.party?.forEach(actor=>actor.focus=actor.maxFocus);this.context.updateHud(true);}
  async teleportRegion(){const index=number(this.panel.querySelector("[data-dev-region]").value);await this.context.transitionRegion(index);this.editor.ensureCurrentDraft();this.refreshAll();}
  teleportXY(){const x=number(this.panel.querySelector("[data-dev-x]").value),y=number(this.panel.querySelector("[data-dev-y]").value),state=this.context.getState(),engine=this.context.getEngine();if(state.gameMode==="tower"){engine.position={x,y};state.position={x,y};}else state.position={x,y};engine.camera.x=Math.max(0,x-engine.canvas.width/2);engine.camera.y=Math.max(0,y-engine.canvas.height/2);this.refreshStatus();}
  async copyCoordinates(){const state=this.context.getState(),engine=this.context.getEngine(),position=state.gameMode==="tower"?engine.position:state.position;await copyText(stableStringify({engine:state.gameMode,region:state.regionIndex,floor:engine.floor?.floor||null,x:position.x,y:position.y,cellX:Math.floor(position.x/64),cellY:Math.floor(position.y/64)},2));this.context.notify?.("Coordenadas copiadas","Prontas para colar no código.","good");}
  async preloadVisual(route,variant,form){const front=this.context.formSprite(route,form,"front",variant),fallback=this.context.characterArt(route,variant),results=[];for(const direction of["front","back","left","right"]){const exact=this.context.formSprite(route,form,direction,variant),image=await this.context.cache.loadFirst(exact,[front,fallback]);results.push({direction,exact,resolved:this.context.cache.aliases.get(exact)||exact,visible:Boolean(image&&image.naturalWidth&&image.naturalHeight)});}return results;}
  async preloadCurrentVisual(){const state=this.context.getState();return this.preloadVisual(state.route,state.visualVariant,state.activeForm);}
  async applyVisual(){const state=this.context.getState(),route=this.panel.querySelector("[data-dev-route]").value==="timbo"?"timbo":"lucas",variant=this.panel.querySelector("[data-dev-variant]").value==="feminino"?"feminino":"masculino",form=this.panel.querySelector("[data-dev-form]").value,results=await this.preloadVisual(route,variant,form),invalid=results.filter(result=>!result.visible);if(invalid.length){this.panel.querySelector("[data-dev-sprite-result]").textContent=`Troca cancelada: ${invalid.length} direção(ões) sem imagem ou fallback.`;return;}const previousHero=this.context.combat?.party?.find(actor=>actor.hero),previousSprite=previousHero?this.context.combat.actorSprite(previousHero):null;state.route=route;state.visualVariant=variant;state.activeForm=form;if(!state.unlockedForms.includes(state.activeForm))state.unlockedForms.push(state.activeForm);await this.context.refreshCharacterVisuals?.();if(previousHero){previousHero.name=state.route==="timbo"?"Timbó":"Lucas";previousHero.img=results.find(result=>result.direction==="front")?.resolved||this.context.characterArt(state.route,state.visualVariant);previousHero.lastVisibleImg=previousSprite;previousHero.imgFallbacks=[previousSprite,this.context.characterArt(state.route,state.visualVariant)].filter(Boolean);this.context.combat.render?.();}this.context.updateHud(true);this.panel.querySelector("[data-dev-sprite-result]").textContent="Forma carregada nas quatro direções sem transparência.";}
  async testCharacterVisuals(){const matrix=[];for(const route of["lucas","timbo"])for(const variant of["masculino","feminino"])for(const form of this.context.forms){const rows=await this.preloadVisual(route,variant,form.id);matrix.push({route,variant,form:form.id,valid:rows.every(row=>row.visible),rows});}await this.preloadCurrentVisual();await this.context.refreshCharacterVisuals?.();const failures=matrix.filter(entry=>!entry.valid);this.panel.querySelector("[data-dev-sprite-result]").textContent=failures.length?`Falha em ${failures.map(entry=>`${entry.route}/${entry.form}/${entry.variant}`).join(", ")}`:`${matrix.length*4} sprites visíveis (2 rotas × formas × 2 variantes × 4 direções).`;return{valid:!failures.length,matrix};}
  startBattle(){this.context.startWorldBattle(number(this.panel.querySelector("[data-dev-region]").value),this.panel.querySelector("[data-dev-encounter]").value);}
  startFinalBattle(){this.context.startFinalBattle(this.panel.querySelector("[data-dev-ending]").value);}
  instantWin(){const combat=this.context.combat;if(!combat?.battle||combat.battle.ended)return;combat.enemies.forEach(enemy=>enemy.hp=0);combat.checkOutcome();}
  resetEncounter(){const combat=this.context.combat;if(combat?.battleMode==="tower"&&combat.towerConfig)combat.startTowerEncounter(clone(combat.towerConfig));else if(combat?.region)combat.start(combat.region.id,combat.encounterType,combat.battle?.finalEnding);}
  towerInputs(){const value=selector=>this.panel.querySelector(selector).value,floorSeed=value("[data-dev-floor-seed]");return{seed:value("[data-dev-seed]")||"DEV-VOZ-PARTIDA",floor:Math.max(1,Math.floor(number(value("[data-dev-floor]"),1))),difficulty:Math.max(.5,number(value("[data-dev-difficulty]"),1)),overrides:{familyId:value("[data-dev-family]")||null,hybridId:value("[data-dev-hybrid]")||null,grammarId:value("[data-dev-grammar]")||null,mutationId:value("[data-dev-mutation]")||null,floorSeed:floorSeed===""?null:number(floorSeed)>>>0}};}
  async enterTower(){const state=this.context.getState(),input=this.towerInputs();state.tower.unlocked=true;state.tower.activeRun=this.context.createDevTowerRun(input);state.gameMode="world";await this.context.continueTowerRun(true);this.editor.ensureCurrentDraft();this.refreshAll();}
  async regenerateTower(){if(this.context.getState().gameMode!=="tower")return this.enterTower();const run=this.context.getState().tower.activeRun,input=this.towerInputs();Object.assign(run,{seed:input.seed,floor:input.floor,difficulty:input.difficulty,floorSeed:null,playerPosition:null,explored:[],developerOverrides:input.overrides});await this.context.getEngine().enterFloor(run,{announce:true});this.editor.ensureTowerOriginal();this.refreshAll();}
  resetCurrentMap(){if(this.editor.enabled)this.editor.reset();else if(this.context.getState().gameMode==="tower")this.regenerateTower();else this.context.transitionRegion(this.context.getState().regionIndex);}
  addXp(){this.context.addXp(this.context.getState(),number(this.panel.querySelector("[data-dev-xp]").value,1000));this.context.updateHud(true);}
  setLevel(){const state=this.context.getState(),target=Math.max(1,Math.floor(number(this.panel.querySelector("[data-dev-level]").value,1)));while(state.level<target)this.context.addXp(state,state.nextXp);if(state.level>target)state.level=target;this.context.updateHud(true);}
  addCurrency(){this.context.getState().currency+=number(this.panel.querySelector("[data-dev-currency]").value,0);this.context.updateHud(true);}
  addTowerCurrency(){this.context.getState().tower.currency+=number(this.panel.querySelector("[data-dev-tower-currency]").value,0);if(this.context.getState().tower.activeRun)this.context.getState().tower.activeRun.resources.towerCurrency+=number(this.panel.querySelector("[data-dev-tower-currency]").value,0);this.context.updateHud(true);}
  toggleSimulation(){const engine=this.context.getEngine();this.flags.simulationPaused=!this.flags.simulationPaused;this.flags.simulationPaused?engine.stop():engine.resume();}
  stepSimulation(){const engine=this.context.getEngine();engine.update?.(1/60);engine.draw?.();}
  renderAssets(){const value=selector=>this.panel.querySelector(selector)?.value||"",query=value("[data-asset-search]").toLowerCase(),region=value("[data-asset-region]"),category=value("[data-asset-category]"),role=value("[data-asset-role]"),source=value("[data-asset-source]"),composition=value("[data-asset-composition]"),collision=value("[data-asset-collision]"),special=value("[data-asset-special]");const assets=TOWER_ASSETS.filter(asset=>(!query||`${asset.name} ${asset.variantGroup} ${asset.compositionSet} ${asset.sourceCategory}`.toLowerCase().includes(query))&&(!region||asset.region===region)&&(!category||asset.category===category)&&(!role||asset.tileRole===role)&&(!source||asset.sourceCategory===source)&&(!composition||asset.compositionSet===composition)&&(!collision||asset.collision===collision)&&(!special||Boolean(asset[special]))).slice(0,120);this.panel.querySelector("[data-asset-grid]").innerHTML=assets.map(asset=>`<button class="dev-asset" data-asset-id="${asset.id}" title="${escapeHtml(asset.name)} · ${asset.scaleClass} · ${asset.recommendedWorldHeight}px"><img loading="lazy" src="${escapeHtml(asset.path)}"><span>${escapeHtml(asset.name)}</span></button>`).join("")||"<p>Nenhum asset encontrado.</p>";}
  refreshEntityIds(){const region=this.context.regions[number(this.panel.querySelector("[data-entity-region]")?.value,this.context.getState()?.regionIndex||0)],kind=this.panel.querySelector("[data-entity-kind]")?.value||"normal";if(!region)return;const ids=kind==="normal"?region.normal:kind==="miniboss"?[region.miniboss]:kind==="boss1"?[region.bosses[0]]:[region.bosses[1]];this.panel.querySelector("[data-entity-id]").innerHTML=ids.map(id=>`<option value="${id}">${escapeHtml(this.context.normalDisplay[id]||id)}</option>`).join("");}
  placeEnemy(){this.editor.setPlacingEntity({type:"encounter",region:number(this.panel.querySelector("[data-entity-region]").value),kind:this.panel.querySelector("[data-entity-kind]").value,id:this.panel.querySelector("[data-entity-id]").value});}
  async createEntity(engineType,spec,world){const region=this.context.regions[spec.region??this.context.getState().regionIndex],id=`dev-entity-${++this.entitySerial}-${Date.now().toString(36)}`,cellX=Math.floor(world.x/64),cellY=Math.floor(world.y/64);if(spec.type==="encounter"){const enemyId=spec.id||region.normal[0],boss=spec.kind!=="normal",front=this.context.mobSprite(region,enemyId,"front",boss),fallbacks=[front],movement={spawnX:world.x,spawnY:world.y,patrol:true,patrolRadius:24,aggroRadius:290,returnRadius:430,movementSpeed:boss?72:62,facing:"front",flying:false,respawn:false,persistence:"clear-once"};if(engineType==="tower")return{id,type:"encounter",label:`DEV ${this.context.normalDisplay[enemyId]||enemyId}`,x:world.x,y:world.y,cellX,cellY,height:boss?132:86,...movement,encounter:{id,kind:spec.kind||"normal",enemyIds:[enemyId],enemyRegions:[region.id],enemyKinds:[spec.kind||"normal"],level:this.context.getState().level,elite:["miniboss","boss1","boss2"].includes(spec.kind),major:["boss1","boss2"].includes(spec.kind),allowFlee:spec.kind==="normal",reward:{xp:50,currency:25,towerCurrency:2},title:`Teste: ${this.context.normalDisplay[enemyId]||enemyId}`}};return{id,type:"encounter",encounter:spec.kind||"normal",enemyId,kind:spec.kind||"normal",label:`DEV ${this.context.normalDisplay[enemyId]||enemyId}`,x:world.x,y:world.y,sprite:front,fallbacks,height:boss?132:86,locked:false,defeated:false,...movement};}return{id,type:spec.type,label:`DEV ${spec.type}`,x:world.x,y:world.y,cellX,cellY,objective:spec.type==="objective",persistence:"clear-once"};}
  renderProperties(selection){
    const root=this.panel.querySelector("[data-editor-properties]");if(!root)return;if(!selection){root.innerHTML="<p>Nenhum objeto selecionado.</p>";return;}
    const value=selection.value,encounter=value.encounter||{},reward=encounter.reward||{},field=(name,label,current=value[name],type="number",step="1")=>`<div class="dev-field"><label>${label}</label><input data-prop="${name}" type="${type}" step="${step}" value="${escapeHtml(current??0)}"></div>`,check=(name,label,current,disabled=false)=>`<label class="dev-field"><span class="dev-label">${label}</span><input data-prop="${name}" type="checkbox" ${current?"checked":""} ${disabled?"disabled":""}></label>`;
    let fields=`${field("x","X")}${field("y","Y")}`;
    if(selection.kind==="prop")fields+=`${field("height","Altura")}${field("scalePercent","Escala %",Math.round((value.height/Math.max(1,value.recommendedWorldHeight||value.height))*100))}${field("anchorOffsetX","Âncora X")}${field("anchorOffsetY","Âncora Y")}${field("sortOffsetY","Sort Y")}${field("collisionOffsetX","Colisão X")}${field("collisionOffsetY","Colisão Y")}${field("footprintW","Colisão L",value.footprint?.[0])}${field("footprintH","Colisão A",value.footprint?.[1])}${field("shadowWidth","Sombra L")}${field("shadowHeight","Sombra A")}${field("shadowOffsetY","Sombra Y")}${field("shadowOpacity","Opacidade",value.shadowOpacity,"number",".01")}${field("rotation","Rotação °",value.rotation||0)}<div class="dev-field"><label>Colisão</label><select data-prop="collision">${["none","traversable","footprint","solid","hazard"].map(option=>`<option ${value.collision===option?"selected":""}>${option}</option>`).join("")}</select></div><div class="dev-field"><label>Camada</label><input data-prop="layer" value="${escapeHtml(value.layer||"")}"></div>${check("shadowEnabled","Sombra",value.shadowEnabled!==false)}${check("mirror","Espelhar",value.mirror,!value.canMirror)}${check("proportionalCollision","Escala proporcional",value.proportionalCollision!==false)}`;
    else if(selection.kind==="entity")fields+=`${field("height","Altura",value.height||86)}${field("spawnX","Spawn X",value.spawnX??value.x)}${field("spawnY","Spawn Y",value.spawnY??value.y)}${field("patrolRadius","Raio patrulha",value.patrolRadius||24)}${field("aggroRadius","Raio aggro",value.aggroRadius||290)}${field("returnRadius","Raio retorno",value.returnRadius||430)}${field("movementSpeed","Velocidade",value.movementSpeed||(encounter.elite?72:62))}<div class="dev-field"><label>Direção</label><select data-prop="facing">${["front","back","left","right"].map(option=>`<option ${value.facing===option?"selected":""}>${option}</option>`).join("")}</select></div>${check("flying","Voador",value.flying)}${check("patrol","Patrulha",value.patrol)}${check("objective","Objetivo",value.objective)}${field("enemyId","Enemy ID",value.enemyId||encounter.enemyIds?.[0]||"","text")}${field("encounterGroup","Grupo",(encounter.enemyIds||[]).join(","),"text")}${field("encounterLevel","Nível",encounter.level||this.context.getState().level)}${field("mutationId","Mutação",encounter.modifier?.id||encounter.mutation?.id||"","text")}${field("rewardXp","Recompensa XP",reward.xp||0)}${field("rewardCurrency","Recompensa Ecos",reward.currency||0)}${field("rewardTowerCurrency","Recompensa Carne",reward.towerCurrency||0)}${check("encounterElite","Elite",encounter.elite)}${check("encounterMajor","Boss principal",encounter.major)}${check("allowFlee","Permitir fuga",encounter.allowFlee!==false)}${check("respawn","Respawn",value.respawn)}${field("persistence","Persistência",value.persistence||"clear-once","text")}`;
    root.innerHTML=`<div class="wide"><b>${escapeHtml(value.id||selection.kind)}</b><br><span class="dev-hint">${selection.kind} · ${escapeHtml(value.path||value.type||"")}</span></div><div class="dev-properties">${fields}<button class="wide" data-prop-apply>Aplicar propriedades</button>${selection.kind==="prop"?'<button class="wide" data-prop-reset-scale>Escala recomendada</button>':''}${selection.kind!=="spawn"?'<button class="wide" data-prop-duplicate>Duplicar selecionado</button><button class="danger wide" data-prop-delete>Excluir selecionado</button>':''}</div>`;
    root.querySelector("[data-prop-apply]").addEventListener("click",()=>{const raw={};root.querySelectorAll("[data-prop]").forEach(input=>raw[input.dataset.prop]=input.type==="checkbox"?input.checked:input.type==="number"?number(input.value):input.value);const properties={...raw};if(selection.kind==="prop"){properties.height=raw.scalePercent&&raw.scalePercent!==100?(value.recommendedWorldHeight||value.height)*raw.scalePercent/100:raw.height;properties.footprint=[raw.footprintW,raw.footprintH];if(!value.canRotate)properties.rotation=0;if(!value.canMirror)properties.mirror=false;delete properties.scalePercent;delete properties.footprintW;delete properties.footprintH;}else if(selection.kind==="entity"){properties.encounter={...encounter,enemyIds:String(raw.encounterGroup||raw.enemyId||"").split(",").map(entry=>entry.trim()).filter(Boolean),level:raw.encounterLevel,elite:raw.encounterElite,major:raw.encounterMajor,allowFlee:raw.allowFlee,reward:{...reward,xp:raw.rewardXp,currency:raw.rewardCurrency,towerCurrency:raw.rewardTowerCurrency}};if(raw.mutationId)properties.encounter.modifier={...(encounter.modifier||encounter.mutation||{}),id:raw.mutationId};for(const key of["encounterGroup","encounterLevel","encounterElite","encounterMajor","allowFlee","mutationId","rewardXp","rewardCurrency","rewardTowerCurrency"])delete properties[key];}this.editor.updateSelected(properties);this.renderProperties(this.editor.selected);});
    root.querySelector("[data-prop-reset-scale]")?.addEventListener("click",()=>{this.editor.resetSelectedScale();this.renderProperties(this.editor.selected);});root.querySelector("[data-prop-duplicate]")?.addEventListener("click",()=>this.editor.duplicateSelected());root.querySelector("[data-prop-delete]")?.addEventListener("click",()=>this.editor.deleteSelected());
  }
  renderValidation(result){const node=this.panel.querySelector("[data-dev-validation]");if(!node||!result)return;node.className=`dev-validation dev-status ${result.valid?"good":"bad"}`;node.textContent=stableStringify({valid:result.valid,errors:result.errors||[],counts:result.counts||null},2);}
  generateExport(mode){const payload=this.editor.exportPayload(this.panel.querySelector("[data-export-full]").checked),text=mode==="js"?asJavaScriptModule(payload,payload.kind.includes("tower")?"TOWER_EDITOR_OVERRIDE":"WORLD_EDITOR_OVERRIDE"):stableStringify(payload,2);const output=this.panel.querySelector("[data-export-output]");output.value=text;output.dataset.mode=mode;return text;}
  downloadExport(){const output=this.panel.querySelector("[data-export-output]"),mode=output.dataset.mode||"json";if(!output.value)this.generateExport(mode);downloadText(`voz_partida_${this.editor.engineType()}_override.${mode==="js"?"js":"json"}`,output.value,mode==="js"?"text/javascript":"application/json");}
  importExport(){this.safe(()=>{const text=this.panel.querySelector("[data-export-output]").value.trim(),json=text.startsWith("{")?text:text.slice(text.indexOf("{")).replace(/\);?\s*$/,""),payload=JSON.parse(json);this.editor.importPayload(payload);this.context.notify?.("Importação aplicada","O mapa foi atualizado e validado.","good");});}
  safe(callback){try{return callback();}catch(error){console.error(error);this.context.notify?.("Ação DEV falhou",error.message||String(error),"bad");}}
}

export function createDeveloperMode(context){const existing=globalThis.__VOZ_DEV__;if(existing?.__vozDevController){existing.context={...existing.context,...context};if(existing.editor?.context)Object.assign(existing.editor.context,{canvas:context.canvas,getState:context.getState,getEngine:context.getEngine,cache:context.cache,regions:context.regions,worldMapOverride:context.worldMapOverride,worldNavigationValue:context.worldNavigationValue});return existing;}if(existing){try{existing.editor?.setEnabled?.(false);existing.panel?.remove?.();existing.indicator?.remove?.();existing.editor?.overlay?.remove?.();}catch{}}return new DeveloperMode(context);}
