import { EditorHistory, cloneEditorValue } from "./editor_history.js";
import { buildTowerDelta, buildWorldExport, buildWorldExportCollection, stableStringify } from "./editor_export.js";
import { presentationFromAsset, normalizePropPresentation, propBlocksPoint, propCollisionBounds, propShadowSpec, propSortY, propVisualBounds } from "./prop_presentation.js";
import { rebuildTowerVisualPlan, validateTowerFloor } from "./tower_generator.js";
import { worldMapOverride as shippedWorldMapOverride, worldNavigationValue as shippedWorldNavigationValue } from "./map_overrides.js";

const CELL=64,clamp=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0)),cellKey=(x,y)=>`${x},${y}`;
const deepClone=cloneEditorValue;
const lineCells=(a,b)=>{const result=[];let x=a.x,y=a.y,dx=Math.abs(b.x-x),sx=x<b.x?1:-1,dy=-Math.abs(b.y-y),sy=y<b.y?1:-1,error=dx+dy;for(;;){result.push({x,y});if(x===b.x&&y===b.y)break;const twice=2*error;if(twice>=dy){error+=dy;x+=sx;}if(twice<=dx){error+=dx;y+=sy;}}return result;};
const rectCells=(a,b)=>{const result=[];for(let y=Math.min(a.y,b.y);y<=Math.max(a.y,b.y);y++)for(let x=Math.min(a.x,b.x);x<=Math.max(a.x,b.x);x++)result.push({x,y});return result;};

export class MapEditor{
  constructor(context){
    this.context=context;this.enabled=false;this.navigationPreview=false;this.layer="navigation";this.tool="select";this.navigationValue="blocked";this.brushSize=1;this.gridSize=64;this.snap=true;this.overlayOpacity=.48;this.allowInvalid=false;this.selected=null;this.placingAsset=null;this.placingEntity=null;this.pointer=null;this.worldDrafts=new Map();this.towerOriginals=new Map();this.lastValidation=null;this.history=new EditorHistory(90,()=>this.context.onChange?.());this.createOverlay();this.bind();
  }
  createOverlay(){
    const canvas=document.createElement("canvas");canvas.className="dev-map-overlay";canvas.tabIndex=0;canvas.setAttribute("aria-label","Editor visual do mapa");Object.assign(canvas.style,{position:"absolute",inset:"0",width:"100%",height:"100%",zIndex:"30",display:"none",touchAction:"none",cursor:"crosshair"});
    const parent=this.context.canvas.parentElement;if(getComputedStyle(parent).position==="static")parent.style.position="relative";parent.appendChild(canvas);this.overlay=canvas;this.ctx=canvas.getContext("2d");this.ctx.imageSmoothingEnabled=false;
  }
  bind(){
    this.overlay.addEventListener("pointerdown",event=>this.pointerDown(event));this.overlay.addEventListener("pointermove",event=>this.pointerMove(event));for(const type of["pointerup","pointercancel","lostpointercapture"])this.overlay.addEventListener(type,event=>this.pointerUp(event));
    this.overlay.addEventListener("contextmenu",event=>event.preventDefault());
    this.keyHandler=event=>{if(!this.enabled||/INPUT|SELECT|TEXTAREA/.test(event.target?.tagName||""))return;if((event.ctrlKey||event.metaKey)&&event.code==="KeyZ"){event.preventDefault();event.shiftKey?this.redo():this.undo();}else if((event.ctrlKey||event.metaKey)&&event.code==="KeyY"){event.preventDefault();this.redo();}else if(event.code==="Delete"||event.code==="Backspace"){event.preventDefault();this.deleteSelected();}else if((event.ctrlKey||event.metaKey)&&event.code==="KeyD"){event.preventDefault();this.duplicateSelected();}else if(this.selected&&event.code.startsWith("Arrow")){event.preventDefault();const step=event.shiftKey?10:1,dx=event.code==="ArrowLeft"?-step:event.code==="ArrowRight"?step:0,dy=event.code==="ArrowUp"?-step:event.code==="ArrowDown"?step:0;this.nudgeSelected(dx,dy);}};
    window.addEventListener("keydown",this.keyHandler);
  }
  overlayActive(){return this.enabled||this.navigationPreview;}
  syncOverlayState(){const active=this.overlayActive();this.overlay.style.display=active?"block":"none";this.overlay.style.pointerEvents=this.enabled?"auto":"none";this.overlay.style.cursor=this.enabled?"crosshair":"default";if(active)this.startDrawing();else cancelAnimationFrame(this.drawFrame);}
  setEnabled(value){this.enabled=Boolean(value);if(this.enabled){this.ensureCurrentDraft();this.context.getEngine()?.stop?.();}else{this.pointer=null;this.selected=null;}this.syncOverlayState();}
  setNavigationPreview(value){this.navigationPreview=Boolean(value);if(this.navigationPreview)this.ensureCurrentDraft();this.syncOverlayState();}
  startDrawing(){cancelAnimationFrame(this.drawFrame);const draw=()=>{if(!this.overlayActive())return;this.render();this.drawFrame=requestAnimationFrame(draw);};draw();}
  engineType(){return this.context.getState()?.gameMode==="tower"?"tower":"world";}
  engine(){return this.context.getEngine();}
  worldToScreen(point){const engine=this.engine();return{x:point.x-engine.camera.x,y:point.y-engine.camera.y};}
  screenToWorld(event){const rect=this.overlay.getBoundingClientRect(),engine=this.engine();return{x:(event.clientX-rect.left)*this.overlay.width/Math.max(1,rect.width)+engine.camera.x,y:(event.clientY-rect.top)*this.overlay.height/Math.max(1,rect.height)+engine.camera.y};}
  cellFor(point){const size=this.engineType()==="tower"?CELL:this.gridSize;return{x:Math.floor(point.x/size),y:Math.floor(point.y/size)};}
  towerKey(floor=this.engine()?.floor){return floor?`${floor.seed}|${floor.floor}|${floor.floorSeed}`:null;}
  ensureCurrentDraft(){if(this.engineType()==="tower")this.ensureTowerOriginal();else this.ensureWorldDraft();}
  ensureTowerOriginal(){const floor=this.engine()?.floor,key=this.towerKey(floor);if(floor&&key&&!this.towerOriginals.has(key))this.towerOriginals.set(key,this.captureTower());}
  ensureWorldDraft(){
    const state=this.context.getState(),engine=this.engine();if(!state||!engine)return null;const id=Number(state.regionIndex);let draft=this.worldDrafts.get(id);
    if(!draft){const spawn=engine.spawnPoint?.(id)||state.position||{x:0,y:0};draft={regionId:id,navigation:new Map(),props:[],addedEntities:[],modifiedEntities:new Map(),removedEntityIds:new Set(),baseEntities:deepClone(engine.entities||[]),baseEntitiesCaptured:true,world:deepClone(engine.world||null),baseSpawn:deepClone(spawn),obstacles:deepClone(engine.obstacles?.(id)),spawnOverride:null,spawnHandle:{id:"spawn",type:"spawn",x:spawn.x,y:spawn.y},runtimeEntitiesRef:engine.entities};this.worldDrafts.set(id,draft);}
    if(!(draft.removedEntityIds instanceof Set))draft.removedEntityIds=new Set(draft.removedEntityIds||[]);
    if(!(draft.modifiedEntities instanceof Map))draft.modifiedEntities=new Map(draft.modifiedEntities||[]);
    if(!(draft.navigation instanceof Map))draft.navigation=new Map(draft.navigation||[]);
    if(draft.runtimeEntitiesRef!==engine.entities){draft.baseEntities=deepClone(engine.entities||[]);draft.baseEntitiesCaptured=true;draft.world=deepClone(engine.world||draft.world||null);draft.baseSpawn=deepClone(engine.spawnPoint?.(id)||draft.baseSpawn||state.position||{x:0,y:0});draft.obstacles=deepClone(engine.obstacles?.(id)??draft.obstacles);this.reconcileLegacyEntities(draft);this.applyWorldDraftRuntime(draft,engine);}
    return draft;
  }
  reconcileLegacyEntities(draft){if(!draft?.legacyEntities)return;const baseIds=new Set((draft.baseEntities||[]).map((entry)=>String(entry.id)));draft.addedEntities=[];draft.modifiedEntities=new Map();for(const entity of draft.legacyEntities){if(baseIds.has(String(entity.id)))draft.modifiedEntities.set(entity.id,deepClone(entity));else draft.addedEntities.push({...deepClone(entity),devAdded:true});}draft.legacyEntities=null;}
  applyWorldDraftRuntime(draft,engine=this.engine()){
    if(!draft||!engine)return;const removed=draft.removedEntityIds instanceof Set?draft.removedEntityIds:new Set(draft.removedEntityIds||[]);engine.entities=deepClone(draft.baseEntities||[]).filter((entry)=>!removed.has(String(entry.id)));for(const entity of engine.entities){const change=draft.modifiedEntities.get(entity.id);if(change)Object.assign(entity,deepClone(change));}for(const entity of draft.addedEntities||[])if(!removed.has(String(entity.id)))engine.entities.push({...deepClone(entity),devAdded:true});for(const entity of engine.entities)if(entity.sprite)this.context.cache.loadFirst(entity.sprite,entity.fallbacks||[]);draft.runtimeEntitiesRef=engine.entities;this.context.onMapChanged?.();
  }
  captureTower(){const floor=this.engine()?.floor;if(!floor)return null;return deepClone({grid:floor.grid,pathCells:floor.pathCells,bridgeCells:floor.bridgeCells,props:floor.props,entities:floor.entities,spawn:floor.spawn,objective:floor.objective});}
  applyTower(snapshot){const engine=this.engine(),floor=engine?.floor;if(!floor||!snapshot)return;for(const field of["grid","pathCells","bridgeCells","props","entities","spawn","objective"])floor[field]=deepClone(snapshot[field]);rebuildTowerVisualPlan(floor);engine.pathLookup=new Set((floor.pathCells||[]).map(([x,y])=>cellKey(x,y)));engine.bridgeLookup=new Set((floor.bridgeCells||[]).map(([x,y])=>cellKey(x,y)));engine.prepareEntities?.(this.context.getState().tower.activeRun);engine.buildSpatialIndex();engine.invalidateVisualCaches?.();engine.chunks?.clear();engine.surfaceTiles?.clear();this.context.onMapChanged?.();}
  captureWorld(){const draft=this.ensureWorldDraft();return{regionId:draft.regionId,navigation:[...draft.navigation],props:deepClone(draft.props),addedEntities:deepClone(draft.addedEntities),modifiedEntities:[...draft.modifiedEntities].map(([id,value])=>[id,deepClone(value)]),removedEntityIds:[...draft.removedEntityIds].sort(),spawnOverride:deepClone(draft.spawnOverride)};}
  applyWorld(snapshot){const draft=this.ensureWorldDraft(),engine=this.engine();draft.navigation=new Map(snapshot.navigation||[]);draft.props=deepClone(snapshot.props||[]);draft.addedEntities=deepClone(snapshot.addedEntities||[]).map((entry)=>({...entry,devAdded:true}));draft.modifiedEntities=new Map(snapshot.modifiedEntities||[]);draft.removedEntityIds=new Set(snapshot.removedEntityIds||[]);draft.spawnOverride=deepClone(snapshot.spawnOverride);Object.assign(draft.spawnHandle,draft.spawnOverride||draft.baseSpawn||{});this.applyWorldDraftRuntime(draft,engine);}
  capture(){return this.engineType()==="tower"?this.captureTower():this.captureWorld();}
  apply(snapshot){return this.engineType()==="tower"?this.applyTower(snapshot):this.applyWorld(snapshot);}
  commit(label,before){const after=this.capture();if(stableStringify(before,0)===stableStringify(after,0))return false;if(this.engineType()==="tower"&&!this.allowInvalid){const validation=validateTowerFloor(this.engine().floor);if(!validation.valid){this.apply(before);this.context.notify?.("Edição recusada",validation.errors[0]||"O andar ficaria inválido.","bad");return false;}}this.history.push({label,before,after,apply:value=>this.apply(value)});this.validate();this.context.onChange?.();return true;}

  pointerDown(event){if(!this.enabled)return;event.preventDefault();this.overlay.setPointerCapture?.(event.pointerId);const world=this.screenToWorld(event),cell=this.cellFor(world),before=this.capture();this.pointer={id:event.pointerId,startWorld:world,lastWorld:world,startCell:cell,lastCell:cell,before,moved:false};
    if(this.placingAsset)return this.placeAsset(world,before);
    if(this.placingEntity)return this.placeEntity(world,before);
    if(this.tool==="select"||this.tool==="move")return this.selectAt(world);
    if(this.tool==="eyedropper")return this.pickNavigation(cell);
    if(["brush","eraser"].includes(this.tool))this.paintCells(this.brushCells(cell),this.tool==="eraser"?"restore":this.navigationValue);
    if(this.tool==="fill")this.fill(cell,this.navigationValue);
  }
  pointerMove(event){if(!this.pointer||event.pointerId!==this.pointer.id)return;const world=this.screenToWorld(event),cell=this.cellFor(world);this.pointer.moved=this.pointer.moved||Math.hypot(world.x-this.pointer.startWorld.x,world.y-this.pointer.startWorld.y)>2;this.pointer.lastWorld=world;this.pointer.lastCell=cell;
    if(this.tool==="move"&&this.selected)this.moveSelected(world);
    else if(this.tool==="brush"||this.tool==="eraser")this.paintCells(this.brushCells(cell),this.tool==="eraser"?"restore":this.navigationValue);
  }
  pointerUp(event){if(!this.pointer||event.pointerId!==this.pointer.id)return;const pointer=this.pointer;this.pointer=null;if(this.tool==="line")this.paintCells(lineCells(pointer.startCell,pointer.lastCell),this.navigationValue);if(this.tool==="rectangle")this.paintCells(rectCells(pointer.startCell,pointer.lastCell),this.navigationValue);if(["brush","eraser","fill","line","rectangle","move"].includes(this.tool))this.commit(this.tool==="move"?"Mover objeto":"Editar navegação",pointer.before);}
  brushCells(center){const radius=Math.max(0,Math.floor(this.brushSize/2)),result=[];for(let y=center.y-radius;y<=center.y+radius;y++)for(let x=center.x-radius;x<=center.x+radius;x++)result.push({x,y});return result;}
  paintCells(cells,value){if(this.layer!=="navigation")return;this.engineType()==="tower"?this.paintTower(cells,value):this.paintWorld(cells,value);}
  paintWorld(cells,value){const draft=this.ensureWorldDraft();for(const cell of cells){const id=cellKey(cell.x,cell.y);if(value==="restore")draft.navigation.delete(id);else draft.navigation.set(id,value);}}
  paintTower(cells,value){const floor=this.engine()?.floor;if(!floor)return;const pathSet=new Set((floor.pathCells||[]).map(([x,y])=>cellKey(x,y))),bridgeSet=new Set((floor.bridgeCells||[]).map(([x,y])=>cellKey(x,y))),original=this.towerOriginals.get(this.towerKey());for(const cell of cells){if(cell.x<0||cell.y<0||cell.x>=floor.size||cell.y>=floor.size)continue;const id=cellKey(cell.x,cell.y);if(value==="restore"){floor.grid[cell.y][cell.x]=original?.grid?.[cell.y]?.[cell.x]??0;if((original?.pathCells||[]).some(([x,y])=>x===cell.x&&y===cell.y))pathSet.add(id);else pathSet.delete(id);if((original?.bridgeCells||[]).some(([x,y])=>x===cell.x&&y===cell.y))bridgeSet.add(id);else bridgeSet.delete(id);}else if(value==="walkable"||value==="path"){floor.grid[cell.y][cell.x]=1;if(value==="path")pathSet.add(id);else pathSet.delete(id);bridgeSet.delete(id);}else if(value==="bridge"){floor.grid[cell.y][cell.x]=1;pathSet.add(id);bridgeSet.add(id);}else if(value==="hazard"){floor.grid[cell.y][cell.x]=2;pathSet.delete(id);bridgeSet.delete(id);}else{floor.grid[cell.y][cell.x]=0;pathSet.delete(id);bridgeSet.delete(id);}}
    floor.pathCells=[...pathSet].map(id=>id.split(",").map(Number)).sort((a,b)=>a[1]-b[1]||a[0]-b[0]);floor.bridgeCells=[...bridgeSet].map(id=>id.split(",").map(Number)).sort((a,b)=>a[1]-b[1]||a[0]-b[0]);rebuildTowerVisualPlan(floor);this.engine().pathLookup=pathSet;this.engine().bridgeLookup=bridgeSet;this.engine().invalidateVisualCaches?.();}
  fill(start,value){if(this.engineType()==="world"){this.paintWorld([start],value);return;}const floor=this.engine()?.floor;if(!floor||!floor.grid[start.y])return;const target=floor.grid[start.y][start.x],seen=new Set(),queue=[start],cells=[];for(let index=0;index<queue.length&&cells.length<4096;index++){const point=queue[index],id=cellKey(point.x,point.y);if(seen.has(id)||floor.grid[point.y]?.[point.x]!==target)continue;seen.add(id);cells.push(point);queue.push({x:point.x+1,y:point.y},{x:point.x-1,y:point.y},{x:point.x,y:point.y+1},{x:point.x,y:point.y-1});}this.paintTower(cells,value);}
  pickNavigation(cell){if(this.engineType()==="tower"){const floor=this.engine()?.floor,value=floor?.grid?.[cell.y]?.[cell.x];this.navigationValue=(floor?.bridgeCells||[]).some(([x,y])=>x===cell.x&&y===cell.y)?"bridge":(floor?.pathCells||[]).some(([x,y])=>x===cell.x&&y===cell.y)?"path":value===2?"hazard":value===1?"walkable":"void";}else this.navigationValue=this.ensureWorldDraft().navigation.get(cellKey(cell.x,cell.y))||"restore";this.context.onChange?.();}

  selectable(){const engine=this.engine();if(this.engineType()==="tower")return[{kind:"spawn",value:engine.floor.spawn},...(engine.floor?.props||[]).map(value=>({kind:"prop",value})),...(engine.floor?.entities||[]).map(value=>({kind:"entity",value}))];const draft=this.ensureWorldDraft();return[{kind:"spawn",value:draft.spawnHandle},...draft.props.map(value=>({kind:"prop",value})),...(engine.entities||[]).map(value=>({kind:"entity",value}))];}
  selectAt(world){const candidates=this.selectable().map(entry=>({entry,distance:Math.hypot(world.x-entry.value.x,world.y-entry.value.y)})).filter(item=>item.distance<Math.max(48,(item.entry.value.footprint?.[0]||0)/2+24)).sort((a,b)=>a.distance-b.distance);this.selected=candidates[0]?.entry||null;this.context.onSelection?.(this.selected);}
  moveSelected(world){if(!this.selected)return;const point=this.snap?{x:(Math.floor(world.x/(this.engineType()==="tower"?CELL:this.gridSize))+.5)*(this.engineType()==="tower"?CELL:this.gridSize),y:(Math.floor(world.y/(this.engineType()==="tower"?CELL:this.gridSize))+.82)*(this.engineType()==="tower"?CELL:this.gridSize)}:world;Object.assign(this.selected.value,{x:point.x,y:point.y,cellX:Math.floor(point.x/CELL),cellY:Math.floor(point.y/CELL)});this.trackWorldEntityChange();if(this.engineType()==="tower")this.engine().buildSpatialIndex();}
  nudgeSelected(dx,dy){if(!this.selected)return;const before=this.capture();this.selected.value.x+=dx;this.selected.value.y+=dy;this.selected.value.cellX=Math.floor(this.selected.value.x/CELL);this.selected.value.cellY=Math.floor(this.selected.value.y/CELL);this.trackWorldEntityChange();if(this.engineType()==="tower")this.engine().buildSpatialIndex();this.commit("Ajustar posição",before);}
  trackWorldEntityChange(){if(this.selected?.kind==="spawn"){if(this.engineType()==="world")this.ensureWorldDraft().spawnOverride={x:this.selected.value.x,y:this.selected.value.y};else Object.assign(this.engine().floor.spawn,{x:this.selected.value.x,y:this.selected.value.y,cellX:Math.floor(this.selected.value.x/CELL),cellY:Math.floor(this.selected.value.y/CELL)});return;}if(this.engineType()!=="world"||this.selected?.kind!=="entity")return;const draft=this.ensureWorldDraft(),entity=this.selected.value;if(entity.devAdded){const index=draft.addedEntities.findIndex(entry=>entry.id===entity.id);if(index>=0)draft.addedEntities[index]=entity;}else draft.modifiedEntities.set(entity.id,deepClone(entity));}
  setPlacingAsset(asset){this.placingAsset=asset;this.placingEntity=null;this.tool="place";this.layer="scenery";this.context.onChange?.();}
  setPlacingEntity(spec){this.placingEntity=spec;this.placingAsset=null;this.tool="place";this.layer="entity";this.context.onChange?.();}
  async placeAsset(world,before=this.capture()){const asset=this.placingAsset;if(!asset)return;const size=this.engineType()==="tower"?CELL:this.gridSize,x=this.snap?(Math.floor(world.x/size)+.5)*size:world.x,y=this.snap?(Math.floor(world.y/size)+.82)*size:world.y,presentation=presentationFromAsset(asset,.5),prop=normalizePropPresentation({id:`dev-prop-${Date.now().toString(36)}-${Math.floor(x)}-${Math.floor(y)}`,assetId:asset.id,path:asset.path,x,y,cellX:Math.floor(x/CELL),cellY:Math.floor(y/CELL),layer:asset.layer,collision:asset.collision,composition:asset.compositionSet||"editor",facing:"editor",devAdded:true,...presentation});await this.context.cache.load(asset.path);if(this.engineType()==="tower"){this.engine().floor.props.push(prop);this.engine().buildSpatialIndex();}else this.ensureWorldDraft().props.push(prop);this.selected={kind:"prop",value:prop};this.commit("Adicionar cenário",before);this.context.onSelection?.(this.selected);}
  async placeEntity(world,before=this.capture()){const spec=this.placingEntity;if(!spec)return;const entity=await this.context.createEntity?.(this.engineType(),spec,world);if(!entity)return;entity.devAdded=true;if(this.engineType()==="tower"){this.engine().floor.entities.push(entity);this.engine().prepareEntities(this.context.getState().tower.activeRun);for(const direction of["front","back","left","right"]){const spriteSpec=entity.spriteSpecs?.[direction];if(spriteSpec)await this.context.cache.loadFirst(spriteSpec.exact,spriteSpec.candidates);}}else{this.ensureWorldDraft().addedEntities.push(entity);this.engine().entities.push(entity);if(entity.sprite)await this.context.cache.loadFirst(entity.sprite,entity.fallbacks||[]);}this.selected={kind:"entity",value:entity};this.commit("Adicionar entidade",before);this.context.onSelection?.(this.selected);}
  deleteSelected(){if(!this.selected)return;if(this.selected.kind==="spawn")return this.context.notify?.("O spawn não pode ser removido","Mova-o ou restaure o mapa original.","bad");const before=this.capture(),target=this.selected.value;if(this.engineType()==="tower"){const list=this.selected.kind==="prop"?this.engine().floor.props:this.engine().floor.entities;const index=list.findIndex(entry=>entry.id===target.id);if(index>=0)list.splice(index,1);this.engine().buildSpatialIndex();}else{const draft=this.ensureWorldDraft();if(this.selected.kind==="prop")draft.props=draft.props.filter(entry=>entry.id!==target.id);else{const wasAdded=target.devAdded||draft.addedEntities.some(entry=>entry.id===target.id);draft.addedEntities=draft.addedEntities.filter(entry=>entry.id!==target.id);if(!wasAdded){draft.removedEntityIds.add(String(target.id));draft.modifiedEntities.delete(target.id);}this.engine().entities=this.engine().entities.filter(entry=>entry.id!==target.id);draft.runtimeEntitiesRef=this.engine().entities;}}this.selected=null;this.commit("Excluir objeto",before);this.context.onSelection?.(null);}
  duplicateSelected(){if(!this.selected||this.selected.kind==="spawn")return;const before=this.capture(),copy=deepClone(this.selected.value);copy.id=`${copy.id}-copia-${Date.now().toString(36)}`;copy.x+=this.snap?(this.engineType()==="tower"?CELL:this.gridSize):16;copy.devAdded=true;if(this.engineType()==="tower"){(this.selected.kind==="prop"?this.engine().floor.props:this.engine().floor.entities).push(copy);this.engine().buildSpatialIndex();}else if(this.selected.kind==="prop")this.ensureWorldDraft().props.push(copy);else{this.ensureWorldDraft().addedEntities.push(copy);this.engine().entities.push(copy);}this.selected={kind:this.selected.kind,value:copy};this.commit("Duplicar objeto",before);this.context.onSelection?.(this.selected);}
  updateSelected(properties,label="Editar propriedades"){if(!this.selected)return;const before=this.capture();Object.assign(this.selected.value,properties);if(this.selected.kind==="prop"&&properties.height&&properties.proportionalCollision!==false){const old=Number(before?.props?.find?.(entry=>entry.id===this.selected.value.id)?.height||this.selected.value.recommendedWorldHeight||properties.height),ratio=properties.height/Math.max(1,old);for(const field of["footprint","visualFootprint"])if(Array.isArray(this.selected.value[field]))this.selected.value[field]=this.selected.value[field].map(value=>value*ratio);for(const field of["shadowWidth","shadowHeight","collisionOffsetX","collisionOffsetY"])this.selected.value[field]=(Number(this.selected.value[field])||0)*ratio;}this.trackWorldEntityChange();if(this.engineType()==="tower")this.engine().buildSpatialIndex();this.commit(label,before);}
  resetSelectedScale(){if(!this.selected||this.selected.kind!=="prop")return;this.updateSelected({height:this.selected.value.recommendedWorldHeight||this.selected.value.height},"Restaurar escala recomendada");}

  undo(){if(this.history.undo())this.validate();}
  redo(){if(this.history.redo())this.validate();}
  reset(){const before=this.capture();if(this.engineType()==="tower")this.applyTower(this.towerOriginals.get(this.towerKey()));else{const draft=this.ensureWorldDraft();draft.navigation.clear();draft.props=[];draft.addedEntities=[];draft.modifiedEntities.clear();draft.removedEntityIds.clear();draft.spawnOverride=null;this.applyWorld(this.captureWorld());}this.commit("Restaurar mapa",before);}
  worldCollisionAt(position,index){if(!this.enabled||this.engineType()!=="world")return null;const draft=this.worldDrafts.get(index);if(!draft)return null;const value=draft.navigation.get(cellKey(Math.floor(position.x/this.gridSize),Math.floor(position.y/this.gridSize)));if(["blocked","hazard","void"].includes(value))return true;if(draft.props.some((prop)=>propBlocksPoint(prop,position.x,position.y,21)))return true;if(["walkable","path","bridge"].includes(value))return false;return null;}
  validate(){if(this.engineType()==="tower")this.lastValidation=validateTowerFloor(this.engine().floor);else{const draft=this.ensureWorldDraft(),all=[...draft.props,...this.engine().entities],ids=all.map(entry=>entry.id),duplicates=ids.filter((id,index)=>ids.indexOf(id)!==index),outside=all.filter(entry=>entry.x<0||entry.y<0||entry.x>this.engine().world.w||entry.y>this.engine().world.h),missing=draft.props.filter((entry)=>!entry.path),blocked=[...draft.navigation.values()].filter((value)=>["blocked","hazard","void"].includes(value)).length,walkable=[...draft.navigation.values()].filter((value)=>["walkable","path","bridge"].includes(value)).length,errors=[...duplicates.map(id=>`ID duplicado: ${id}`),...outside.map(entry=>`Fora do mapa: ${entry.id}`),...missing.map(entry=>`Asset ausente: ${entry.id}`)];this.lastValidation={valid:!errors.length,errors:[...new Set(errors)],counts:{navigation:draft.navigation.size,walkable,blocked,props:draft.props.length,solidProps:draft.props.filter((entry)=>!["none","traversable"].includes(entry.collision)).length,enemies:this.engine().entities.filter((entry)=>entry.type==="encounter").length,entities:this.engine().entities.length,removedEntities:draft.removedEntityIds.size,regionsWithDrafts:this.worldDrafts.size}};}this.context.onValidation?.(this.lastValidation);return this.lastValidation;}
  exportWorldRegion(regionId){
    const id=Number(regionId),region=this.context.regions?.find?.((entry)=>Number(entry.id)===id)||this.context.regions?.[id],base=deepClone(this.resolveWorldOverride(id)||{}),draft=this.worldDrafts.get(id),hasOwn=(object,key)=>Object.prototype.hasOwnProperty.call(object||{},key),mergeById=(...lists)=>{const map=new Map();for(const list of lists)for(const entry of list||[])if(entry?.id!==undefined)map.set(entry.id,deepClone(entry));return[...map.values()];};
    if(!draft){const layout={};if(hasOwn(base,"spawn"))layout.spawn=deepClone(base.spawn);if(hasOwn(base,"obstacles"))layout.obstacles=deepClone(base.obstacles);return buildWorldExport({regionId:id,world:base.world||null,layout,navigation:base.navigation||[],navigationChanges:[],navigationRaster:base.navigationRaster||null,props:base.props||[],addedProps:[],entities:base.entities||[],modifiedEntities:[],addedEntities:[],removedEntityIds:base.removedEntityIds||[],spawnOverride:null,metadata:{...(base.metadata||{}),region:region?.name||`Região ${id}`,gridSize:Number(base.metadata?.gridSize)||this.gridSize,allRegionsExport:true,unedited:true}});}
    const removed=new Set([...(base.removedEntityIds||[]),...draft.removedEntityIds].map(String)),navigation=new Map((base.navigation||[]).map((entry)=>[cellKey(entry.x,entry.y),entry.value]));for(const [key,value] of draft.navigation)navigation.set(key,value);const modified=[...draft.modifiedEntities.values()].map(deepClone),added=deepClone(draft.addedEntities||[]),entities=mergeById((base.entities||[]).filter((entry)=>!removed.has(String(entry.id))),modified,added).filter((entry)=>!removed.has(String(entry.id))),props=mergeById(base.props||[],draft.props||[]),layout={spawn:deepClone(draft.spawnOverride||base.spawn||draft.baseSpawn||null)};if(hasOwn(base,"obstacles"))layout.obstacles=deepClone(base.obstacles);else if(draft.obstacles!==undefined)layout.obstacles=deepClone(draft.obstacles);
    return buildWorldExport({regionId:id,world:draft.world||base.world||null,layout,navigation,navigationChanges:draft.navigation,navigationRaster:base.navigationRaster||null,props,addedProps:draft.props,entities,modifiedEntities:modified,addedEntities:added,removedEntityIds:[...removed],spawnOverride:deepClone(draft.spawnOverride),metadata:{...(base.metadata||{}),region:region?.name||`Região ${id}`,gridSize:this.gridSize,allRegionsExport:true,unedited:false}});
  }
  exportAllWorldPayload(){this.ensureWorldDraft();const overrides=new Map();for(const region of this.context.regions||[])overrides.set(Number(region.id),this.exportWorldRegion(region.id));return buildWorldExportCollection(overrides,{allRegions:true,regionNames:(this.context.regions||[]).map((region)=>region.name),draftRegionIds:[...this.worldDrafts.keys()].sort((a,b)=>a-b)});}
  exportPayload(full=false){if(this.engineType()==="tower"){const original=this.towerOriginals.get(this.towerKey()),current=this.engine().floor;return full?{kind:"voz-partida-tower-snapshot",version:1,floor:deepClone(current)}:buildTowerDelta(original,current);}return this.exportAllWorldPayload();}
  importWorldOverride(override){
    const id=Number(override.regionId),state=this.context.getState(),engine=this.engine(),current=this.engineType()==="world"&&Number(state?.regionIndex)===id,hasOwn=(object,key)=>Object.prototype.hasOwnProperty.call(object||{},key);let draft=this.worldDrafts.get(id);
    if(!draft){const spawn=override.spawn||{x:0,y:0};draft={regionId:id,navigation:new Map(),props:[],addedEntities:[],modifiedEntities:new Map(),removedEntityIds:new Set(),baseEntities:current?deepClone(engine.entities||[]):[],baseEntitiesCaptured:current,world:deepClone(current?engine.world:override.world||null),baseSpawn:deepClone(current?engine.spawnPoint?.(id)||spawn:spawn),obstacles:deepClone(current?engine.obstacles?.(id):override.obstacles),spawnOverride:null,spawnHandle:{id:"spawn",type:"spawn",x:Number(spawn.x)||0,y:Number(spawn.y)||0},runtimeEntitiesRef:current?engine.entities:null};this.worldDrafts.set(id,draft);}
    const navigationEntries=hasOwn(override,"navigationChanges")?override.navigationChanges:override.navigation;draft.navigation=new Map((navigationEntries||[]).map((entry)=>[cellKey(entry.x,entry.y),entry.value]));draft.props=deepClone(hasOwn(override,"addedProps")?override.addedProps:override.props||[]).map((entry)=>({...entry,devAdded:true}));draft.removedEntityIds=new Set((override.removedEntityIds||[]).map(String));draft.spawnOverride=deepClone(hasOwn(override,"spawnOverride")?override.spawnOverride:override.spawn||null);Object.assign(draft.spawnHandle,draft.spawnOverride||draft.baseSpawn||override.spawn||{});
    if(hasOwn(override,"modifiedEntities")||hasOwn(override,"addedEntities")){draft.modifiedEntities=new Map((override.modifiedEntities||[]).map((entry)=>[entry.id,deepClone(entry)]));draft.addedEntities=deepClone(override.addedEntities||[]).map((entry)=>({...entry,devAdded:true}));draft.legacyEntities=null;}else{draft.legacyEntities=deepClone(override.entities||[]);if(current)this.reconcileLegacyEntities(draft);}
    if(current){draft.runtimeEntitiesRef=null;this.ensureWorldDraft();}return draft;
  }
  importPayload(payload){if(!payload||typeof payload!=="object")throw new Error("Arquivo de editor inválido.");const before=this.capture();if(payload.kind==="voz-partida-world-overrides"&&this.engineType()==="world"){for(const override of Object.values(payload.regions||{}))this.importWorldOverride(override);this.ensureWorldDraft();this.context.notify?.("Todas as regiões importadas",`${Object.keys(payload.regions||{}).length} regiões foram carregadas no editor.`,"good");}else if(payload.kind==="voz-partida-world-override"&&this.engineType()==="world"){this.importWorldOverride(payload);}else if(payload.kind==="voz-partida-tower-delta"&&this.engineType()==="tower"){const floor=this.engine().floor;if(Number(payload.floor)!==Number(floor.floor)||Number(payload.floorSeed)!==Number(floor.floorSeed))throw new Error("O delta pertence a outro andar ou seed.");for(const entry of payload.changedGridCells||[])if(floor.grid?.[entry.y]?.[entry.x]!==undefined)floor.grid[entry.y][entry.x]=entry.value;if(Array.isArray(payload.pathCellsOverride))floor.pathCells=deepClone(payload.pathCellsOverride);if(Array.isArray(payload.bridgeCellsOverride))floor.bridgeCells=deepClone(payload.bridgeCellsOverride);const removedProps=new Set(payload.removedPropIds||[]),removedEntities=new Set(payload.removedEntityIds||[]);floor.props=floor.props.filter(entry=>!removedProps.has(entry.id));floor.entities=floor.entities.filter(entry=>!removedEntities.has(entry.id));const merge=(list,entries)=>entries.forEach(entry=>{const target=list.find(value=>value.id===entry.id);if(target)Object.assign(target,deepClone(entry));else list.push(deepClone(entry));});merge(floor.props,[...payload.modifiedProps||[],...payload.addedProps||[]]);merge(floor.entities,[...payload.modifiedEntities||[],...payload.addedEntities||[]]);if(payload.spawnOverride)floor.spawn={...floor.spawn,...deepClone(payload.spawnOverride)};this.applyTower(this.captureTower());}else throw new Error("O arquivo não corresponde ao mapa aberto.");this.commit("Importar edição",before);}
  saveDraft(){const key=this.engineType()==="tower"?this.towerKey():String(this.context.getState().regionIndex),payload={version:1,engine:this.engineType(),key,data:this.capture()};localStorage.setItem("voz_partida_dev_editor_v1",stableStringify(payload,0));return payload;}
  loadDraft(){const payload=JSON.parse(localStorage.getItem("voz_partida_dev_editor_v1")||"null");if(!payload||payload.engine!==this.engineType())throw new Error("Não há rascunho compatível com este mapa.");const before=this.capture();this.apply(payload.data);this.commit("Carregar rascunho",before);return payload;}
  deleteDraft(){localStorage.removeItem("voz_partida_dev_editor_v1");}

  render(){const source=this.context.canvas;if(this.overlay.width!==source.width||this.overlay.height!==source.height){this.overlay.width=source.width;this.overlay.height=source.height;this.ctx.imageSmoothingEnabled=false;}const ctx=this.ctx;ctx.clearRect(0,0,this.overlay.width,this.overlay.height);this.drawNavigation(ctx);if(this.enabled){if(this.engineType()==="world")this.drawWorldProps(ctx);this.drawMarkers(ctx);this.drawSelection(ctx);}if(this.navigationPreview)this.drawPathLegend(ctx);}
  visibleCellBounds(size,maxWidth=Infinity,maxHeight=Infinity){const engine=this.engine();return{minX:Math.max(0,Math.floor(engine.camera.x/size)),maxX:Math.min(maxWidth-1,Math.ceil((engine.camera.x+this.overlay.width)/size)),minY:Math.max(0,Math.floor(engine.camera.y/size)),maxY:Math.min(maxHeight-1,Math.ceil((engine.camera.y+this.overlay.height)/size))};}
  pathColor(value){return["walkable","path","bridge"].includes(value)?"38,235,104":"255,48,78";}
  resolveWorldOverride(regionId){return this.context.worldMapOverride?.(regionId)||shippedWorldMapOverride?.(regionId)||null;}
  resolveWorldNavigationValue(regionId,x,y,cellSize){return this.context.worldNavigationValue?.(regionId,x,y,cellSize)??shippedWorldNavigationValue?.(regionId,x,y,cellSize)??null;}
  drawWorldNavigationRaster(ctx,override){const raster=override?.navigationRaster;if(!raster||!Array.isArray(raster.rows))return false;const engine=this.engine(),size=Math.max(1,Number(raster.gridSize)||8),bounds=this.visibleCellBounds(size,Number(raster.width)||Infinity,Number(raster.height)||Infinity),alpha=Math.max(.18,Math.min(.9,this.overlayOpacity));ctx.globalCompositeOperation="source-over";for(let y=bounds.minY;y<=bounds.maxY;y++){const row=raster.rows[y]||"";let runStart=bounds.minX,runSymbol=row[runStart];for(let x=bounds.minX+1;x<=bounds.maxX+1;x++){const symbol=x<=bounds.maxX?row[x]:null;if(symbol===runSymbol)continue;if(runSymbol==="0"||runSymbol==="1"){const value=runSymbol==="1"?(raster.pathValue||"path"):(raster.blockedValue||"blocked");ctx.fillStyle=`rgba(${this.pathColor(value)},${alpha})`;ctx.fillRect(Math.round(runStart*size-engine.camera.x),Math.round(y*size-engine.camera.y),Math.max(1,(x-runStart)*size),size);}runStart=x;runSymbol=symbol;}}return true;}
  drawWorldNavigationSamples(ctx,regionId){const engine=this.engine(),size=8,bounds=this.visibleCellBounds(size),alpha=Math.max(.18,Math.min(.9,this.overlayOpacity));let painted=false;for(let y=bounds.minY;y<=bounds.maxY;y++)for(let x=bounds.minX;x<=bounds.maxX;x++){const value=this.resolveWorldNavigationValue(regionId,(x+.5)*size,(y+.5)*size,size);if(!value)continue;painted=true;ctx.fillStyle=`rgba(${this.pathColor(value)},${alpha})`;ctx.fillRect(Math.round(x*size-engine.camera.x),Math.round(y*size-engine.camera.y),size,size);}return painted;}
  drawNavigation(ctx){const engine=this.engine(),draft=this.engineType()==="world"?this.ensureWorldDraft():null;ctx.save();ctx.font="9px ui-monospace,monospace";ctx.textBaseline="top";if(this.engineType()==="world"){const regionId=this.context.getState()?.regionIndex,override=this.resolveWorldOverride(regionId);if(!this.drawWorldNavigationRaster(ctx,override))this.drawWorldNavigationSamples(ctx,regionId);const size=this.gridSize,bounds=this.visibleCellBounds(size);for(let y=bounds.minY;y<=bounds.maxY;y++)for(let x=bounds.minX;x<=bounds.maxX;x++){const value=draft.navigation.get(cellKey(x,y));if(!value)continue;const sx=Math.round(x*size-engine.camera.x),sy=Math.round(y*size-engine.camera.y);if(value==="restore"){ctx.clearRect(sx,sy,size,size);continue;}ctx.fillStyle=`rgba(${this.pathColor(value)},${this.overlayOpacity})`;ctx.fillRect(sx,sy,size,size);ctx.strokeStyle="rgba(255,255,255,.2)";ctx.strokeRect(sx+.5,sy+.5,size-1,size-1);if(this.enabled&&size>=48){ctx.fillStyle="rgba(255,255,255,.82)";ctx.fillText(`${x},${y} ${value}`,sx+3,sy+3);}}}else{const size=CELL,bounds=this.visibleCellBounds(size),floor=engine.floor,pathSet=new Set((floor?.pathCells||[]).map(([x,y])=>cellKey(x,y))),bridgeSet=new Set((floor?.bridgeCells||[]).map(([x,y])=>cellKey(x,y)));for(let y=bounds.minY;y<=bounds.maxY;y++)for(let x=bounds.minX;x<=bounds.maxX;x++){const cell=floor?.grid?.[y]?.[x];if(cell===undefined)continue;const key=cellKey(x,y),value=bridgeSet.has(key)?"bridge":pathSet.has(key)?"path":cell===1?"walkable":cell===2?"hazard":"void",sx=Math.round(x*size-engine.camera.x),sy=Math.round(y*size-engine.camera.y);ctx.fillStyle=`rgba(${this.pathColor(value)},${this.overlayOpacity})`;ctx.fillRect(sx,sy,size,size);ctx.strokeStyle="rgba(255,255,255,.16)";ctx.strokeRect(sx+.5,sy+.5,size-1,size-1);if(this.enabled){ctx.fillStyle="rgba(255,255,255,.78)";ctx.fillText(`${x},${y} ${value}`,sx+3,sy+3);}}if(this.enabled){const chunk=8*CELL;ctx.strokeStyle="rgba(255,54,144,.7)";ctx.lineWidth=2;for(let x=Math.ceil(engine.camera.x/chunk)*chunk;x<engine.camera.x+this.overlay.width;x+=chunk){ctx.beginPath();ctx.moveTo(x-engine.camera.x,0);ctx.lineTo(x-engine.camera.x,this.overlay.height);ctx.stroke();}for(let y=Math.ceil(engine.camera.y/chunk)*chunk;y<engine.camera.y+this.overlay.height;y+=chunk){ctx.beginPath();ctx.moveTo(0,y-engine.camera.y);ctx.lineTo(this.overlay.width,y-engine.camera.y);ctx.stroke();}}}ctx.restore();}
  drawPathLegend(ctx){ctx.save();ctx.font="700 11px ui-monospace,monospace";ctx.textBaseline="middle";ctx.fillStyle="rgba(7,6,10,.86)";ctx.fillRect(12,12,230,32);ctx.strokeStyle="rgba(255,255,255,.25)";ctx.strokeRect(12.5,12.5,229,31);ctx.fillStyle="rgb(38,235,104)";ctx.fillRect(22,22,12,12);ctx.fillStyle="#f5fff8";ctx.fillText("PATH",40,28);ctx.fillStyle="rgb(255,48,78)";ctx.fillRect(98,22,12,12);ctx.fillStyle="#fff2f4";ctx.fillText("BLOCK PATH",116,28);ctx.restore();}
  drawWorldProps(ctx){for(const prop of this.ensureWorldDraft().props){const image=this.context.cache.get(prop.path);if(!image)continue;const shadow=propShadowSpec(prop),box=propVisualBounds(prop),engine=this.engine(),anchorX=prop.x-engine.camera.x+(prop.anchorOffsetX||0),anchorY=prop.y-engine.camera.y+(prop.anchorOffsetY||0);ctx.fillStyle=`rgba(0,0,0,${shadow.opacity})`;ctx.beginPath();ctx.ellipse(shadow.x-engine.camera.x,shadow.y-engine.camera.y,shadow.width/2,shadow.height/2,0,0,Math.PI*2);ctx.fill();ctx.save();ctx.translate(anchorX,anchorY);if(prop.rotation&&prop.canRotate!==false)ctx.rotate(Number(prop.rotation)*Math.PI/180);if(prop.mirror&&prop.canMirror!==false)ctx.scale(-1,1);ctx.drawImage(image,...prop.sourceBounds,box.x-engine.camera.x-anchorX,box.y-engine.camera.y-anchorY,box.w,box.h);ctx.restore();}}
  drawMarkers(ctx){const engine=this.engine(),entities=this.engineType()==="tower"?engine.floor?.entities||[]:engine.entities||[],spawn=this.engineType()==="tower"?engine.floor?.spawn:this.ensureWorldDraft().spawnHandle,colors={spawn:"#4dff9a",entrance:"#42dffc",exit:"#ffd45f",objective:"#ffffff",encounter:"#ff496f",npc:"#c49aff",chest:"#f6ce63",altar:"#dca4ff",portal:"#4fdfff",tower:"#ff4a82"};ctx.save();ctx.font="10px ui-monospace,monospace";ctx.textAlign="center";for(const entity of[{...spawn,id:"SPAWN",type:"spawn"},...entities]){const point=this.worldToScreen(entity);if(point.x<-20||point.y<-20||point.x>this.overlay.width+20||point.y>this.overlay.height+20)continue;ctx.fillStyle=entity.objective?colors.objective:colors[entity.type]||"#fff";ctx.beginPath();if(entity.type==="spawn"){ctx.moveTo(point.x,point.y-8);ctx.lineTo(point.x+8,point.y+6);ctx.lineTo(point.x-8,point.y+6);ctx.closePath();}else ctx.arc(point.x,point.y,5,0,Math.PI*2);ctx.fill();ctx.fillText(entity.id,point.x,point.y+9);}ctx.restore();}
  drawSelection(ctx){if(!this.selected)return;const value=this.selected.value,engine=this.engine();ctx.save();if(this.selected.kind==="prop"){const visual=propVisualBounds(value),collision=propCollisionBounds(value),shadow=propShadowSpec(value),sortY=propSortY(value);ctx.strokeStyle="#63edff";ctx.strokeRect(visual.x-engine.camera.x,visual.y-engine.camera.y,visual.w,visual.h);ctx.strokeStyle="#ff506f";ctx.strokeRect(collision.x-engine.camera.x,collision.y-engine.camera.y,collision.w,collision.h);ctx.strokeStyle="#ffe06f";ctx.beginPath();ctx.ellipse(shadow.x-engine.camera.x,shadow.y-engine.camera.y,shadow.width/2,shadow.height/2,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#fff";ctx.fillRect(value.x-engine.camera.x-2,value.y-engine.camera.y-2,5,5);ctx.strokeStyle="#c894ff";ctx.beginPath();ctx.moveTo(value.x-engine.camera.x-24,sortY-engine.camera.y);ctx.lineTo(value.x-engine.camera.x+24,sortY-engine.camera.y);ctx.stroke();}else{const point=this.worldToScreen(value);ctx.strokeStyle=this.selected.kind==="spawn"?"#4dff9a":"#fff";ctx.lineWidth=2;ctx.beginPath();ctx.arc(point.x,point.y,15,0,Math.PI*2);ctx.stroke();}const point=this.worldToScreen(value);ctx.fillStyle="rgba(4,3,9,.86)";ctx.fillRect(point.x-78,point.y+18,156,25);ctx.fillStyle="#fff";ctx.font="9px ui-monospace,monospace";ctx.textAlign="center";ctx.fillText(`X ${Math.round(value.x)} Y ${Math.round(value.y)}`,point.x,point.y+22);ctx.fillText(`CELL ${Math.floor(value.x/CELL)},${Math.floor(value.y/CELL)}`,point.x,point.y+32);ctx.restore();}

  drawWorldMinimapOverlay(ctx,{w,h,world,scale,ox,oy}){if(!this.enabled||this.engineType()!=="world")return;const draft=this.ensureWorldDraft(),size=this.gridSize;ctx.save();for(const [id,value]of draft.navigation){const[x,y]=id.split(",").map(Number);ctx.fillStyle=["walkable","path","bridge"].includes(value)?"#26eb68":"#ff304e";ctx.globalAlpha=.55;ctx.fillRect(ox+x*size*scale,oy+y*size*scale,Math.max(1,size*scale),Math.max(1,size*scale));}ctx.globalAlpha=1;for(const prop of draft.props){ctx.fillStyle=prop.collision==="none"?"#d1a5ff":"#ffb05a";ctx.fillRect(ox+prop.x*scale-1,oy+prop.y*scale-1,3,3);}const spawn=draft.spawnHandle;ctx.fillStyle="#4dff9a";ctx.beginPath();ctx.arc(ox+spawn.x*scale,oy+spawn.y*scale,3,0,Math.PI*2);ctx.fill();ctx.restore();}
}
