(function(){
  window.EQ=window.EQ||{};
  const app=document.getElementById('app');
  const runtime={storyIndex:0,currentMission:null,lastSummary:null,lastSession:null,decision:null,quickQuestions:null,quickGrade:null,challengeMode:'quick',challengeBack:'teacher/quick',challengeLabel:'Quick Challenge'};
  const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const route=()=>location.hash.replace(/^#\/?/,'')||'title';
  function navigate(path){location.hash='#/'+path}
  function setWorld(grade){const w=EQ.CURRICULUM.grades[grade];document.documentElement.style.setProperty('--world',w.colors.world);document.documentElement.style.setProperty('--world-soft',w.colors.soft);EQ.Audio.syncAmbient(Number(grade))}
  function toast(message){const region=document.getElementById('toast-region'),el=document.createElement('div');el.className='toast reveal';el.textContent=message;region.appendChild(el);setTimeout(()=>el.remove(),3200)}
  function shell(content,opts){
    opts=opts||{};const p=EQ.Store.activeProfile(),s=EQ.Store.get().settings;
    return `<div class="app-shell"><header class="topbar"><button class="icon-btn" data-nav="${opts.back||'mode'}" aria-label="Voltar">←</button><button class="brand" data-nav="worlds" style="border:0;background:none;color:inherit"><span class="brand-orb"></span><span>English Quest</span></button><span class="topbar-spacer"></span>${p?`<button class="btn ghost small hide-mobile" data-nav="progress">${esc(p.avatar||'◉')} ${esc(p.nickname)}</button>`:''}<button class="icon-btn" data-audio-toggle aria-label="${s.sound?'Desativar':'Ativar'} sons">${s.sound?'♫':'×'}</button><button class="icon-btn" data-nav="accessibility" aria-label="Acessibilidade">Aa</button></header><div class="page ${opts.wide?'wide':''}">${content}</div><footer>English Quest: The Lost Signal · Dados salvos localmente · Funciona offline</footer></div>`;
  }
  function bindGlobal(){
    app.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));
    const audio=app.querySelector('[data-audio-toggle]');if(audio)audio.addEventListener('click',()=>{EQ.Accessibility.set('sound',!EQ.Store.get().settings.sound);render()});
    app.querySelectorAll('button').forEach(b=>{if(!b.dataset.audioBound){b.dataset.audioBound='1';b.addEventListener('click',()=>EQ.Audio.click(),{once:true})}});
  }
  function titleScreen(){
    app.innerHTML=`<section class="title-screen"><div class="title-card reveal"><span class="eyebrow">A signal needs your class</span><div class="signal-hero" aria-hidden="true"><div class="ring"></div><div class="ring two"></div><div class="core"><span class="eye"></span></div></div><h1 class="glitch-title">English Quest:<br><span style="color:var(--accent)">The Lost Signal</span></h1><p class="subtitle">Learn English. Decode the mystery. Restore the signal.</p><div class="cta-row"><button class="btn" data-nav="mode">Iniciar transmissão</button><button class="btn secondary" data-nav="credits">Conhecer o projeto</button></div><p class="muted tiny" style="margin-top:18px">6º ao 9º ano · 2º trimestre · individual, equipes ou projetor</p></div></section>`;bindGlobal();
  }
  function modeScreen(){
    const content=`<div class="section-head"><div><span class="kicker">Selecione o acesso</span><h2>Como a turma vai jogar?</h2><p class="muted">A mesma aventura se adapta ao dispositivo e à dinâmica da aula.</p></div></div><div class="grid three">
      <button class="mode-card" data-nav="student-entry"><span class="mode-icon">◉</span><h3>Estudante</h3><p class="muted">Entrar por código, continuar progresso e explorar as missões.</p><span class="badge">Individual ou grupo</span></button>
      <button class="mode-card" data-nav="teacher/overview"><span class="mode-icon">▧</span><h3>Professor</h3><p class="muted">Gerenciar turma, lançar atividades, revisar dados e criar conteúdo.</p><span class="badge">Controle local</span></button>
      <button class="mode-card" data-mode-projector><span class="mode-icon">▣</span><h3>Projetor</h3><p class="muted">Interface ampliada para votação, resposta oral e colaboração coletiva.</p><span class="badge">Uma tela para todos</span></button>
    </div>`;app.innerHTML=shell(content,{back:'title'});bindGlobal();app.querySelector('[data-mode-projector]').addEventListener('click',()=>{EQ.Accessibility.set('projector',true);navigate('worlds')});
  }
  function studentEntry(){
    const cls=EQ.Store.activeClass();const content=`<div class="section-head"><div><span class="kicker">Student entry</span><h2>Entre na transmissão</h2><p class="muted">Use apenas um apelido ou número. Nenhum e-mail ou nome completo é necessário.</p></div></div><form id="student-form" class="card form-grid">
      <div class="field"><label for="class-code">Código da turma</label><input id="class-code" name="code" value="${esc(cls.code)}" required autocomplete="off"></div>
      <div class="field"><label for="student-nickname">Apelido</label><input id="student-nickname" name="nickname" value="${esc(EQ.Store.activeProfile()?.nickname||'Explorer')}" required autocomplete="nickname"></div>
      <div class="field"><label for="student-grade">Ano</label><select id="student-grade" name="grade"><option value="6">6º ano</option><option value="7">7º ano</option><option value="8">8º ano</option><option value="9">9º ano</option></select></div>
      <div class="field"><label for="student-support">Nível de suporte</label><select id="student-support" name="support"><option value="0">Padrão</option><option value="1">Suporte 1</option><option value="2">Suporte 2</option><option value="3">Suporte 3</option></select></div><div class="field"><label for="play-mode">Modo de sala</label><select id="play-mode" name="playMode"><option value="individual">Individual</option><option value="team">Equipe</option><option value="projector">Projetor</option></select></div>
      <div class="field full"><button class="btn" type="submit">Conectar ao sinal</button></div></form>`;
    app.innerHTML=shell(content,{back:'mode'});bindGlobal();app.querySelector('#student-form').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),code=String(fd.get('code')).trim().toUpperCase(),found=EQ.Store.get().classes.find(c=>c.code.toUpperCase()===code);if(!found){toast('Código não encontrado neste dispositivo. Use ECHO-26 para a turma demo.');return}const grade=Number(fd.get('grade')),nickname=String(fd.get('nickname')).trim(),support=Number(fd.get('support'));EQ.Store.update(d=>{let p=d.profiles.find(x=>x.nickname.toLowerCase()===nickname.toLowerCase()&&x.classId===found.id);if(!p){p={id:'p-'+Date.now(),nickname,classId:found.id,grade,avatar:'◉',xp:0,energy:0,completed:[],badges:[],supportLevel:support};d.profiles.push(p)}p.grade=grade;p.supportLevel=support;d.activeProfileId=p.id;d.activeClassId=found.id;d.settings.supportLevel=support;d.settings.playMode=String(fd.get('playMode')||'individual');d.settings.projector=d.settings.playMode==='projector'},true);navigate('worlds')});
  }
  function worlds(){
    const p=EQ.Store.activeProfile(),content=`<div class="section-head"><div><span class="kicker">Signal map</span><h2>Quatro distritos.<br>Uma única mensagem.</h2><p class="muted">Cada mundo trabalha o conteúdo do 2º trimestre em uma aventura conectada.</p></div><button class="btn secondary" data-nav="progress">Ver progresso</button></div><div class="grid four">${Object.entries(EQ.CURRICULUM.grades).map(([g,w])=>{const ms=EQ.CONTENT.missions.filter(m=>m.grade==g),done=ms.filter(m=>p?.completed.includes(m.id)).length;return `<button class="world-card" data-grade="${g}" style="--world:${w.colors.world};--world-soft:${w.colors.soft}"><span class="grade">${g}</span><span class="world-icon">${w.icon}</span><span class="kicker">${g}º ano</span><h3>${w.name}</h3><p class="muted">${w.description}</p><div class="progress-track"><div class="progress-fill" style="width:${done/3*100}%"></div></div><p class="tiny muted">${done}/3 missões restauradas</p></button>`}).join('')}</div><br><section class="card"><span class="kicker">Objetivo coletivo</span><h3>Restaurar 1.000 unidades de energia do sinal</h3><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,(EQ.Store.get().unlocks.classEnergy||0)/10)}%"></div></div><p class="muted tiny">${EQ.Store.get().unlocks.classEnergy||0} / 1.000 unidades</p></section>`;
    app.innerHTML=shell(content,{back:'mode'});bindGlobal();app.querySelectorAll('[data-grade]').forEach(b=>b.addEventListener('click',()=>navigate('missions/'+b.dataset.grade)));
  }
  function missions(grade){
    grade=Number(grade);setWorld(grade);const w=EQ.CURRICULUM.grades[grade],p=EQ.Store.activeProfile(),ms=EQ.CONTENT.missions.filter(m=>m.grade===grade),allDone=ms.every(m=>p?.completed.includes(m.id)),boss=EQ.CONTENT.bosses[grade];
    const content=`<div class="section-head"><div><span class="kicker">${grade}º ano · ${w.name}</span><h2>${w.chapter}</h2><p class="muted">${w.description}</p></div><div class="cta-row"><span class="badge">${w.topics.length} conteúdos conectados</span><button class="btn secondary small" data-freeplay="${grade}">Free Play</button></div></div><div class="grid three">${ms.map((m,i)=>`<button class="mission-card ${p?.completed.includes(m.id)?'done':''}" data-mission="${m.id}"><span class="mission-number">MISSION 0${i+1}</span><h3>${m.title}</h3><p>${m.description}</p><div class="tag-row">${m.objectives.slice(0,3).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></button>`).join('')}</div><br><button class="mission-card ${allDone?'':'locked'}" data-boss="${grade}" ${allDone?'':'aria-disabled="true"'}><span class="mission-number">CLASS BOSS</span><h3>${boss.title}</h3><p>${boss.description}</p><span class="badge">${allDone?'Disponível':'Conclua as três missões'}</span></button>`;
    app.innerHTML=shell(content,{back:'worlds'});bindGlobal();app.querySelectorAll('[data-mission]').forEach(b=>b.addEventListener('click',()=>{runtime.storyIndex=0;navigate('story/'+b.dataset.mission)}));const free=app.querySelector('[data-freeplay]');if(free)free.addEventListener('click',()=>navigate('freeplay/'+grade));app.querySelector('[data-boss]').addEventListener('click',e=>{if(!allDone){toast('O Class Boss é desbloqueado após as três missões.');return}navigate('boss/'+grade)});
  }
  function findMission(id){return EQ.CONTENT.missions.find(m=>m.id===id)}
  function story(id){
    const m=findMission(id);if(!m){navigate('worlds');return}setWorld(m.grade);runtime.currentMission=m;const scene=m.story[runtime.storyIndex]||m.story[0],char=EQ.CONTENT.characters[scene.speaker]||{icon:'◉'};
    const content=`<div class="story-layout"><section class="scene"><div class="scene-art"></div><div class="dialogue-box"><span class="speaker">${char.icon} ${esc(scene.speaker)}</span><p class="dialogue" lang="en">${esc(scene.text)}</p><div class="cta-row"><button class="btn secondary" data-speak-story>▶ Listen</button><button class="btn" data-next-story>${runtime.storyIndex<m.story.length-1?'Continue':'Start mission'}</button></div></div></section><aside class="card"><span class="kicker">Mission briefing</span><h3>${esc(m.title)}</h3><p class="muted">${esc(m.description)}</p><ul class="objective-list">${m.objectives.map(o=>`<li>${esc(o)}</li>`).join('')}</ul><div class="support-banner"><span>◇</span><div><strong>15–25 minutos</strong><div class="tiny">Exploração, prática, decisão e exit ticket.</div></div></div></aside></div>`;
    app.innerHTML=shell(content,{back:'missions/'+m.grade,wide:true});bindGlobal();app.querySelector('[data-speak-story]').addEventListener('click',()=>EQ.Audio.speak(scene.text,false));app.querySelector('[data-next-story]').addEventListener('click',()=>{if(runtime.storyIndex<m.story.length-1){runtime.storyIndex++;story(id)}else navigate('play/'+id)});
  }
  function playMission(id){
    const m=findMission(id);if(!m){navigate('worlds');return}setWorld(m.grade);runtime.currentMission=m;app.innerHTML=shell('<div id="runner-root"></div>',{back:'missions/'+m.grade,wide:true});bindGlobal();
    new EQ.Minigames.Runner(document.getElementById('runner-root'),{questions:m.questions,meta:{mode:'mission',missionId:m.id,grade:m.grade,label:m.title},onComplete:(summary,session)=>{runtime.lastSummary=summary;runtime.lastSession=session;navigate('decision/'+m.id)}});
  }
  function decision(id){
    const m=findMission(id);if(!m)return;setWorld(m.grade);const options=[['Share the clue','Compartilhe a pista com todas as equipes.'],['Follow Glitch','Siga Glitch por uma rota instável, mas criativa.'],['Restore a memory','Use a energia recuperada para restaurar uma memória de Echo.']];
    const content=`<div class="section-head"><div><span class="kicker">Team decision</span><h2>The signal is waiting.</h2><p class="muted">Discuta com o grupo e vote. Não existe uma única escolha correta.</p></div></div><div class="grid three">${options.map((o,i)=>`<button class="mode-card" data-decision="${i}"><span class="mode-icon">${['◇','⌁','◉'][i]}</span><h3>${o[0]}</h3><p class="muted">${o[1]}</p></button>`).join('')}</div>`;app.innerHTML=shell(content,{back:'missions/'+m.grade});bindGlobal();app.querySelectorAll('[data-decision]').forEach(b=>b.addEventListener('click',()=>{runtime.decision=options[Number(b.dataset.decision)][0];EQ.Store.update(d=>d.unlocks.classEnergy=(d.unlocks.classEnergy||0)+25,true);navigate('exit/'+id)}));
  }
  function exitTicket(id){
    const m=findMission(id);if(!m)return;setWorld(m.grade);const content=`<div class="section-head"><div><span class="kicker">Exit ticket</span><h2>Antes de fechar o sinal…</h2><p class="muted">Três respostas rápidas: compreensão, aplicação e autoavaliação.</p></div></div><form id="exit-form" class="card form-grid"><div class="field full"><label for="exit-reflection">${m.exitTicket[0].prompt}</label><textarea id="exit-reflection" name="reflection" required></textarea></div><div class="field full"><label for="exit-application">${m.exitTicket[1].prompt}</label><textarea id="exit-application" name="application" required></textarea></div><div class="field full"><label for="exit-self">${m.exitTicket[2].prompt}</label><select id="exit-self" name="self">${m.exitTicket[2].options.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field full"><button class="btn" type="submit">Finalizar missão</button></div></form>`;app.innerHTML=shell(content,{back:'decision/'+id});bindGlobal();app.querySelector('#exit-form').addEventListener('submit',e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));EQ.Store.update(d=>{const s=d.sessions.find(x=>x.id===runtime.lastSession?.id);if(s){s.exitTicket=values;s.teamDecision=runtime.decision}},true);navigate('results/'+id)});
  }
  function results(id){
    const m=findMission(id),s=runtime.lastSummary||{accuracy:0,score:0,correct:0,total:0,durationSeconds:0};if(!m)return;setWorld(m.grade);const content=`<div class="section-head"><div><span class="kicker">Mission complete</span><h2>Signal fragment restored.</h2><p class="muted">${esc(m.title)} agora faz parte da memória de Echo.</p></div></div><div class="grid four"><div class="metric"><strong>${s.accuracy}%</strong><span>Precisão</span></div><div class="metric"><strong>${s.correct}/${s.total}</strong><span>Desafios concluídos</span></div><div class="metric"><strong>${s.score}</strong><span>Energia pessoal</span></div><div class="metric"><strong>${Math.ceil(s.durationSeconds/60)} min</strong><span>Tempo</span></div></div><br><div class="grid two"><section class="card"><span class="kicker">Evidence of learning</span><h3>${esc(EQ.CURRICULUM.grades[m.grade].skills[0].objective)}</h3><p class="muted">${esc(EQ.CURRICULUM.grades[m.grade].skills[0].evidence)}</p><span class="badge">${teacherStatus(s.accuracy)}</span></section><section class="card"><span class="kicker">Next step</span><h3>${s.accuracy<70?'Review mission recommended':'New route unlocked'}</h3><p class="muted">${s.accuracy<70?'Refaça a missão com pistas e tradução ativadas, sem perder o progresso atual.':'Continue para a próxima missão ou explore o modo livre.'}</p></section></div><br><div class="cta-row"><button class="btn" data-nav="missions/${m.grade}">Voltar ao mapa</button><button class="btn secondary" data-replay>Jogar novamente</button></div>`;app.innerHTML=shell(content,{back:'missions/'+m.grade});bindGlobal();app.querySelector('[data-replay]').addEventListener('click',()=>navigate('play/'+id));
  }
  function teacherStatus(v){let out=EQ.CURRICULUM.statusLabels[0].label;EQ.CURRICULUM.statusLabels.forEach(x=>{if(v>=x.min)out=x.label});return out}
  function boss(grade){
    grade=Number(grade);setWorld(grade);const b=EQ.CONTENT.bosses[grade],ids=b.questionIds,all=EQ.CONTENT.missions.flatMap(m=>m.questions),questions=ids.map(id=>all.find(q=>q.id===id)).filter(Boolean);app.innerHTML=shell(`<div class="section-head"><div><span class="kicker">Class Boss · ${grade}º ano</span><h2>${esc(b.title)}</h2><p class="muted">${esc(b.description)}</p></div></div><div id="runner-root"></div>`,{back:'missions/'+grade,wide:true});bindGlobal();new EQ.Minigames.Runner(document.getElementById('runner-root'),{questions,meta:{mode:'boss',grade,label:b.title},onComplete:(summary,session)=>{runtime.lastSummary=summary;runtime.lastSession=session;showBossResult(grade,b,summary)}});
  }
  function showBossResult(grade,b,s){app.innerHTML=shell(`<div class="section-head"><div><span class="kicker">Boss cleared</span><h2>${s.accuracy>=75?'District restored.':'The signal survived.'}</h2><p class="muted">${s.accuracy>=75?'A nova parte da mensagem de Echo foi desbloqueada.':'A turma pode tentar novamente com mais pistas, sem perder pontos.'}</p></div></div><section class="card"><h3>${esc(b.title)}</h3><div class="grid three"><div class="metric"><strong>${s.accuracy}%</strong><span>Precisão coletiva</span></div><div class="metric"><strong>${s.score}</strong><span>Energia</span></div><div class="metric"><strong>${s.attempts}</strong><span>Tentativas</span></div></div></section><br><button class="btn" data-nav="missions/${grade}">Continuar</button>`,{back:'missions/'+grade});bindGlobal()}
  function progress(){
    const p=EQ.Store.activeProfile(),sessions=EQ.Store.get().sessions.filter(s=>s.profileId===p?.id&&s.endedAt),byGrade=[6,7,8,9].map(g=>({g,done:EQ.CONTENT.missions.filter(m=>m.grade===g&&p?.completed.includes(m.id)).length}));const content=`<div class="section-head"><div><span class="kicker">Student progress</span><h2>${esc(p?.nickname||'Explorer')}</h2><p class="muted">Progresso privado neste dispositivo. Sem ranking individual público.</p></div><span class="badge">${p?.xp||0} XP</span></div><div class="grid four">${byGrade.map(x=>`<div class="metric"><strong>${x.done}/3</strong><span>${x.g}º ano</span></div>`).join('')}</div><br><div class="grid two"><section class="card"><span class="kicker">Cosmetics</span><h3>Signal Scout</h3><p class="muted">Avatares, molduras e companheiros são recompensas visuais sem dinheiro real.</p><div class="tag-row"><span class="tag">◉ Echo Orb</span><span class="tag">◇ Scout Frame</span><span class="tag">⌁ Glitch Trail</span></div></section><section class="card"><span class="kicker">Recent activity</span><h3>${sessions.length} sessões concluídas</h3><p class="muted">Energia acumulada: ${p?.energy||0}</p><button class="btn secondary" data-nav="worlds">Continuar aventura</button></section></div>`;app.innerHTML=shell(content,{back:'worlds'});bindGlobal();
  }
  function teacher(section){
    section=section||'overview';const labels={overview:'Visão geral',classes:'Turma e equipes',quick:'Desafio rápido',editor:'Editor de conteúdo',reports:'Relatórios',backup:'Backup',accessibility:'Acessibilidade'};let body='';if(section==='overview')body=EQ.Teacher.overviewHTML();if(section==='classes')body=EQ.Teacher.classesHTML();if(section==='quick')body=EQ.Teacher.quickHTML();if(section==='editor')body=EQ.Teacher.editorHTML();if(section==='reports')body=EQ.Teacher.reportsHTML();if(section==='backup')body=EQ.Teacher.backupHTML();if(section==='accessibility')body=`<div class="section-head"><div><span class="kicker">Accessibility</span><h2>Ajustes da experiência</h2><p class="muted">Acessibilidade faz parte da arquitetura principal e vale para a mesma história.</p></div></div>${EQ.Accessibility.settingsHTML()}`;
    const content=`<div class="dashboard"><aside class="sidebar">${Object.entries(labels).map(([k,v])=>`<button class="${section===k?'active':''}" data-teacher-nav="${k}">${v}</button>`).join('')}<button data-nav="worlds">Abrir mapa</button></aside><section>${body}</section></div>`;app.innerHTML=shell(content,{back:'mode',wide:true});bindGlobal();app.querySelectorAll('[data-teacher-nav]').forEach(b=>b.addEventListener('click',()=>navigate('teacher/'+b.dataset.teacherNav)));EQ.Teacher.bind(app,navigate);if(section==='accessibility')EQ.Accessibility.bind(app);
  }
  function accessibility(){const content=`<div class="section-head"><div><span class="kicker">Support Mode</span><h2>Acessibilidade e áudio</h2><p class="muted">Ajustes persistentes para leitura, som, movimento, toque e apoio pedagógico.</p></div></div>${EQ.Accessibility.settingsHTML()}`;app.innerHTML=shell(content,{back:'worlds'});bindGlobal();EQ.Accessibility.bind(app)}
  function credits(){
    const chars=Object.entries(EQ.CONTENT.characters);const content=`<div class="section-head"><div><span class="kicker">About the signal</span><h2>Uma aventura de inglês para a sala real.</h2><p class="muted">Narrativa, colaboração, acessibilidade e relatórios locais em HTML, CSS e JavaScript puro.</p></div></div><div class="grid two"><section class="card"><h3>Princípios curriculares</h3><ul class="objective-list"><li>Inglês como língua franca e comunicação significativa.</li><li>Listening, speaking, reading, writing e consciência intercultural.</li><li>Gramática sempre ligada a decisões, histórias e tarefas práticas.</li><li>Códigos BNCC/CRMG não são inventados: a associação deve ser conferida nos documentos oficiais adotados pela escola.</li></ul></section><section class="card"><h3>Privacidade e funcionamento</h3><ul class="objective-list"><li>Sem nome completo, e-mail, telefone, foto ou localização.</li><li>Dados ficam no dispositivo até exportação explícita.</li><li>Funciona offline, por caminhos relativos e sem servidor obrigatório.</li><li>Compatível com mouse, teclado e toque.</li></ul></section></div><br><span class="kicker">Characters</span><div class="grid three">${chars.map(([n,c])=>`<div class="card flat"><span style="font-size:2.4rem;color:${c.color}">${c.icon}</span><h3>${n}</h3><p class="muted">${c.role}</p></div>`).join('')}</div><br><button class="btn" data-nav="title">Voltar ao início</button>`;app.innerHTML=shell(content,{back:'title'});bindGlobal();
  }
  function startQuickChallenge(grade,questions){if(!questions.length){toast('Nenhuma questão combina com esses filtros.');return}runtime.quickQuestions=questions;runtime.quickGrade=grade;runtime.challengeMode='quick';runtime.challengeBack='teacher/quick';runtime.challengeLabel='Quick Challenge';navigate('quick-play')}
  function startReviewChallenge(grade,questions){if(!questions.length){toast('Nenhum erro disponível para revisão.');return}runtime.quickQuestions=questions;runtime.quickGrade=grade;runtime.challengeMode='review';runtime.challengeBack='teacher/overview';runtime.challengeLabel='Review Mission';navigate('quick-play')}
  function quickPlay(){const qs=runtime.quickQuestions;if(!qs){navigate(runtime.challengeBack||'teacher/quick');return}setWorld(runtime.quickGrade);app.innerHTML=shell('<div id="runner-root"></div>',{back:runtime.challengeBack,wide:true});bindGlobal();new EQ.Minigames.Runner(document.getElementById('runner-root'),{questions:qs,meta:{mode:runtime.challengeMode,grade:runtime.quickGrade,label:runtime.challengeLabel},onComplete:s=>{app.innerHTML=shell(`<div class="section-head"><div><span class="kicker">${runtime.challengeLabel} complete</span><h2>${s.accuracy}% de precisão</h2><p class="muted">${runtime.challengeMode==='review'?'Os conteúdos com maior dificuldade foram praticados novamente.':'A atividade foi registrada nos relatórios da turma.'}</p></div></div><button class="btn" data-nav="teacher/overview">Ver relatório</button>`,{back:'teacher/overview'});bindGlobal()}})}
  function freePlay(grade){grade=Number(grade);setWorld(grade);const questions=EQ.Minigames.shuffle(EQ.CONTENT.missions.filter(m=>m.grade===grade).flatMap(m=>m.questions)).slice(0,7);app.innerHTML=shell('<div class="section-head"><div><span class="kicker">Free Play</span><h2>Treino sem pressão</h2><p class="muted">Esta sessão não entra nos relatórios formais nem altera a conclusão das missões.</p></div></div><div id="runner-root"></div>',{back:'missions/'+grade,wide:true});bindGlobal();new EQ.Minigames.Runner(document.getElementById('runner-root'),{questions,meta:{mode:'freeplay',grade,label:'Free Play'},onComplete:s=>{app.innerHTML=shell(`<div class="section-head"><div><span class="kicker">Free Play complete</span><h2>${s.accuracy}% de precisão</h2><p class="muted">Treino concluído sem impacto no relatório formal.</p></div></div><button class="btn" data-nav="missions/${grade}">Voltar às missões</button>`,{back:'missions/'+grade});bindGlobal()}})}
  function render(){
    EQ.Accessibility.apply();const parts=route().split('/'),head=parts[0];
    try{
      if(head==='title')titleScreen();else if(head==='mode')modeScreen();else if(head==='student-entry')studentEntry();else if(head==='worlds')worlds();else if(head==='missions')missions(parts[1]);else if(head==='story')story(parts[1]);else if(head==='play')playMission(parts[1]);else if(head==='decision')decision(parts[1]);else if(head==='exit')exitTicket(parts[1]);else if(head==='results')results(parts[1]);else if(head==='boss')boss(parts[1]);else if(head==='progress')progress();else if(head==='teacher')teacher(parts[1]);else if(head==='accessibility')accessibility();else if(head==='credits')credits();else if(head==='quick-play')quickPlay();else if(head==='freeplay')freePlay(parts[1]);else titleScreen();
    }catch(err){console.error(err);app.innerHTML=`<div class="page"><section class="card"><h2>O sinal encontrou um erro.</h2><p class="muted">${esc(err.message)}</p><button class="btn" data-nav="title">Reiniciar navegação</button></section></div>`;bindGlobal()}
    app.focus({preventScroll:true});
  }
  window.addEventListener('hashchange',render);window.addEventListener('DOMContentLoaded',()=>{EQ.Accessibility.apply();render()});
  EQ.App={navigate,render,toast,startQuickChallenge,startReviewChallenge};
})();
